### ISSUE TITLE
ObjectDisposedException in SequenceGenerator

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#764] opened 2020-09-04 14:06 UTC
After a time I get the ObjectDisposedException error. Maybe it is affected by the Autitrail.

iXISXRM.Win.exe Error: 0 : 04.09.20 15:39:46.066	================================================================================
The error occurred:

	Type:       ObjectDisposedException
	Message:    Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "DevExpress.Xpo.UnitOfWork(57)".
	Data:       0 entries
	Stack trace:

   bei DevExpress.Xpo.Session.Connect()
   bei DevExpress.Xpo.Session.get_ObjectLayer()
   bei DevExpress.Xpo.Session.get_DataLayer()
   bei DevExpress.Persistent.AuditTrail.AuditDataStore`2.Save(Session session, List`1 itemsToSave, IAuditTimestampStrategy timestampStrategy, String currentUserName)
   bei DevExpress.Persistent.AuditTrail.AuditTrailService.SaveAuditDataByDefault(Session session, List`1 itemsToSave)
   bei DevExpress.Persistent.AuditTrail.AuditTrailService.InternalSaveAuditData(Session session, List`1 itemsToSave)
   bei DevExpress.Persistent.AuditTrail.AuditTrailService.SaveAuditData(Session session)
   bei DevExpress.ExpressApp.AuditTrail.Helpers.AuditTrailHelper.ObjectSpace_Committed(Object sender, EventArgs e)
   bei System.EventHandler.Invoke(Object sender, EventArgs e)
   bei DevExpress.ExpressApp.BaseObjectSpace.OnCommitted()
   bei DevExpress.ExpressApp.BaseObjectSpace.CommitChanges()
   bei Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorService.<>c__DisplayClass25_1.<GenerateSequences>b__5(Object o) in D:\a\1\s\src\Modules\SequenceGenerator\SequenceGeneratorService.cs:Zeile 195.
   bei System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Do.cs:Zeile 38.
	InnerException is null

**Comment by apobekiaris** [comment] 2020-09-04 15:34
can u test it without the audittrail? if we do not have exact repro steps resolving it can be the game of 20 questions

**Comment by CWolffIF** [comment] 2020-09-04 18:11
In my DEMO Project it works with Audittrail and without Audittrail.
How can I debug it in my main project ?

**Comment by apobekiaris** [comment] 2020-09-04 18:15
the symbols are distributed, I am sure you are aware of this you only need to enabled them and set the Break On Error

https://github.com/eXpandFramework/eXpand/wiki/HowToDebug

1. do u have issues doing so?
2. can u reproduce it consistently in your production app? maybe u can share the app in private?

**Comment by CWolffIF** [comment] 2020-09-04 18:54
Hi Tolis,
the symbols are loaded, but how to "set the Break On Error"?

**Comment by apobekiaris** [comment] 2020-09-04 18:57
VS menu debug/windows/exception settings and then check the CLR exception this will break on the exception location

![image](https://user-images.githubusercontent.com/159464/92276389-8db5f100-eef9-11ea-9b4d-8878b2fa8ba1.png)

note debugging this module is not trivial at all

**Comment by apobekiaris** [comment] 2020-09-04 18:59
i would load the XAF symbols as described in https://github.com/eXpandFramework/DevExpress.XAF/wiki/How-to-boost-your-DevExpress-Debugging-Experience then add a breakpoint into the dispose of the UnitOfWork and try to see what  is happening.

**Comment by CWolffIF** [comment] 2020-09-05 07:44
Maybe my screenshot helps.
"o" is null. There is a unitofwork in "space" but is seemed to be allready disposed.
![Unbenannt](https://user-images.githubusercontent.com/43132306/92300559-4ca2f880-ef5c-11ea-9a64-9bb602c761aa.PNG)

**Comment by apobekiaris** [comment] 2020-09-05 18:44
i understand where it throws I could blind safe guard it however I prefer to see what happens before and your post does not help. 

>After a time 

what the log says?

**Comment by CWolffIF** [comment] 2020-09-06 07:56
Hi Tolis,

thanks for your help. I think I got it.
"After a time" was the key. When I run the app and do nothing than after a time the error occurs. So I looked in all timed events and I found code that a derived  Session dispose. I don´t know why at all und I don´t why the code runs in 20.1.402. But this the error.

**Comment by apobekiaris** [comment] 2020-09-06 10:23
since you closed the case, my understanding is that is not relate to the module?

**Comment by CWolffIF** [comment] 2020-09-06 12:11
Yes you are right.

There is an error in my code. In 20.1.402 it works without error, in 20.1.70x not. But the reason was in my code.

**Comment by apobekiaris** [comment] 2020-09-09 05:53
unfortunately it loks like the #737 fix causes issues

**Comment by expand** [comment] 2020-09-11 15:42
The pre-release [2.201.15.4](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.15.4) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Increase_Sequence_When_creating_Nested_New_Objects_on_parent_saving #737 #764](https://github.com/eXpandFramework/DevExpress.XAF/commit/ea531630432e47d6ababd97fc096857a67b67fe3)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.
<details>
    <summary>Released packages:</summary>
1. [Xpand.Extensions v.2.202.47.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions)
 1. [Xpand.Extensions.Mono.Cecil v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil)
 1. [Xpand.Extensions.Office.Cloud v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud)
 1. [Xpand.Extensions.Reactive v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive)
 1. [Xpand.Extensions.XAF v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF)
 1. [Xpand.Extensions.XAF.Xpo v.2.202.44.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo)
 1. [Xpand.XAF.Core.All v.2.202.39.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Modules.AutoCommit v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)
 1. [Xpand.XAF.Modules.CloneMemberValue v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)
 1. [Xpand.XAF.Modules.CloneModelView v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)
 1. [Xpand.XAF.Modules.GridListEditor v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)
 1. [Xpand.XAF.Modules.HideToolBar v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)
 1. [Xpand.XAF.Modules.LookupCascade v.2.202.50.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)
 1. [Xpand.XAF.Modules.MasterDetail v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)
 1. [Xpand.XAF.Modules.ModelMapper v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)
 1. [Xpand.XAF.Modules.ModelViewInheritance v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance)
 1. [Xpand.XAF.Modules.Office.Cloud.Google v.2.202.9.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google)
 1. [Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.2.202.6.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft v.2.202.49.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.2.202.20.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.2.202.19.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo)
 1. [Xpand.XAF.Modules.OneView v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)
 1. [Xpand.XAF.Modules.PositionInListView v.2.202.19.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/PositionInListView)
 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)
 1. [Xpand.XAF.Modules.Reactive v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)
 1. [Xpand.XAF.Modules.Reactive.Logger v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)
 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)
 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)
 1. [Xpand.XAF.Modules.Reactive.Win v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)
 1. [Xpand.XAF.Modules.RefreshView v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)
 1. [Xpand.XAF.Modules.SequenceGenerator v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)
 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)
 1. [Xpand.XAF.Modules.ViewEditMode v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)
 1. [Xpand.XAF.Modules.ViewItemValue v.2.202.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewItemValue)
 1. [Xpand.XAF.Modules.ViewWizard v.2.202.10.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewWizard)
 1. [Xpand.XAF.Web.All v.2.202.39.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Win.All v.2.202.39.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Closed** 2021-05-03 16:00 UTC
Labels: Bug, Reactive.XAF, SequenceGenerator
