### ISSUE TITLE
Xpand.ExpressApp.MasterDetail.Win error

### ISSUE THREAD

**Issue by rodrigokiller** [eXpandFramework/eXpand#949] opened 2022-09-08 20:37 UTC
Hi.
After I install the NuGet eXpandMasterDetailWin (v22.1.401) - 
[Github](https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/MasterDetail), I get an error: 
```Could not load file or assembly 'System.Interactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)```

This error doesn't stop the app to run, but I can't get the app to work with MasterDetail mode, I am unable to create a dashboard inside Views, etc.

XAF: 22.1.4
.NET Core 6.0
Windows 11
WinForms

See the screenshots below:

![image](https://user-images.githubusercontent.com/1853922/189220355-fda78e02-05a3-4333-b6ff-d440f4c885a1.png)
![image](https://user-images.githubusercontent.com/1853922/189220387-6e866db6-dc30-450a-998a-1691f129c3e4.png)
![image](https://user-images.githubusercontent.com/1853922/189220325-4385ee0c-3146-4ad3-89e0-5e8ab01763ff.png)

**Comment by apobekiaris** [comment] 2022-09-09 13:22
did  you tried top install the `System.Reactive` package as prompted?

**Comment by rodrigokiller** [comment] 2022-09-09 15:56
@apobekiaris yes, I've installed `System.Reactive` v.5.0.0, `System.Interactive` v.5.0.0 and after getting the same error, i tried `System.Interactive` v6.0.1, also with the same errors.

![image](https://user-images.githubusercontent.com/1853922/189391639-c11cf2c3-2cb7-4a4c-9ef9-c5544aab4ad9.png)


![image](https://user-images.githubusercontent.com/1853922/189391694-01955c48-13f6-4d42-9d79-ef3774a83f2b.png)

**Comment by apobekiaris** [comment] 2022-09-09 17:08
is the assembly with the same version and signature located in your bin?

**Comment by apobekiaris** [comment] 2022-09-09 17:08
the Systen.Reactive 5

**Comment by rodrigokiller** [comment] 2022-09-09 17:35
yes, they have the same version.
The serial number (certificate) in my bin folder is 0568a2bc0bd12e0753ace5f4d01748c0.
I don't know if it has anything to do with the public token 94bc3704cddfc263. 
How can I audit that?

**Comment by rodrigokiller** [comment] 2022-09-14 18:47
Im still getting the errorr :/

**Comment by rodrigokiller** [comment] 2022-09-22 20:46
Hi there. I've recorded two videos.
The first one shows the error
The second, I was trying to use "XpandModelEditor", but I got some problems too.
I know that I said at some point something about xpand.xaf.modules.masterDetail, but I did not intend to do that. I want to use the eXpandMasterDetailWin module.
[Video 1 - Google Drive](https://drive.google.com/file/d/1pX_GzD3VRbBIsfpg53fIR4nIrOtU4t4B/view?usp=sharing)
[Video 2 - Google Drive](https://drive.google.com/file/d/18mm3oO9L-q1TXALEeokvl6xDjiFRFkS_/view?usp=sharing)
Thank you.

**Comment by apobekiaris** [comment] 2022-09-23 04:20
I suggest you improve your communication since you go for free support. Your videos are too long and cannot spent my time guessing. In any case a sample is required with repro instruction.

ps: at least for me the MasterDetail XVideoRental model opens fine although as I wrote here native Xaf MasterDetail view is the way to go, do not get tricked.

**Comment by apobekiaris** [comment] 2022-09-23 04:21
https://supportcenter.devexpress.com/internal/ticket/details/T1112752

**Comment by rodrigokiller** [comment] 2022-09-23 11:47
> I suggest you improve your communication since you go for free support. Your videos are too long and cannot spent my time guessing. In any case a sample is required with repro instruction.

Hi there. I'm sorry, I do not understand what you mean by "improve my communication". If there is anything that you don't understand, feel free to ask me. I will gladly try to explain it in a different way. I apologize if I, at any time, was disrespectful. And yes, I do know how GitHub works. I'm just trying to describe my issue with details. I expected (maybe in a wrong way) that the video would help the devs to understand what is causing the error here. Every new project that I've created, on two different computers, triggered this error. 



> https://supportcenter.devexpress.com/internal/ticket/details/T1112752

I'm sorry, what I am supposed to do here? I think that I misunderstand you. 😢 

Have a good day 😄

**Comment by apobekiaris** [comment] 2022-09-24 09:22
bad communication I am sorry. What I meant your videos are long without directions. Thanks for recording them but ot of much value. 

>yes, I've installed System.Reactive v.5.0.0, System.Interactive v.5.0.0 and after getting the same error, i tried System.Interactive v6.0.1, also with the same errors.

I repro this and fixed it with 

```xml
<PackageReference Include="System.Interactive" Version="6.0.1" />
```

let me know if it works for u.

**Comment by apobekiaris** [comment] 2022-09-24 10:23
I also mentioned XVideoRental as a good example to see how to configure the MasterDetail package. Here is an additional screenshot from the demo

![image](https://user-images.githubusercontent.com/159464/192092806-461e9e04-bb10-4701-a3aa-4174e5e3b7a8.png)

I had to make some updates in the XVideoRental, I will push the changes shortly.

**Comment by apobekiaris** [comment] 2022-09-29 13:19
eXpand.lab release [22.1.501.1](https://github.com/eXpandFramework/eXpand.lab/releases/22.1.501.1) includes commit that relate to this task:

* [XVideoRental masterDetail  #949](https://github.com/eXpandFramework/eXpand.lab/commit/78d7236e873762fa7f392d43f17cb4ce59835016)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by rodrigokiller** [comment] 2022-09-29 13:36
> let me know if it works for u.

Hi, it worked like this.
Also, before your reply, I've solved it doing this: 
copy the file: %USERPROFILE%\.nuget\packages\system.private.servicemodel\4.6.0\lib\netstandard2.0\System.Private.ServiceModel.dll
to 
%USERPROFILE%\.nuget\packages\system.servicemodel.primitives\4.6.0\ref\netcoreapp2.1

Late today, or tomorrow (GMT-3) i will get the last release and test it without doing any manual changes to the dlls.
I will let you know!
Thank you for your answer. 

PS. I am using the lib now and it works like a charm.

**Comment by yunits** [comment] 2022-11-04 14:49
Hi, this error still occurs.
I've tried to enable "Xpand.XAF.Modules.SequenceGenerator" and also installed for testing purposes 
System.Reactive v.5.0.0 and System.Interactive v.5.0.0
I am using your latest Xpand.XAF.Core.All package
What else can I do?

**Comment by apobekiaris** [comment] 2022-11-04 14:52
what about https://github.com/eXpandFramework/eXpand/issues/949#issuecomment-1256921148

**Comment by yunits** [comment] 2022-11-04 14:59
that doesn't change the error message

`	Type:       BadImageFormatException
	Message:    Could not load file or assembly 'System.Interactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
	Data:       0 entries
	Stack trace:
`

could it be something with .NET? I think .NET 6.0.10 is not net standard 2.0 anymore?
Latest Visual Studio automatically updates to the newest SDK.

**Comment by apobekiaris** [comment] 2022-11-04 15:00
post a sample

**Comment by rodrigokiller** [comment] 2022-11-04 15:42
hi @yunits , have you tried [this](https://github.com/eXpandFramework/eXpand/issues/949#issuecomment-1262295878) workaround?

**Comment by yunits** [comment] 2022-11-04 15:42
I solved my problem and this is just a hin for you, if someone else has the same error:
I guess it is something with .net standard 2.0 and net standard 2.1, like mentioned before.

Before I had a clean and only install of Visual Studio 2022 (never installed 2019 before). 2022 references in the latest version to .netstandard 2.1
`netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, Location=C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\6.0.10\netstandard.dll`

For testing purposes I've installed Visual Studio 2019, and now it everything works in Visual Studio 2022 (maybe "missing" files are now where they should be).

I've seen that you have support for .NET-Framework, that's why I was wondering how it could work with 2.1.
Conclusion: If someone has a new fresh Windows installation with only Visual Studio 2022, some dll's might be missing. Maybe you can deliver them or add any requirements to this..

Thanks for your fast responses.

**Comment by apobekiaris** [comment] 2022-11-04 15:45
both solution does not offer something I can use to address this for all. I need a repro sample

**Comment by yunits** [comment] 2022-11-04 15:49
as this error is machine specific, you cannot repro it without having the same machine setup as I have.
You could just try to setup a virtual machine with windwos 10 and only latest visual studio 2022.

As rodrigokiller earlier mentioned, he solved it by replacing 2.1 dll with 2.0 dll files.

however, my problem has been solved, thanks anyway.

**Comment by yunits** [comment] 2022-11-07 09:12
It's me again xD
I had this error again but now I guess I have a working solution:
System.Interactive 6.0.1 is required (after installing, Visual Studio has to be closed and started again)
And .NET6 SDK lower than current 6.0.10 is required (x86)
I tried it with 6.0.5 x86 SDK installer for Windows.
https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.5/6.0.5.md

x86 is important. If you use x64 it wouldn't work.

With a clean Visual Studio install you have only 6.0.10 in that folder C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\ 
and that netstandard.dll has the version 2.1

**Comment by apobekiaris** [comment] 2022-11-07 09:23
I guess these instruactions are suppose to help me repro it. But they really do not not, I have endless solutions and not have VS2019 installed and never tried to do any of the magic u suggested here. What I need is a sample I do not think this is enviromental issue.

**Comment by yunits** [comment] 2022-11-07 09:25
If I find a 100 % solution, I will get back to you. For the moment it is also hard to repro for me. I uninstalled my SDK to test if the error occurs, but it doesn't.. 
I don't know if some others have this same problem but if, then I would like to provide a working solution for them.
If the error occurs again, I will get back to you with my solution.

**Comment by apobekiaris** [comment] 2022-11-07 09:30
also when u face build problems consider that eXpand builds run on azure and unit/easy test there on the devops VM. In addition they are configured to failed even if there just one warning, aiming to provide the cleanest build possible to all

**Comment by yunits** [comment] 2022-11-07 09:35
I guess it was my fault that I didn't restarted Visual Studio after installing System.Interactive 6.0.1
I am not used to do this after installing nuget packages.

That is reproducable if you uninstall System.Interactive and install it and open Model Designer without Visual Studio restart.

For the moment that is all what I know.

Thanks for your fast responses all the time, you did a great job with your extensions :-)

**Comment by apobekiaris** [comment] 2022-11-07 09:38
>Model Designer

aha now u touch the problem, native Xaf ME is unpredictable, not because of Xaf but because of  VS designers craziness. Consider XpandModelEditor or the Xaf Standalone editor, you will sleep better

**Comment by apobekiaris** [comment] 2023-02-02 08:26
eXpand.lab release [22.2.400.0](https://github.com/eXpandFramework/eXpand.lab/releases/22.2.400.0) includes commit that relate to this task:

* [XVideoRental masterDetail  #949](https://github.com/eXpandFramework/eXpand.lab/commit/4a47133dfe6332d96e746eda11d85c0ea6523e50)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

To minimize version conflicts we recommend that you switch to PackageReference format and use only the [eXpandAgnostic](https://www.nuget.org/packages/eXpandAgnostic), [eXpandWin](https://www.nuget.org/packages/eXpandWin), [eXpandWeb](https://www.nuget.org/packages/eXpandWeb) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video). 

Thanks a lot for your contribution.

**Comment by expand** [comment] 2024-02-02 21:02
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2024-02-02 21:02 UTC
