### ISSUE TITLE
DelayedExceptionList : An asynchronous operation cannot be started at this time. 

### ISSUE THREAD

**Issue by larspl** [eXpandFramework/eXpand#543] opened 2019-09-15 16:51 UTC
**Describe the bug**
Dx 19.1.5, Xpand 19.1.504 ( nuget ) 
After deployment to prod environment we get the following errors:

the default.aspx in my webApp have Async="true" so the error is unclear for me. 

w3wp.exe Error: 0 : 15.09.19 17:52:59.399	no context	================================================================================
The error occurred:

	Type:       DelayedExceptionList
	Message:    An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.. 'Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueModule'. 'pnc.dgv.cdb.Web.CdbAspNetApplication'
	Data:       0 entries
	-------------------
	Delayed exception 0:

		Type:       DelayedException
		Message:    An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.. 'Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueModule'
		Data:       0 entries
		Stack trace:

		----------------
		InnerException:

				Type:       InvalidOperationException
				Message:    An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.
				Data:       0 entries
				Stack trace:

   at System.Web.AspNetSynchronizationContext.OperationStarted()
   at System.Reactive.Concurrency.SynchronizationContextExtensions.PostWithStartComplete(SynchronizationContext context, Action action)
   at System.Reactive.Concurrency.SynchronizationContextScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action)
   at System.Reactive.Linq.ObservableImpl.EventProducer`2.Session.<>c.<Connect>b__5_0(ValueTuple`3 tuple)
   at System.Reactive.Disposables.AnonymousDisposable`1.Dispose()
   at System.Reactive.Disposables.Disposable.TryDispose(IDisposable& fieldRef)
   at System.Reactive.Sink`1.Dispose()

-> all other infos see: link ( logfile.zip/rar ) 

**To Reproduce**

Rebuild and redeploy via TFS Build agent

**Expected behavior**
WebApp should start normal

**Desktop (please complete the following information):**
4x IIS 8.5 / Windows 2012R2

[logfile.zip](https://github.com/eXpandFramework/eXpand/files/3613998/logfile.zip)

**Comment by apobekiaris** [comment] 2019-09-15 20:10
1. is this a prod only case?
2. which version u had before?

**Comment by larspl** [comment] 2019-09-16 11:30
Hi Tolis, 

this error raise in dev and prod.
i start from 19.1.1

i found addition Errors in Log: 

I found some issues about "netstandard"

1.	The `access is denied` error, which may be related to system permissions.
2.	i have no clue why there is a mix of .NET Standard 2.0 assemblies in my ASP.NET WebForms project, netstandard.dll should not be normally used and installed in GAC.

These errors may be caused by Fasterflect.Netstandard, Mono.* and other assemblies that rely on netstandard.dll.

Any idea why the netstandard was loaded twice? 

The error occurred:

	Type:       CompilerErrorException
	Message:    Cannot compile the generated code. Please inspect the generated code via this exception's SourceCode property. The following errors occurred: 
(0, 0): Es wurde bereits eine Assembly mit der gleichen Identität 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' importiert. Entfernen Sie einen der doppelten Verweise.

	Data:       1 entries
			'ASPIMPERSONATING'		''
	Stack trace:

   bei DevExpress.ExpressApp.Utils.CodeGeneration.CSCodeCompiler.RaiseCompilerException(String sourceCode, CompilerResults compilerResults)
   bei Compile_Patch1(CSCodeCompiler sourceCode, String references, String[] assemblyFile, String )
   bei DevExpress.ExpressApp.DC.ClassGeneration.DCBuilder.GetAssembly(String assemblyFile)
   bei DevExpress.ExpressApp.DC.Xpo.XpoTypeInfoSource.GenerateEntities(String generatedAssemblyFile)
   bei DevExpress.ExpressApp.DC.TypesInfo.GenerateEntities(String generatedAssemblyFile)
   bei DevExpress.ExpressApp.XafApplication.SetupCore(String applicationName, IList`1 objectSpaceProviders, ApplicationModulesManager modulesManager, ISecurityStrategyBase security)
   bei DevExpress.ExpressApp.XafApplication.Setup()
   bei pnc.dgv.cdb.Web.Global.Session_Start(Object sender, EventArgs e) in C:\ws\dgv\WebCDB\pnc.dgv.cdb.Web\Global.asax.cs:Zeile 147.
   bei System.Web.SessionState.SessionStateModule.RaiseOnStart(EventArgs e)
   bei System.Web.SessionState.SessionStateModule.CompleteAcquireState()
   bei System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
   bei System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   bei System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   bei System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
	InnerException is null

--------------------------------------------------------------------------------
Loaded assemblies

,,

**Comment by apobekiaris** [comment] 2019-09-16 13:40
an assembly will load twice if it exists in 2 different probing paths, expand already ha netstandard.dll empeded and pacthes the Compile method in order to add it as reference. The end path could be the GAC installer may found netstard,dll in path and put it in GAC. Did u try removing the GAC one?

**Comment by larspl** [comment] 2019-09-18 08:50
If i remove it from GAC, i get this error:

The error occurred:

	Type:       TypeInitializationException
	Message:    Der Typeninitialisierer für "Xpand.Persistent.Base.General.XpandModuleBase" hat eine Ausnahme verursacht.
	Data:       1 entries
			'ASPIMPERSONATING'		''
	Stack trace:

   bei Xpand.Persistent.Base.General.XpandModuleBase..ctor()
   bei Xpand.ExpressApp.ViewVariants.XpandViewVariantsModule..ctor() in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ViewVariants\XpandViewVariantsModule.cs:Zeile 27.
   bei pnc.dgv.cdb.Web.CdbAspNetApplication.InitializeComponent() in C:\ws\dgv\WebCDB\pnc.dgv.cdb.Web\WebApplication.cs:Zeile 234.
   bei pnc.dgv.cdb.Web.CdbAspNetApplication..ctor() in C:\ws\dgv\WebCDB\pnc.dgv.cdb.Web\WebApplication.cs:Zeile 146.
   bei pnc.dgv.cdb.Web.Global.Session_Start(Object sender, EventArgs e) in C:\ws\dgv\WebCDB\pnc.dgv.cdb.Web\Global.asax.cs:Zeile 111.
   bei System.Web.SessionState.SessionStateModule.RaiseOnStart(EventArgs e)
   bei System.Web.SessionState.SessionStateModule.CompleteAcquireState()
   bei System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
   bei System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   bei System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   bei System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
	----------------
	InnerException:

			Type:       FileNotFoundException
			Message:    Die Datei oder Assembly "netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
			Data:       0 entries
			Stack trace:

   bei Xpand.Persistent.Base.General.XpandModuleBase..cctor()
			InnerException is null

if i have Add the netstandard.dll to .web project, 
i get the already "netstandard.dll" loaded and can loaded twice error.

**Comment by apobekiaris** [comment] 2019-09-18 09:01
why do you need to add the netsatndard.dll to your web project? this assembly is extracted to temp and then used as a reference to the ModelAssembly.dll

https://github.com/eXpandFramework/eXpand/blob/2518300e8e660014bc6f0b4ad2feb7e0628c192b/Xpand/Xpand.Persistent/Xpand.Persistent.Base/General/XpandModuleBase.cs#L92-L99

**Comment by apobekiaris** [comment] 2019-09-18 09:10
is the asssembly in that path? if not can u try adding it manually?

**Comment by apobekiaris** [comment] 2019-09-18 09:12
can u also try an empty xaf project with only the XpandViewVariants module installed? I mean web project. Maybe its reproducable that easy.

**Comment by larspl** [comment] 2019-09-18 13:08
first: i don't need netstandard.dll i get , in production and dev environment several errors that's related to netstandard. 

1. The error occurred:

	Type:       TypeInitializationException
	Message:    Der Typeninitialisierer für "Xpand.Persistent.Base.General.XpandModuleBase" hat eine Ausnahme verursacht.
	Data:       1 entries
			'ASPIMPERSONATING'		''
	Stack trace:

   bei Xpand.Persistent.Base.General.XpandModuleBase..ctor()
   bei Xpand.ExpressApp.ViewVariants.XpandViewVariantsModule..ctor() in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\ViewVariants\XpandViewVariantsModule.cs:Zeile 27.
   bei pnc.dgv.cdb.Web.CdbAspNetApplication.InitializeComponent() in C:\ws\dgv\WebCDB\pnc.dgv.cdb.Web\WebApplication.cs:Zeile 234.
   bei pnc.dgv.cdb.Web.CdbAspNetApplication..ctor() in C:\ws\dgv\WebCDB\pnc.dgv.cdb.Web\WebApplication.cs:Zeile 146.
   bei pnc.dgv.cdb.Web.Global.Session_Start(Object sender, EventArgs e) in C:\ws\dgv\WebCDB\pnc.dgv.cdb.Web\Global.asax.cs:Zeile 111.
   bei System.Web.SessionState.SessionStateModule.RaiseOnStart(EventArgs e)
   bei System.Web.SessionState.SessionStateModule.CompleteAcquireState()
   bei System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
   bei System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   bei System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   bei System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
	----------------
	InnerException:

			Type:       FileNotFoundException
			Message:    Die Datei oder Assembly "netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
			Data:       0 entries
			Stack trace:

   bei Xpand.Persistent.Base.General.XpandModuleBase..cctor()
			InnerException is null

if i have the netstandard.dll NOR in GAC and not assigned. 

if you can solve this case, it will help.


2. in prod system, 
i got a problem that the 
c:\windows\temp\netstandard.dll is already in use - the app crash with a access denied on c:\windows\temp\netstandard.dll

**Comment by apobekiaris** [comment] 2019-09-18 21:12
try these steps please and report how they work
1. Create and empty xaf solution
2. install the XpandViewVariants module
3. Run the web app.
4. Look in your {Path.GetTempPath()}\\netstandard for the assembly in my machine is C:\Users\Tolis\AppData\Local\Temp\netstandard\netstandard.dll

does this works?

**Comment by apobekiaris** [comment] 2019-10-10 15:03
it looks like the XAF team can reproduce the case follwing those steps I just posted and they send me a sample. 

I have to ask you next time to try answer my questions if u have time. #565 also looks the same

**Comment by larspl** [comment] 2019-10-10 17:06
Hi Tolis, sounds good. I look forward to see a update in this case. I’m ready also on the upcoming weekend. Just let me know. Cheers Lars

**Comment by expand** [comment] 2019-10-10 18:30
eXpand.lab release [19.1.604.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.604.3) includes commit that relate to this task:

* [Netstandard should not be injected to DC assembly #543](https://github.com/eXpandFramework/eXpand.lab/commit/82fc58815d2493db7b457553d70970937acc9c0b)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by larspl** [comment] 2019-10-11 10:46
> 
> 
> eXpand.lab release [19.1.604.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.604.3) includes commit that relate to this task:
> 
>     * [Netstandard should not be injected to DC assembly #543](https://github.com/eXpandFramework/eXpand.lab/commit/82fc58815d2493db7b457553d70970937acc9c0b)
> 
> 
> Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.
> 
> Thanks a lot for your contribution.

Hi Tolis., 

it seams that the netstandard.dll linking in my DC XAF solution is gone. Thanks. But i can't get my app running/debug ing while the Xpand.FasterFlect is still depend on netstandard.dll.

**Comment by apobekiaris** [comment] 2019-10-12 05:32
>it seams that the netstandard.dll linking in my DC XAF solution is gone.

this is not correct if u look at the changes on this commit u can tell that only the douplicate dependency has gone as I mentioned to u in #565 many modules are already ported to netstandard

**Comment by apobekiaris** [comment] 2019-10-12 05:35
it looks however that there is a problem that affects all web and comes from the Reactive.Logger which should affect your project as well as u use Sesystem.Web #581

**Comment by apobekiaris** [comment] 2019-10-12 05:36
I cannot confirm that it is the root of your cause though cause I do not have a way to repro it in any case when the bot notifies u update and let me know

**Comment by expand** [comment] 2019-10-12 06:00
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ReactiveLoggerService RefreshViewDataSource fails the web #581 #543 #565](https://github.com/eXpandFramework/DevExpress.XAF/commit/8b976e7ef674a254909c7461b2b73f73042226f8)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment] 2019-12-12 03:01
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2019-12-12 03:01 UTC
Labels: Bug, System.Web

**Comment by apobekiaris** [comment] 2020-01-19 12:10
see #661
