### ISSUE TITLE
 Xpand.Persistent.Base.General.SequenceGenerator.GenerateSequence "returns null"

### ISSUE THREAD

**Issue by IFBDahmen** [eXpandFramework/eXpand#737] opened 2020-07-20 10:09 UTC
I'm creating an API to a Win-Application with Xpo-Objects.
In the Win-Application (in the XPCustomObject) we have the code below:

 protected override void OnSaving()
        {
            if (!IsDeleted)
            {
                if (Session.IsNewObject(this))
                    SequenceGenerator.GenerateSequence(this);
...

Executing it in the Win-Application it works.
Executing it in the API the Sequence stays zero.
But its always the indentical Code-position.

 Assembly Xpand.Persistent.Base, Version=19.2.702.0

**Comment by apobekiaris** [comment] 2020-07-20 12:41
i suggest you switch to the sequencegenerator module, in latest version the implementation u use does not exist

https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator

**Comment by IFBDahmen** [comment] 2020-07-23 15:19
Thanks for your quick answer. 
Now we updated our System.
We still have some issues.
 After adding some Sequence Storage(s) the list looks like this:
![grafik](https://user-images.githubusercontent.com/68540300/88303586-7e8f3100-cd07-11ea-8af0-b4d3e19c9831.png)

and some members we referenced in the list doesn't increment. 

Best Regards

**Comment by apobekiaris** [comment] 2020-07-23 15:23
please provide simple repro samples in order to prioritize a failing case.

**Comment by IFBDahmen** [comment] 2020-08-11 12:19
[Solution3.zip](https://github.com/eXpandFramework/eXpand/files/5056817/Solution3.zip)

I created an example solution.
so the steps to recreate our issue:
1. start "solution3.win"
2. create an sequencegenerator for student (stundent.ID) in the application
3. start webApplication1
4. put a break point in homeController 
you'll see the created student wont have an ID or it is still zero.

So what are we doing wrong?

Best regards

**Comment by apobekiaris** [comment] 2020-08-13 09:32
the solution u posted is in a bad shape and spent a lot of time for trying to make it compile however failed and it really beats me what you try to do. 

The SequenceGenerator standalone installation can be done as per screencast in https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules#modules-list. This works for all XAF versions, 

Did  you tried it? 

We have easytests on the scenario so it works on the EasyTested XAF application for each build. 

Or maybe you want to use expandFramework modules and get SequenceGenerator pre-installed as part of the `eXpandSystem` module so you are looking to install at least the https://www.nuget.org/packages/eXpandAgnostic and depending on your needs you might need the https://www.nuget.org/packages/eXpandWin or the https://www.nuget.org/packages/eXpandWeb

**Comment by expand** [comment] 2020-08-13 16:31
The pre-release [2.201.13.1](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.13.1) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [SequenceGenerator: fails to start when empty database #737](https://github.com/eXpandFramework/DevExpress.XAF/commit/6ece42b7caea3d52ff3cdbab24d7967ce943e04f)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.
<details>
    <summary>Released packages:</summary>
1. [Xpand.Extensions v.2.202.41.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions)
 1. [Xpand.Extensions.Mono.Cecil v.2.202.37](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil)
 1. [Xpand.Extensions.Office.Cloud v.2.202.41.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud)
 1. [Xpand.Extensions.Reactive v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive)
 1. [Xpand.Extensions.XAF v.2.202.42.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF)
 1. [Xpand.Extensions.XAF.Xpo v.2.202.38.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo)
 1. [Xpand.XAF.Core.All v.2.202.37.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Modules.AutoCommit v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)
 1. [Xpand.XAF.Modules.CloneMemberValue v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)
 1. [Xpand.XAF.Modules.CloneModelView v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)
 1. [Xpand.XAF.Modules.GridListEditor v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)
 1. [Xpand.XAF.Modules.HideToolBar v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)
 1. [Xpand.XAF.Modules.LookupCascade v.2.202.44.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)
 1. [Xpand.XAF.Modules.MasterDetail v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)
 1. [Xpand.XAF.Modules.ModelMapper v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)
 1. [Xpand.XAF.Modules.ModelViewInheritance v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance)
 1. [Xpand.XAF.Modules.Office.Cloud.Google v.2.202.0](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft v.2.202.43.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.2.202.15.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.2.202.13.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo)
 1. [Xpand.XAF.Modules.OneView v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)
 1. [Xpand.XAF.Modules.PositionInListView v.2.202.13.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/PositionInListView)
 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)
 1. [Xpand.XAF.Modules.Reactive v.2.202.42.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)
 1. [Xpand.XAF.Modules.Reactive.Logger v.2.202.42.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)
 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)
 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)
 1. [Xpand.XAF.Modules.Reactive.Win v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)
 1. [Xpand.XAF.Modules.RefreshView v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)
 1. [Xpand.XAF.Modules.SequenceGenerator v.2.202.42.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)
 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)
 1. [Xpand.XAF.Modules.ViewEditMode v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)
 1. [Xpand.XAF.Modules.ViewItemValue v.2.202.8.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewItemValue)
 1. [Xpand.XAF.Modules.ViewWizard v.2.202.5.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewWizard)
 1. [Xpand.XAF.Web.All v.2.202.37.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Win.All v.2.202.37.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by IFBDahmen** [comment] 2020-08-17 18:28
Hello apobekiaris,
I'm sorry we had some communication problems.
We already use the SequenceStorage in simple ways - it works.
this is my example solution:
https://github.com/IFBDahmen/API 

the problem is still there. the student.ID wont be set by the API.

Best regards

**Comment by apobekiaris** [comment] 2020-08-17 18:45
what is the problem really? u started this post using the code for the old version of sequence generator  that does not exist in the current latest source. The way to go is with the https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator which is also installed if u use the eXpandSystem module.

later u posted a solution that I spent my resources in vain and frankly i  am still confused on that u are facing. Maybe a screencast would help me understand what u doing

**Comment by IFBDahmen** [comment] 2020-08-18 14:06
Hi,
I summarize my problem:
I have an API where I want to save a student. (In my example code: in the valuecontroller) [https://github.com/IFBDahmen/API/blob/master/WebApplication1/Controllers/ValuesController.cs](url)
The Gif shows how I create the SequenceStorage for the class student and a new student.
Then I start the API and post a new student.
This student created by API hasn't got an ID, the student created by App has got an ID.

![HowToProblem](https://user-images.githubusercontent.com/68540300/90522630-3cbda300-e16c-11ea-8180-41468cf2f221.gif)

Best regards

**Comment by IFBDahmen** [comment] 2020-08-27 13:54
Hello apobekiaris,
I need to know if you're working on this issue or if there are any other communication problems. :/

Best regards

**Comment by apobekiaris** [comment] 2020-08-28 05:51
Apologies my resources are limited and  the issue is already prioritized as per 

𝗛𝗼𝘄 𝘄𝗲 𝗽𝗿𝗶𝗼𝗿𝗶𝘁𝗶𝘇𝗲 𝗶𝘀𝘀𝘂𝗲𝘀
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels in order.

01. ❇️ Exclusive-Services
02. ❤ Bronze Sponsor
03. ❤ Sponsor
04. ❤ Backer
05. Installation
06. ShowStopper
07. Nuget
08. Contribution
09. BreakingChange
10. ReproSample
11. Deployment
12. Must-Have

For all other issues the posting time is respected.

at the moment there are many prioritized cases https://github.com/eXpandFramework/eXpand/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3APriority and the resolution will take a while.

If u resolve the case before me feel free to send a PR to avoid spending resources in vain. 

Thanks for the understanding and support

**Comment by apobekiaris** [comment] 2020-08-28 19:10
I am still unable to compile your solution 

![image](https://user-images.githubusercontent.com/159464/91604699-d01a8380-e977-11ea-8845-74c9c7eae102.png)

why there is such a mix of Xpand References and Xpand Nuget packages, this will make it impossible to compile in a different system than yours.

What I understand is that you try to init the module with the 

```cs
XafTypesInfo.Instance.RegisterEntity(typeof(Xpand.XAF.Modules.SequenceGenerator.SequenceGeneratorModule));
            XafTypesInfo.Instance.RegisterEntity(typeof(Solution3.Module.Solution3Module));
```

which pretty much do nothing the modules you registering in the TypesInfo system are modules and not entities and in addition there is no XafApplication that will leads to a per design initialization of the module.

The SequenceGenerator requires a XAF application where you will add the SequenceGenerator to its modules collection

**Comment by apobekiaris** [comment] 2020-08-28 19:17
and of courses you will call the Setup method of your WebApiXAFDummyAppWithTheSeqGeneratorInTheModules

**Comment by CWolffIF** [comment] 2020-09-01 11:41
Hi Tolis,

here is a new sample. We try to create a contact from within an organisation by default (if you save the organisation a contact is createtd). But this contact has no sequence number. It is in an XAFpplication (Win).

Maybe this helps.
![ContactfromOrga](https://user-images.githubusercontent.com/43132306/91845021-bcfa0300-ec58-11ea-944a-3c0c1ea28abe.gif)
[DEMO.zip](https://github.com/eXpandFramework/eXpand/files/5155912/DEMO.zip)

**Comment by apobekiaris** [comment] 2020-09-02 08:10
fyi @isatahiri

**Comment by expand** [comment] 2020-09-04 05:42
The pre-release [2.201.15.1](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.15.1) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Increase_Sequence_When_creating_Nested_New_Objects_on_parent_saving #737](https://github.com/eXpandFramework/DevExpress.XAF/commit/3ccea8aa8d5e423703c8f7c85322941865e74842)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.
<details>
    <summary>Released packages:</summary>
1. [Xpand.Extensions v.2.202.45](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions)
 1. [Xpand.Extensions.Mono.Cecil v.2.202.40](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil)
 1. [Xpand.Extensions.Office.Cloud v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud)
 1. [Xpand.Extensions.Reactive v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive)
 1. [Xpand.Extensions.XAF v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF)
 1. [Xpand.Extensions.XAF.Xpo v.2.202.42](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo)
 1. [Xpand.XAF.Core.All v.2.202.39.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Modules.AutoCommit v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)
 1. [Xpand.XAF.Modules.CloneMemberValue v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)
 1. [Xpand.XAF.Modules.CloneModelView v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)
 1. [Xpand.XAF.Modules.GridListEditor v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)
 1. [Xpand.XAF.Modules.HideToolBar v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)
 1. [Xpand.XAF.Modules.LookupCascade v.2.202.48.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)
 1. [Xpand.XAF.Modules.MasterDetail v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)
 1. [Xpand.XAF.Modules.ModelMapper v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)
 1. [Xpand.XAF.Modules.ModelViewInheritance v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance)
 1. [Xpand.XAF.Modules.Office.Cloud.Google v.2.202.7.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google)
 1. [Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.2.202.5.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft v.2.202.47.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.2.202.18.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.2.202.17.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo)
 1. [Xpand.XAF.Modules.OneView v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)
 1. [Xpand.XAF.Modules.PositionInListView v.2.202.17.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/PositionInListView)
 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)
 1. [Xpand.XAF.Modules.Reactive v.2.202.46.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)
 1. [Xpand.XAF.Modules.Reactive.Logger v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)
 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)
 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)
 1. [Xpand.XAF.Modules.Reactive.Win v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)
 1. [Xpand.XAF.Modules.RefreshView v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)
 1. [Xpand.XAF.Modules.SequenceGenerator v.2.202.46.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)
 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)
 1. [Xpand.XAF.Modules.ViewEditMode v.2.202.46.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)
 1. [Xpand.XAF.Modules.ViewItemValue v.2.202.12.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewItemValue)
 1. [Xpand.XAF.Modules.ViewWizard v.2.202.8.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewWizard)
 1. [Xpand.XAF.Web.All v.2.202.39.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Win.All v.2.202.39.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by CWolffIF** [comment] 2020-09-04 09:56
Hi Tolis,

I tested it with
Xpand.XAF.Modules.SequenceGenerator, Version=2.202.46.2

and it works in our DEMO-Project.

We now test it in the real project.

**Comment by expand** [comment] 2020-09-08 07:03
Issue is `deprioritized` as `no Assignee found` and scheduled for `auto-close` if no activity in the next `60 days`. Thanks a lot for your contribution.

**Comment by expand** [comment] 2020-09-11 15:42
The pre-release [2.201.15.4](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.15.4) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Increase_Sequence_When_creating_Nested_New_Objects_on_parent_saving #737 #764](https://github.com/eXpandFramework/DevExpress.XAF/commit/ea531630432e47d6ababd97fc096857a67b67fe3)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.
<details>
    <summary>Released packages:</summary>
1. [Xpand.Extensions v.2.202.47.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions)
 1. [Xpand.Extensions.Mono.Cecil v.2.202.42.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil)
 1. [Xpand.Extensions.Office.Cloud v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud)
 1. [Xpand.Extensions.Reactive v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive)
 1. [Xpand.Extensions.XAF v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF)
 1. [Xpand.Extensions.XAF.Xpo v.2.202.44.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo)
 1. [Xpand.XAF.Core.All v.2.202.39.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Modules.AutoCommit v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)
 1. [Xpand.XAF.Modules.CloneMemberValue v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)
 1. [Xpand.XAF.Modules.CloneModelView v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)
 1. [Xpand.XAF.Modules.GridListEditor v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)
 1. [Xpand.XAF.Modules.HideToolBar v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)
 1. [Xpand.XAF.Modules.LookupCascade v.2.202.50.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)
 1. [Xpand.XAF.Modules.MasterDetail v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)
 1. [Xpand.XAF.Modules.ModelMapper v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)
 1. [Xpand.XAF.Modules.ModelViewInheritance v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance)
 1. [Xpand.XAF.Modules.Office.Cloud.Google v.2.202.9.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google)
 1. [Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.2.202.6.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft v.2.202.49.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.2.202.20.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.2.202.19.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo)
 1. [Xpand.XAF.Modules.OneView v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)
 1. [Xpand.XAF.Modules.PositionInListView v.2.202.19.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/PositionInListView)
 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)
 1. [Xpand.XAF.Modules.Reactive v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)
 1. [Xpand.XAF.Modules.Reactive.Logger v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)
 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)
 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)
 1. [Xpand.XAF.Modules.Reactive.Win v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)
 1. [Xpand.XAF.Modules.RefreshView v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)
 1. [Xpand.XAF.Modules.SequenceGenerator v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)
 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)
 1. [Xpand.XAF.Modules.ViewEditMode v.2.202.48.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)
 1. [Xpand.XAF.Modules.ViewItemValue v.2.202.14.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewItemValue)
 1. [Xpand.XAF.Modules.ViewWizard v.2.202.10.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewWizard)
 1. [Xpand.XAF.Web.All v.2.202.39.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Win.All v.2.202.39.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment] 2022-05-06 21:02
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2022-05-06 21:02 UTC
Labels: Bug, SequenceGenerator, Reactive.XAF, ❤ Sponsor
