### ISSUE TITLE
Xpand.Extensions dependency not found with XAF lab v2.202.39.3 

### ISSUE THREAD

**Issue by rSeeFip** [eXpandFramework/eXpand#770] opened 2020-09-09 06:56 UTC
After installing XAF nugets v2.202.39.3 from lab the issue #752 is closed,
but now i can't open Model Editor or Designer of f.e. Module.

I got issue Xpand.Extension 2.202.45.0 is missed, sure because i have 2.202.46.1 from nuget

![image](https://user-images.githubusercontent.com/43534405/92564900-322d8f80-f27a-11ea-8efb-157dd19f1753.png)

**Comment by apobekiaris** [comment] 2020-09-09 06:59
#752 is not merged in main framework u need to rollback and repost if problems in the next eXpandFramework minor

**Comment by apobekiaris** [comment] 2020-09-09 07:03
or u can add binding redirects to this version in your machine.config, or XpandModelEditor has an option to do the same in the VSIX setting an enviromental variable to provide a custom app.config wher u can again set the binding redirect

**Comment by rSeeFip** [comment] 2020-09-09 07:04
i will try, thanks a lot

**Comment by dsikic** [comment] 2020-09-23 16:34
I had to set all of these to get the ME to load, and in the end it crashes on **Xpand.XAF.Modules.Reactive.ReactiveModule.Setup();**

VSIX appears to do nothing, as I also had to place an Xpand.Xpo.dll into **C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE**

`<runtime>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
				<assemblyIdentity name="Mono.Cecil" publicKeyToken="50cebf1cceb9d05e" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-0.10.1.0" newVersion="0.11.2.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Xpand.Extensions" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.45.0" newVersion="2.202.50.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Xpand.Extensions.Mono.Cecil" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.40.0" newVersion="2.202.45.0" />
			</dependentAssembly>	
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.ViewEditMode" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.46.0" newVersion="2.202.51.2" />
			</dependentAssembly>	
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.CloneModelView" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.46.0" newVersion="2.202.51.2" />
			</dependentAssembly>	
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.Reactive.Logger" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.46.0" newVersion="2.202.51.2" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.ModelViewInheritance" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.46.0" newVersion="2.202.51.2" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.CloneMemberValue" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.46.0" newVersion="2.202.51.2" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.HideToolBar" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.46.0" newVersion="2.202.51.2" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.ProgressBarViewItem" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.46.0" newVersion="2.202.51.2" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.RefreshView" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.46.0" newVersion="2.202.51.2" />
			</dependentAssembly>	
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.Reactive" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.46.0" newVersion="2.202.51.2" />
			</dependentAssembly>	
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.GridListEditor" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.46.0" newVersion="2.202.51.2" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.ModelMapper" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.46.0" newVersion="2.202.51.2" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.PositionInListview" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.17.0" newVersion="2.202.22.1" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.SequenceGenerator" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.46.0" newVersion="2.202.51.2" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Xpand.XAF.Modules.ViewItemValue" publicKeyToken="c52ffed5d5ff0958" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.202.12.0" newVersion="2.202.17.2" />
			</dependentAssembly>			
		</assemblyBinding>
	</runtime>`

**Comment by apobekiaris** [comment] 2020-09-23 16:44
posting a sample demostrating the issue that uses nuget will help tracing down the problem, like this i cannot say much more than analyzing your statement

>VSIX appears to do nothing

actually it copies the assemblies from bin to a specific folder on each build and logs the operation in the VS output window.

>as I also had to place an Xpand.Xpo.dll 

it might be the case in some old versions but such workaround will lead to futher problems in your system as you will probably forget it there and will cause other issues when you upgrade. I suggest you upgrade to the latest and provide detailed sample.

finally i guess that XpandModelEditor as an out of VS process exe should work fine

**Comment by apobekiaris** [comment] 2020-09-23 16:57
> but such workaround will lead to futher problems in your system as you will probably forget it there and will cause other issues when you upgrade

another related suggestion is to try open your solution on a clean machine so to verify that does not relate to your local system. HyperV VM are build in Windows and I use them constantly for similar cases

**Comment by dsikic** [comment] 2020-09-23 18:19
> posting a sample demostrating the issue that uses nuget will help tracing down the problem, like this i cannot say much more than analyzing your statement
> 
> > VSIX appears to do nothing
> 
> actually it copies the assemblies from bin to a specific folder on each build and logs the operation in the VS output window.
> 
> > as I also had to place an Xpand.Xpo.dll
> 
> it might be the case in some old versions but such workaround will lead to futher problems in your system as you will probably forget it there and will cause other issues when you upgrade. I suggest you upgrade to the latest and provide detailed sample.
> 
> finally i guess that XpandModelEditor as an out of VS process exe should work fine

I'm removing all unnecessary Xpand nuget packages and Mono packages that were added automatically, trying to stop any version mismatches that get created. 

Will delete that xpo.dll, also and try to start clean. Problem is that I haven't installed anything other than the xpand VSIX, and I've migrated all of my projects to the new VS2017+ project style which reference packages from nuget. During this process it added some extra packages that cause version mismatches.

Because expand isn't installed locally anymore, and there's nothing in GAC everything depends on packages resolving the right versions nicely and this is not happening for me at the moment.

If this housecleaning fails, I'll try the external model editor. Thanks as always!

**Comment by apobekiaris** [comment] 2020-09-23 18:24
yeah i admit and feel your pain we all learn in the process, my solution to this problem is to eliminate the unknowns in the equation  as so a simple test in a clean VM taking extra carefull not to install anything is very valuable. It establish a reproducible contract and if is reproducible it can be solved.

**Comment by dsikic** [comment] 2020-09-23 18:25
> yeah i admit and feel your pain we all learn in the process, my solution to this problem is to eliminate the unknowns in the equation as so a simple test in a clean VM taking extra carefull not to install anything is very valuable. It establish a reproducible contract and if is reproducible it can be solved.

Setting it up as we speak! :)

**Comment by dsikic** [comment] 2020-09-23 22:23
Hi @apobekiaris,

I spent a lot of time removing all XAF.Module packages from my projects which are included in Expand... projects which are v 701. This removed version mismatches. I then tried to open the model editor on a fresh Windows 10 machine and it didn't work. The DevExpress installed editor works fine on projects without Expand Modules, but not on any with Expand Modules. 

**Steps to reproduce:**

1. Downloaded this [Windows 10 Development Image](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) from Microsoft

2. Installed [.NET 4.8 Targeting Pack](https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-developer-pack-offline-installer). 

3. [Installed PowerShell 7.0.3 x64 ](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.3)

4. Executed` Install-Package Xpand.XAF.ModelEditor -Scope CurrentUser`

5. Tried to execute `"C:\Users\User\AppData\Local\PackageManagement\NuGet\Packages\Xpand.XAF.ModelEditor.1.201.6\build\Xpand.XAF.ModelEditor.exe"` it didn't work.

7. Installed DevExpress 2020.1.7 to get DevExpress Model Editor out of the box in Visual Studio. 

8. Tried to open Model.Xafml on Windows project. It failed asking for elevated permissions.
9. Run as Administrator and had another error, not sure exactly what it was.
10. Installed Latest v701 VSIX plugin [from here](https://github.com/eXpandFramework/eXpand/releases/download/20.1.701.0/Nupkg-20.1.701.0.zip) reloaded Visual Studio with Administrative rights.

11. Tried to open same Model.xafml by double clicking from visual studio (again using built in DX editor) ... missing Xpand.Xpo.dll in Community/common7/ide.

... What am I missing here? I can build you a sample solution. My DX2017 installation wasn't needed for my solution to compile. 

`\Xpand.ExpressApp.Modules\ViewVariants\XpandViewVariantsModule.cs:line 27
   at MyProject.Win.MyProjectWindowsFormsApplication.InitializeComponent() in C:\Users\User\source\repos\MyProjecttemp\MyProject.Win\WinApplication.Designer.cs:line 64
   at MyProject.Win.MyProjectWindowsFormsApplication..ctor() in C:\Users\User\source\repos\MyProjecttemp\MyProject.Win\WinApplication.cs:line 25
   at Create_MyProjectWindowsFormsApplication()
   at DevExpress.ExpressApp.Utils.Reflection.TypeData.CreateInstance(Object[] args)
----------InnerException----------
**Could not find file 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\Xpand.Xpo.dll'.**
----------StackTrace----------
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Xpand.Persistent.Base.General.XpandModuleBase.AssemblyResolver.Resolve(AssemblyNameReference name) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\XpandModuleBase.cs:line 623
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Xpand.Extensions.Mono.Cecil.MonoCecilExtensions.<BaseClasses>d__0.MoveNext() in D:\a\1\s\src\Extensions\Xpand.Extensions.Mono.Cecil\BaseClasses.cs:line 9
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Xpand.Extensions.Mono.Cecil.MonoCecilExtensions.IsSubclassOf(TypeDefinition childTypeDef, TypeDefinition parentTypeDef) in D:\a\1\s\src\Extensions\Xpand.Extensions.Mono.Cecil\IsSubclassOf.cs:line 6
   at Xpand.Persistent.Base.General.XpandModuleBase.<>c__DisplayClass99_0.<LoadAssemblyRegularTypes>b__1(TypeDefinition definition) in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\XpandModuleBase.cs:line 636
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Xpand.Persistent.Base.General.XpandModuleBase.LoadAssemblyRegularTypes() in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\XpandModuleBase.cs:line 637
   at Xpand.Persistent.Base.General.XpandModuleBase..cctor() in D:\a\1\s\Xpand\Xpand.Persistent\Xpand.Persistent.Base\General\XpandModuleBase.cs:line 112`

**Comment by apobekiaris** [comment] 2020-09-24 06:14
1. where is the sample solution? where u demonstrate the problem using the published packages and not random assemblies?
4. I do not offer support to solutions that use modified source code and not use the nuget packages unless it is a payed support. For free support u must use the packages as they are published. 
3. #762 had the same issue and reports that is now resolved after the fix i provided there.
2. You are confused of how the XpandModelEdititor works although there is a detailed wiki. https://github.com/eXpandFramework/DevExpress.XAF/tree/master/tools/Xpand.XAF.ModelEditor#vsix-integration. Again as the user reports in #762 the XpandModelEditor works for the same problem u having

**Comment by dsikic** [comment] 2020-09-24 18:27
Thank you for the 762 suggestions, when I upgraded to 703.1 from xpandnuget server prior to you publishing 703.0 officially. This change, plus a machine.config binding redirect (for mono.cecil) solved most of the prior issues. I also just updated VSIX to the 703 you published.

This got me a lot further and I had to clean up and rebuild my WinApplication.designer file. Had strange issues with audit trail then removed that entirely from the solution and now I'm stuck on a DX error when loading the model.

I also tried your Xpand.XAF.ModelEditor package directly into my Windows project but it wouldn't build due to PowerShell errors. Something about paket. 

All in all I think this DX error is related to me using the new CSPROJ package format and it doesn't know how to deal with it. I might need to pay for some support here because I need to merge some of these models upward and it's urgent. 

All DX & Xpand references are from NuGet.org officially or from Xpand's Nuget server. I'm not using anything compiled locally or modified in any way. 

```
   at DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.GetComponentFromDesigner[ComponentType](ProjectItem projectItem, ITypesInfo typesInfo)
   at DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.GetXafApplicationByDesigner(Project project)
   at DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   at DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   at DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
```

**Comment by apobekiaris** [comment] 2020-09-24 18:55
>I also tried your Xpand.XAF.ModelEditor package directly into my Windows project but it wouldn't build due to PowerShell errors. Something about paket

If you use the eXpand* assemblies VSIX is a requirement due to ModelMapper dependencies for supporting the XAF modeleditor. To this end the VSIX copies all assemlbies from the bin to devEnvInstallationFolder\CommonExtensions\DataDesign and this helps XAF model editor to locate the assemblies.

The XpandModelEditor wiki I posted before does not mention that u have to install the XpandModelEditor package instead it says that the VSIX has the XpandModelEditor embeded. So remove that package cause is of no use to you.

Read the wiki link I posted before carefully please

https://user-images.githubusercontent.com/159464/75141828-769c7800-56fa-11ea-9498-49374bb96fae.png

the stack traces you posted are missing context that relates to Xpand operations so I cannot suggest anything.

**Comment by dsikic** [comment] 2020-09-24 20:14
Hi @apobekiaris,

In [this documentation](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/tools/Xpand.XAF.ModelEditor#vsix-integration) please consider removing the Installation section from the top, or adding a note next to it that says something like _"See VSIX section below for use, as this component is bundled with Xpand.VSIX visual studio plugin."_ . 

I had re-read it a bunch of times but always started with the Installation as a first step. On both my development machines XAF Model List doesn't load. On machine 1 it is a white box that doesn't initiate a build process. On machine 2 it is a transparent box which opens Output window, switches to Xpand output source and prints that three projects (VSTO projects) are invalid. All three are actually not loaded in the solution. 

Can I please connect with you on Skype, Teams or TeamViewer and you invoice me for it? I'll wake up early tomorrow to accommodate your time zone and schedule.

**Comment by apobekiaris** [comment] 2020-09-24 20:19
transparency is a VS issue u can resolve it by by unchecking the VS/Options/Enviroment/Optimize Rendering

>Can I please connect with you on Skype, Teams or TeamViewer and you invoice me for it? I'll wake up early tomorrow to accommodate your time zone and schedule.

if you require private support hours fell free to contact me by email it is available in my profile https://github.com/apobekiaris

**Comment by dsikic** [comment] 2020-09-24 20:31
Optimize Rendering helped a lot! THANK YOU! 

Modules list loads now and quite a few open up, but some crash with the following in Event Viewer. It's nice that it shows the command it's executing so I can try to debug it. 

I'll shoot you an email in an hour or so if I'm still stuck, to set up something for tomorrow / weekend.

`Application: Xpand.XAF.ModelEditor637365614812685150.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.InvalidCastException at DevExpress.XtraRichEdit.Layout.TablesControllerTableState.LeaveCurrentTable(Boolean, Boolean) at DevExpress.XtraRichEdit.Layout.TablesController.LeaveCurrentTableCore() at DevExpress.XtraRichEdit.Layout.TablesController.LeaveCurrentTable(DevExpress.XtraRichEdit.Model.TableCell) at DevExpress.XtraRichEdit.Layout.Engine.RowsController.BeginParagraph(DevExpress.XtraRichEdit.Model.Paragraph, DevExpress.XtraRichEdit.Layout.Engine.LineFormatterBeginParagraphFlags) at DevExpress.XtraRichEdit.Layout.Engine.LineFormatter.BeginParagraph(DevExpress.XtraRichEdit.Layout.Engine.LineFormatterBeginParagraphFlags) at DevExpress.XtraRichEdit.Layout.Engine.LineFormatter.BeginParagraphFormatting(DevExpress.XtraRichEdit.Layout.Engine.ParagraphBoxIterator, DevExpress.XtraRichEdit.Layout.Engine.LineFormatterBeginParagraphFlags) at DevExpress.XtraRichEdit.Layout.Engine.BeginParagraphFormatting.FormatParagraph() at DevExpress.XtraRichEdit.Layout.Engine.ParagraphFormatter.FormatParagraphCore() at DevExpress.XtraRichEdit.Layout.Engine.ParagraphFormatter.FormatParagraph() at DevExpress.XtraRichEdit.Layout.Engine.BackgroundFormatter.PerformPrimaryLayoutCore() at DevExpress.XtraRichEdit.Layout.Engine.BackgroundFormatter.WaitForPrimaryLayoutReachesLogPosition(DevExpress.XtraRichEdit.Model.DocumentLogPosition) at DevExpress.XtraRichEdit.RichEditView.EnsureFormattingCompleteForLogPosition(DevExpress.XtraRichEdit.Model.DocumentLogPosition) at DevExpress.XtraRichEdit.Layout.DocumentLayoutPosition.UpdateCore(DevExpress.XtraRichEdit.Layout.PageCollection, DevExpress.XtraRichEdit.Layout.DocumentLayoutDetailsLevel) at DevExpress.XtraRichEdit.Layout.DocumentLayoutPosition.Update(DevExpress.XtraRichEdit.Layout.PageCollection, DevExpress.XtraRichEdit.Layout.DocumentLayoutDetailsLevel, Boolean) at DevExpress.XtraRichEdit.Layout.CaretPosition.Update(DevExpress.XtraRichEdit.Layout.DocumentLayoutDetailsLevel) at DevExpress.XtraRichEdit.Ruler.HorizontalRulerControl.CanUpdate() at DevExpress.XtraRichEdit.RichEditControl.UpdateRulers() at DevExpress.XtraRichEdit.Internal.InnerRichEditControl.PerformRaiseDeferredEventsCore(DevExpress.XtraRichEdit.Model.DocumentModelChangeActions) at DevExpress.XtraRichEdit.Internal.InnerRichEditDocumentServer.RaiseDeferredEventsCore(DevExpress.XtraRichEdit.Model.DocumentModelChangeActions) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() at System.Threading.ThreadPoolWorkQueue.Dispatch() `

**Comment by expand** [comment] 2020-09-26 23:10
The pre-release [2.201.17.1](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.17.1) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [XpandModelEditor wiki is confusing #770](https://github.com/eXpandFramework/DevExpress.XAF/commit/64457dd357a950e655c823b2df375cadb132a4af)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all.
<details>
    <summary>Released packages:</summary>
1. [Xpand.Extensions v.2.202.54.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions)
 1. [Xpand.Extensions.Mono.Cecil v.2.202.49](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil)
 1. [Xpand.Extensions.Office.Cloud v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud)
 1. [Xpand.Extensions.Reactive v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive)
 1. [Xpand.Extensions.XAF v.2.202.55.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF)
 1. [Xpand.Extensions.XAF.Xpo v.2.202.51](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo)
 1. [Xpand.XAF.Core.All v.2.202.41.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Modules.AutoCommit v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)
 1. [Xpand.XAF.Modules.CloneMemberValue v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)
 1. [Xpand.XAF.Modules.CloneModelView v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)
 1. [Xpand.XAF.Modules.GridListEditor v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)
 1. [Xpand.XAF.Modules.HideToolBar v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)
 1. [Xpand.XAF.Modules.LookupCascade v.2.202.57.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/LookupCascade)
 1. [Xpand.XAF.Modules.MasterDetail v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)
 1. [Xpand.XAF.Modules.ModelMapper v.2.202.55.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)
 1. [Xpand.XAF.Modules.ModelViewInheritance v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance)
 1. [Xpand.XAF.Modules.Office.Cloud.Google v.2.202.16.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google)
 1. [Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.2.202.6.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar)
 1. [Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.2.202.13.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft v.2.202.56.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.2.202.27.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar)
 1. [Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.2.202.26.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo)
 1. [Xpand.XAF.Modules.Office.DocumentStyleManager v.2.202.0](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Office.DocumentStyleManager)
 1. [Xpand.XAF.Modules.OneView v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)
 1. [Xpand.XAF.Modules.PositionInListView v.2.202.26.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/PositionInListView)
 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)
 1. [Xpand.XAF.Modules.Reactive v.2.202.55.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)
 1. [Xpand.XAF.Modules.Reactive.Logger v.2.202.55.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)
 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)
 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)
 1. [Xpand.XAF.Modules.Reactive.Win v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)
 1. [Xpand.XAF.Modules.RefreshView v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)
 1. [Xpand.XAF.Modules.SequenceGenerator v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SequenceGenerator)
 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)
 1. [Xpand.XAF.Modules.ViewEditMode v.2.202.55.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)
 1. [Xpand.XAF.Modules.ViewItemValue v.2.202.21.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewItemValue)
 1. [Xpand.XAF.Modules.ViewWizard v.2.202.17.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewWizard)
 1. [Xpand.XAF.Web.All v.2.202.41.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Win.All v.2.202.41.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)

</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment] 2022-05-09 21:02
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2022-05-09 21:02 UTC
Labels: Bug, XpandModelEditor, Design-time, VSIX
