### ISSUE TITLE
CloneMemberValue as standalone nuget package

### ISSUE THREAD

**Issue by isatahiri** [eXpandFramework/eXpand#345] opened 2019-03-13 16:01 UTC
**Describe the bug**
It seems that the clone value does not work in inline edit and via the detailview. 

**To Reproduce**
Set the clone value to true : 
![image](https://user-images.githubusercontent.com/41955268/54294100-53dc8680-45b1-11e9-8bba-32cf872dd412.png)

**Expected behavior**
When i set the clone value to True, I expect that on new record it takes the previous value and set it. 
Here we do not want to use the aftercontruction method, because we want to take the last inserted value. 

BR
ISA

**Comment by apobekiaris** [comment] 2019-03-20 18:04
>via the detailview

Please describe repro steps.

**Comment by apobekiaris** [comment] 2019-03-22 14:00
true the thats a variation of [XAF_how-to-copy-last-entered-values-into-a-newly-created-object-when-using-the-save-and-new-e2484](https://github.com/DevExpress-Examples/XAF_how-to-copy-last-entered-values-into-a-newly-created-object-when-using-the-save-and-new-e2484).

I am working on a new package for this, stay tuned

**Comment by apobekiaris** [comment] 2019-03-26 12:56
[Xpand.XAF.Modules.CloneMemberValue](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab/src/Modules/Agnostic/CloneMemberValue) module can be used to address this case. 

The existing functionality (in eXpandFramework) since it is not used from any modules it will be removed in the next minor. 

Looking forward for your feedback, note this is a nightly package and available only from https://xpandnugetserver.azurewebsites.net/nuget at the moment.

**Comment by expand** [comment] 2019-03-27 06:23
eXpand.lab Installer [18.2.703.2](https://github.com/eXpandFramework/lab/releases/18.2.703.2) includes commit [Removes CloneMemberValueViewController, use Xpand.XAF.Modules.CloneMemberValue package #345](https://github.com/eXpandFramework/153812905/commit/33c8272f82f99f7c4fa0ea28f031fc1bff179570) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

. Thanks a lot for your contribution.

**Comment by expand** [comment] 2019-03-29 15:04
The DevExpress.XAF includes commit [CloneMemberValueModule release #345](https://github.com/eXpandFramework/161949491/commit/c645f5199234bfa3fce48eebc308c13ef2d87696) that relate to this task. Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/).

**Comment by brond3** [comment] 2019-03-30 01:26
I noticed a slight mistake on your installation instructions. 
You have **RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.CloneMemberValueModule));**
I think you mean to have 
**RequiredModuleTypes.Add(typeof(Xpand.XAF.Modules.CloneMemberValue.CloneMemberValueModule));**

**Comment by apobekiaris** [comment] 2019-03-30 01:50
thnks

**Comment by brond3** [comment] 2019-03-30 02:21
Another thing I noticed is that as soon as I put the cloneMembervalueModule in the WinModule.Designer.cs file the application raises an error. 

**System.IO.FileNotFoundException: 'Could not load file or assembly 'DevExpress.ExpressApp.v17.2, Version=17.2.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a' or one of its dependencies. The system cannot find the file specified.'**

If I comment the line the problem gets resolved.  I do not have 17.2.7.0 installed.   Could Xpand.XAF.Modules.CloneMemberValue.dll be dependent on a Devexpress dll from V17 ?

I am not a pro at this so I might be missing the obvious.

**Comment by apobekiaris** [comment] 2019-03-30 02:24
whats your dx version?

**Comment by brond3** [comment] 2019-03-30 02:30
Devexpress 18.2.7.0

**Comment by apobekiaris** [comment] 2019-03-30 02:33
what is in your VS output windows for the Build log when you first build a project where you installed the module.

you should have a bit more thatn these entries describing the checks and in your case the patch 

```
1>------ Build started: Project: Solution56.Module, Configuration: Debug Any CPU ------
1>  Solution56.Module -> C:\Users\Tolis\source\repos\Solution56\Solution56.Module\bin\Debug\Solution56.Module.dll
1>  Loading Mono.Cecil
1>  Checking C:\Users\Tolis\source\repos\Solution56\Solution56.Module\bin\Debug\Xpand.XAF.Modules.CloneMemberValue.dll references..
1>  Checking C:\Users\Tolis\source\repos\Solution56\packages\Xpand.XAF.Modules.CloneMemberValue.1.0.1.1\lib\net4.6.1\Xpand.XAF.Modules.CloneMemberValue.dll references..
1>  Checking C:\Users\Tolis\source\repos\Solution56\Solution56.Module\bin\Debug\Xpand.XAF.Modules.Reactive.dll references..
1>  Checking C:\Users\Tolis\source\repos\Solution56\packages\Xpand.XAF.Modules.Reactive.1.0.10.1\lib\net4.6.1\Xpand.XAF.Modules.Reactive.dll references..
```

**Comment by apobekiaris** [comment] 2019-03-30 02:39
>17.2.7.0

oops now I seen this,no the module was build with the current version so no way u get such a message. I can debug a sample if you have. 

Note the module uses the [VersionConverter](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/tools/Xpand.VersionConverter) package, to auto patch it selft on each build. The same Technic is used from the `ModelViewInheritance` module which is distributed with eXpandFramework that was build on 18.2.7 where the module was on 18.2.6 and I had no reports.

**Comment by brond3** [comment] 2019-03-30 02:42
Ok.  I will keep looking at it.   If I cant get it working In the next few hours I will create a sample.

**Comment by brond3** [comment] 2019-03-30 02:43
should specific version be set to True or False on the CloneMemberValue ?

**Comment by apobekiaris** [comment] 2019-03-30 02:46
i just testsed the default installation from the nuget on a 18.2.7 empty solution and worked as described.

Does it work with an empty XAF solution?

>should specific version be set to True or False on the CloneMemberValue ?

the assembly pacthed is the one in the `Packages` folder so that attribute should not have any effect to this module.

**Comment by apobekiaris** [comment] 2019-03-30 03:11
yes you are right sorry about this I can repro the case, I ll update you once fixed

**Comment by apobekiaris** [comment] 2019-03-30 06:30
Hmm I was wrong, I tried many times to repro it but do not see how.

This what I am doing:
1. On a clean VM installed XAF 18.2.6, CloneMemberValue is compiled against 18.2.7 so I am on a past version.
1. Create a new XAF empty project
2. Open VS Nuget Package manager and issue
```ps1
Update-ProjectTargetFramework #This method exist in XpandPosh you can also go manual and will update all projects to 4.6.1
 ```
after updating to 4.6.1 do 
```ps1
Install-Package Xpand.XAF.Modules.CloneMemberValue
```

and then build and see in the output info about the patching done

```
1>------ Rebuild All started: Project: Solution6.Module, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "DevExpress.ExpressApp.v18.2" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>  Solution6.Module -> C:\Users\Tolis\source\repos\Solution6\Solution6.Module\bin\Debug\Solution6.Module.dll
1>  Loading Mono.Cecil
1>  Checking C:\Users\Tolis\source\repos\Solution6\Solution6.Module\bin\Debug\Xpand.XAF.Modules.CloneMemberValue.dll references..
1>  True
1>  DevExpress.ExpressApp.v18.2 version changed from 18.2.7.0 to 18.2.6.0
1>  Checking C:\Users\Tolis\source\repos\Solution6\packages\Xpand.XAF.Modules.CloneMemberValue.1.0.1\lib\net4.6.1\Xpand.XAF.Modules.CloneMemberValue.dll references..
1>  True
1>  DevExpress.ExpressApp.v18.2 version changed from 18.2.7.0 to 18.2.6.0
1>  Checking C:\Users\Tolis\source\repos\Solution6\Solution6.Module\bin\Debug\Xpand.XAF.Modules.Reactive.dll references..
1>  True
1>  DevExpress.ExpressApp.v18.2 version changed from 18.2.7.0 to 18.2.6.0
1>  Checking C:\Users\Tolis\source\repos\Solution6\packages\Xpand.XAF.Modules.Reactive.1.0.10\lib\net4.6.1\Xpand.XAF.Modules.Reactive.dll references..
1>  True
1>  DevExpress.ExpressApp.v18.2 version changed from 18.2.7.0 to 18.2.6.0
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

and you can run the CloneMemberValue with the past version

**Comment by apobekiaris** [comment] 2019-03-30 06:33
can you follow the same steps (u can skip the clean vm part if u like :)) and let me know if it works, or can you provide exact details on what u do and is failing?

**Comment by apobekiaris** [comment] 2019-03-30 06:55
>System.IO.FileNotFoundException: 'Could not load file or assembly 'DevExpress.ExpressApp.v17.2, Version=17.2.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a' or one of its dependencies. The system cannot find the file specified.'

a few more notes on this: This a FileNotFoundException and you may be able to get the caller and the reason using `fuslogvw` in a VS developer command prompt (run it as Admin)

**Comment by brond3** [comment] 2019-03-30 08:15
After creating a new project I noticed that the cause of the issue was with 
**<Import Project="..\packages\Xpand.VersionConverter.1.0.4\build\Xpand.VersionConverter.targets" Condition="Exists('..\packages\Xpand.VersionConverter.1.0.4\build\Xpand.VersionConverter.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Xpand.VersionConverter.1.0.4\build\Xpand.VersionConverter.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Xpand.VersionConverter.1.0.4\build\Xpand.VersionConverter.targets'))" />
  </Target>**

It was inserted in both the Module.Win and the Win module.  This was causing some of the errors.  After cleaning up my real project things started to work well.    

After that I decided to test the clone value and found an error.  I created a very simple project to show you the error that it generates.    To duplicate the error.  Create a new terms code.  Click save to get back to listview, and close the application.  Start application once more,  click on terms record that you previously created and once in detail view click on SaveAndNew.  Once you do it will generate the following error.  **Unable to cast object of type 'Solution8Clone.Module.BusinessObjects.TermsBO' to type 'DevExpress.ExpressApp.IObjectSpaceLink'.**

Note that this will happen only once.  If you go back to terms listview and repeat the process the error will be gone.  This only happens when you open the record after you have started the application. 

[Solution8Clone.zip](https://github.com/eXpandFramework/eXpand/files/3025265/Solution8Clone.zip)

**Comment by brond3** [comment] 2019-03-30 08:25
Trying a second time .  It was the code  
Import Project="..\packages\Xpand.VersionConverter.1.0.4\build\Xpand.VersionConverter.targets" Condition="Exists('..\packages\Xpand.VersionConverter.1.0.4\build\Xpand.VersionConverter.targets')" 
That showed up in multiple area._

**Comment by apobekiaris** [comment] 2019-03-30 08:55
so you manage to run it, that's good, my guess is that this was one time problem? or you know how this duplication occurred?

**Comment by expand** [comment] 2019-06-05 03:05
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2019-06-05 03:05 UTC
Labels: CloneMemberValue, Enhancement, Standalone_XAF_Modules, System
