### ISSUE TITLE
HttpUnhandledException

### ISSUE THREAD

**Issue by JakeLogan2019** [eXpandFramework/eXpand#534] opened 2019-09-12 03:03 UTC
World Creator throws this exception when I try to create Base Class Info/Merged Class Info new entry in the Persistent Class Info screen in General Tab.

The error occurred:

	Type:       HttpUnhandledException
	Message:    Exception of type 'System.Web.HttpUnhandledException' was thrown.
	Data:       1 entries
			'ASPIMPERSONATING'		''
	Stack trace:

   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.default_aspx.ProcessRequest(HttpContext context) in c:\Users\Vaas\AppData\Local\Temp\Temporary ASP.NET Files\vs\54e5db1e\48e4861d\App_Web_gon4xl1e.0.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
	----------------
	InnerException:

			Type:       NullReferenceException
			Message:    Object reference not set to an instance of an object.
			Data:       0 entries
			Stack trace:

   at Xpand.ExpressApp.WorldCreator.System.WCExtensions.Init(IPersistentTemplatedTypeInfo persistentTemplatedTypeInfo, Type codeTemplateType) in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\WorldCreator\System\WCExtensions.cs:line 59
   at Xpand.ExpressApp.WorldCreator.Controllers.InitializeTemplatedTypeInfoController.OnViewControlsCreated() in D:\a\1\s\Xpand\Xpand.ExpressApp.Modules\WorldCreator\Controllers\InitializeTemplatedTypeInfoController.cs:line 13
   at DevExpress.ExpressApp.ViewController.view_ControlsCreated(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at DevExpress.ExpressApp.View.OnControlsCreated()
   at DevExpress.ExpressApp.View.CreateControls()
   at DevExpress.ExpressApp.Web.Controls.ViewSiteControl.SetView(View view)
   at DevExpress.ExpressApp.Web.Templates.BaseXafPage.SetView(View view)
   at DevExpress.ExpressApp.Frame.SetTemplateView(View view)
   at DevExpress.ExpressApp.Frame.SetTemplate(IFrameTemplate val)
   at DevExpress.ExpressApp.Web.WebWindow.CreateControls(Page page, Boolean checkRequestParams)
   at DevExpress.ExpressApp.Web.WebApplication.CreateControlsCore(Page page)
   at DevExpress.ExpressApp.Web.WebApplication.CreateControls(Page page)
   at DevExpress.ExpressApp.Web.Templates.BaseXafPage.CreateControls()
   at DevExpress.ExpressApp.Web.Templates.BaseXafPage.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
			InnerException is null

**Comment by apobekiaris** [comment] 2019-09-12 03:08
a sample will help resolving the issue

**Comment by JakeLogan2019** [comment] 2019-09-12 03:18
Gave sample project in #535 called Solution1.zip contains sample project.

**Comment by apobekiaris** [comment] 2019-09-24 21:56
I cannot reproduce this case, however it does not look direct related to the WorldCreator module. I suggest you try the solutions suggested from google

https://www.google.com/search?q=Loading+this+assembly+would+produce+a+different+grant+set+from+other+instances.&rlz=1C1CHBF_enGR824GR824&oq=Loading+this+assembly+would+produce+a+different+grant+set+from+other+instances.&aqs=chrome..69i57j0l4j69i60.2215j0j7&sourceid=chrome&ie=UTF-8

**Comment by expand** [comment] 2019-09-24 22:07
eXpand.lab release [19.1.602.6](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.602.6) includes commit that relate to this task:

* [WorldCreator: PersistentClassInfo base should be selected only from preexisting classinfo #534](https://github.com/eXpandFramework/eXpand.lab/commit/c28d3f7bc8a46f4fd67d4838818558da638f46ae)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment] 2019-11-24 03:01
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2019-11-24 03:01 UTC
Labels: Bug, WorldCreator
