### ISSUE TITLE
XAF Model Editor is not opening when I have installed any eXpand module

### ISSUE THREAD

**Issue by q-soft** [eXpandFramework/eXpand#724] opened 2020-07-05 13:15 UTC
I am trying to utilized some module of eXpand into my application but when i am installing any module via NuGet  package Xaf model editor is not opening it showing this error
**One or more errors were encountered while loading the designer. The errors are listed below. Fixing some of the errors may require code or model changes.**
**Unable to create an instance of the "Xpand.ExpressApp.ImportWizard.ImportWizardModule" type.
Reason: "The type initializer for 'Xpand.Persistent.Base.General.XpandModuleBase' threw an exception."**
Please note I am using Visual Studio 2019 with latest updates and DevExpress version 20.1.4.0 and eXpand version 20.1.04.0

**Comment by apobekiaris** [comment] 2020-07-05 13:42
does the XpandModelEditor works? what are the modules u try to use? Please install them in an empty XAF solution and post it here

**Comment by q-soft** [comment] 2020-07-05 16:29
Thanks for your reply
XpandModelEditor is also not working, actually I am trying to use excel ImportWizard, WizardUI & Email Module etc... but in anyways even not working a single module same issue for all the installed modules, I have made much efforts to get it functional almost spending 20 days to get it working but failed
Please click [here](https://www.dropbox.com/s/fwqxd735fvmku18/solution3.rar?dl=0) to find my sample Dropbox solution

**Comment by q-soft** [comment] 2020-07-06 14:53
Hi apobekiaris
You have found that error?

**Comment by expand** [comment] 2020-07-06 15:20
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by apobekiaris** [comment] 2020-07-06 15:20
Hi

is going to take some time as I have other issues prioritized for this week

**Comment by q-soft** [comment] 2020-07-06 16:13
thank you I need eXpand some module to implement into my project, you can take your time and I am looking forward to you

**Comment by apobekiaris** [comment] 2020-07-10 14:59
the attachment is missing

**Comment by q-soft** [comment] 2020-07-10 22:02
Sorry for link broken
I am share new link [here](https://www.dropbox.com/s/2ejfhwpicpfnjod/expandmodeleditorissue.rar?dl=0) please check it

**Comment by apobekiaris** [comment] 2020-07-11 11:57
did u tried on a different machine? at least in mine works fine, also u should be able to debug it by setting the Tools/Options/XPand/Model Editor Debug to true. Then you open the XpandModelEditor and a MsgBox will popup leaving u the chance to attach to the XpandModelEditor.exe processs and having Break on Errors it should stop to the exception location where u can examine whats happening in the debugger,

Probably is some version confict in your system, I receommend to use only the container Nuget packages to avoid version conflicts. In addition it may also relate to a case like #726

**Comment by apobekiaris** [comment] 2020-07-12 12:17
I can reproduce and found that Xamarin extensions loads the Mono.Cecil in the AppDomain and once loaded there is not way to unload at least I did not find one. However Xpand.ModelEditor is a standalone outside of VS process and works fine. Consider using it instead or try to get a possible solution to this problem in the Xamarin support.

**Comment by q-soft** [comment] 2020-07-13 08:23
I have put every efforts to work it but failed. Actually I need some module to utilize into my application like ImportWizard, Email, WorldCreation etc... but not work a single module at my side

**Comment by apobekiaris** [comment] 2020-07-13 08:26
>I have put every efforts to work i

describe what u did and what failed cause I did: XpandModelEditor worked fine for me,

**Comment by expand** [comment] 2020-07-16 21:04
Issue is `deprioritized` as `no Assignee found` and scheduled for `auto-close` if no activity in the next `60 days`. Thanks a lot for your contribution.

**Comment by q-soft** [comment] 2020-07-17 11:43
I have also removed MOno.Cecil dll from project and even though it's not working at my side. also I don't find XpandModel Editor would you please guide me how can I use alternatively it

**Comment by Vbacna** [comment] 2020-07-17 12:40
The eXpand Model Editor is starting from VS menu: Extensions / Xpand / XAF Models list.

I think removing Mono.Cecil from project will not help, because the designer works in context of Visual Studio (devenv.exe), not your project

**Comment by apobekiaris** [comment] 2020-07-17 13:38
>The workaround was to modify machine.config and make a bindingRedirect to version 0.11.2 

this one of the least public solution I did not tried, thnks for sharing

**Comment by apobekiaris** [comment] 2020-08-31 07:10
could someone post the exact machine.config redirect for reference please

**Comment by apobekiaris** [comment] 2020-08-31 08:26
```xml
<runtime>
	<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
	  <dependentAssembly>
		<assemblyIdentity name="Mono.Cecil" publicKeyToken="50cebf1cceb9d05e" culture="neutral" />
		<bindingRedirect oldVersion="0.0.0.0-0.10.1.0" newVersion="0.11.2.0" />
	  </dependentAssembly>
  </assemblyBinding>
</runtime>
```

**Comment by expand** [comment] 2020-10-30 23:28
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2020-10-30 23:28 UTC
Labels: Design-time, EmailModule, ImportWizard, ReproSample
