### ISSUE TITLE
Duplicate item is shown in enum editor

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#523] opened 2019-08-26 18:51 UTC
This Enum produces the following wrong behavior
Public Enum NoFilterEnum
        <ImageName("BO_Task")> Option1
        Option2
    End Enum

![2019-08-26_15-50-15](https://user-images.githubusercontent.com/226800/63715032-59edb900-c819-11e9-86ba-1d33d0fa6beb.gif)

Public Enum NoFilterEnum
        <ImageName("BO_Task")> Option1
        Option2
    End Enum

**Comment by apobekiaris** [comment] 2019-08-26 18:56
please provide a sample to avoid losing time in vain

**Comment by apobekiaris** [comment] 2019-09-23 01:03
i cannot reproduce the case with the latest lab version and your sample, please check again and let me know

**Comment by expand** [comment] 2019-11-22 03:01
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2019-11-22 03:01 UTC
Labels: Bug, System.Win
