### ISSUE TITLE
ambiguous machtes issue by open complex DashboardView

### ISSUE THREAD

**Issue by rSeeFip** [eXpandFramework/eXpand#654] opened 2020-01-07 10:34 UTC
One Month ago i got the ambiguous matches issue by opening login Window, with Release
19.2.301.9.

You fixed it by change on ModelMapper by
at PredefinedMapServices GetViewControl on
with :

```cs
if (new[]{PredefinedMap.XafLayoutControl,PredefinedMap.SplitContainerControl}.Any(map => map==predefinedMap)){
var value = view.GetPropertyValue(nameof(CompositeView.LayoutManager));
return value.GetType().Properties(nameof(LayoutManager.Container)).First().GetValue(value);
}
```

Now, with actual release i got this error by opening an Dashboard View, which includes 
2 Chart Views, 1 GridView and 1 ListView.

it occurs again by Modelmapperservice BindData like last time.

The actual stacktrace is

```
Mehrdeutige Übereinstimmung gefunden.

   bei System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   bei System.Type.GetProperty(String name, BindingFlags bindingAttr)
   bei Fasterflect.PropertyExtensions.Property(Type type, String name, Flags bindingFlags)
   bei Fasterflect.Emitter.LookupUtils.GetMember(CallInfo callInfo)
   bei Fasterflect.Emitter.MemberGetEmitter.CreateDelegate()
   bei Fasterflect.Emitter.BaseEmitter.GetDelegate()
   bei Fasterflect.PropertyExtensions.DelegateForGetPropertyValue(Type type, String name, Flags bindingFlags)
   bei Fasterflect.PropertyExtensions.GetPropertyValue(Object obj, String name, Flags bindingFlags)
   bei Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.BindData(ValueTuple`3 data, Object control)
   bei Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.<>c.<ViewModelProperties>b__9_1(ValueTuple`3 _)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   bei System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
   bei System.Reactive.ObserverBase`1.OnError(Exception error)
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   bei System.Reactive.Sink`2.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error)
   bei System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
   bei System.Reactive.ObserverBase`1.OnError(Exception error)
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Sink`1.ForwardOnError(Exception error)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.IdentitySink`1.OnNext(T value)
   bei System.Reactive.Subjects.Subject`1.OnNext(T value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.IdentitySink`1.OnNext(T value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value)
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value)
   bei System.Reactive.Subjects.Subject`1.OnNext(T value)
   bei System.EventHandler.Invoke(Object sender, EventArgs e)
   bei DevExpress.ExpressApp.View.OnControlsCreated()
   bei Xpand.ExpressApp.XpandListView.OnControlsCreated()
   bei DevExpress.ExpressApp.View.CreateControls()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.EnsureViewControl()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.FillViewSite()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.viewSiteControl_HandleCreated(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   bei DevExpress.XtraEditors.XtraScrollableControl.OnHandleCreated(EventArgs e)
   bei DevExpress.XtraEditors.PanelControl.OnHandleCreated(EventArgs e)
   bei System.Windows.Forms.Control.WmCreate(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei DevExpress.XtraEditors.XtraScrollableControl.WndProc(Message& m)
   bei DevExpress.Utils.Controls.PanelBase.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by apobekiaris** [comment] 2020-01-07 10:47
can you first try to make sure which control is the one that fails (most probably is the chart) by removing  the other parts from the dashboard and testing again.

**Comment by rSeeFip** [comment] 2020-01-07 11:31
it occurs by chart and pivotgrid

**Comment by apobekiaris** [comment] 2020-01-07 11:33
ok i will try patch it for all, wait for an update

**Comment by apobekiaris** [comment] 2020-01-08 06:47
at the moment there is a fail build however u may test the attached assemblies by adding them to your 
C:\Users\Tolis\.nuget\packages\xpand.xaf.modules.modelmapper\YOURLATESTVERSION\lib\net461\ whereas first u run 

```ps1
Remove-VersionConverterFlags
```
[bin.zip](https://github.com/eXpandFramework/eXpand/files/4033900/bin.zip)

let me know if the problem is resolved and please not that these assemblies are not tested as the build fails

**Comment by rSeeFip** [comment] 2020-01-08 07:46
are you sure the file is right, the filedate is 20.12.19

after following your instructions nothing changed, so i copy the file to gac and then i get
![image](https://user-images.githubusercontent.com/43534405/71959494-296c5180-31f3-11ea-9a5e-9d770f9de960.png)

**Comment by apobekiaris** [comment] 2020-01-08 07:57
hmmm unfortunately this fast workaround I attempted won't work they versioned different. If you are in a hurry your only option at the moment is to compile the lab branch else u have to wait for the build to pass.

**Comment by rSeeFip** [comment] 2020-01-09 08:11
yes i need it but when i try to build lab Modules i have same issue like by build master Modules #653

**Comment by apobekiaris** [comment] 2020-01-09 08:12
You did not reply back to my last comment so I assume you manage it. Please let me know why the build fails while respecting my last comment

**Comment by apobekiaris** [comment] 2020-01-09 08:13
use #653

**Comment by rSeeFip** [comment] 2020-01-09 08:31
Sorry to less time because i have recognized this error in productive system :-(

**Comment by apobekiaris** [comment] 2020-01-09 08:31
what this mean?

**Comment by rSeeFip** [comment] 2020-01-09 08:33
for deeper inspect what fails in modules build

**Comment by expand** [comment] 2020-01-11 17:07
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ModelMapper: Try .net reflection if Fasterflect throw ambiguoes exceptions #653 #656 #654](https://github.com/eXpandFramework/DevExpress.XAF/commit/1a259535cad5d9df1bc6eb6df1e7e6fd48c13c03)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment] 2020-01-11 18:39
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ModelMapper: Try .net reflection if Fasterflect throw ambiguoes exceptions #653 #656 #654](https://github.com/eXpandFramework/DevExpress.XAF/commit/764666de79495032e7f598f8581f663ef72626fc)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by rSeeFip** [comment] 2020-02-06 11:44
the Application works, but by starting in debug mode, after login, some ambiguos matches issues thrown on reflecting. 
stack comes asap

**Comment by expand** [comment] 2020-04-26 21:01
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2020-04-26 21:01 UTC
Labels: Bug, Standalone_XAF_Modules
