### ISSUE TITLE
ModelEditor does not open at Solution.Module level error opening 'Xpand.ExpressApp.TreeListEditors.Win.XpandTreeListEditorsWinModule' module

### ISSUE THREAD

**Issue by laceratione** [eXpandFramework/eXpand#684] opened 2020-03-06 05:04 UTC
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
When I'm click on the "Open Model Editor" solution module, I get the following error occurs:"Exception occurs while initializing the 'Xpand.ExpressApp.TreeListEditors.Win.XpandTreeListEditorsWinModule' module: The type initializer for 'Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService' threw an exception." How to fix?
![errorEditor](https://user-images.githubusercontent.com/43997427/76054192-af0d4300-5f91-11ea-9d9e-d045042e968b.png)

**Comment by laceratione** [comment] 2020-03-06 05:07
Error details:
at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager)
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModulesPatch(ApplicationModulesManager __instance)
   at SetupModules_Patch1(ApplicationModulesManager )
   at DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   at DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(ModuleBase module, String assembliesPath, List`1 additionalModules, ISecurityStrategyBase securityInstance)
   at DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   at DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   at DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
----------InnerException----------
The type initializer for 'Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService' threw an exception.
----------StackTrace----------
   at Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.Extend(ApplicationModulesManager modulesManager, PredefinedMap map, Action`1 configure)
   at Xpand.ExpressApp.TreeListEditors.Win.XpandTreeListEditorsWinModule.Setup(ApplicationModulesManager moduleManager)
   at Xpand.XAF.Modules.Reactive.ReactiveModuleBase.SetupModules(ApplicationModulesManager applicationModulesManager)
----------InnerException----------
Could not load file or assembly 'Xpand.ExpressApp.Win, Version=19.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
----------StackTrace----------
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.GetAssembly(Assembly[] assemblies, String name, Boolean partialMatch)
   at Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.Init()
   at Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService..cctor()
----------InnerException----------
The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by apobekiaris** [comment] 2020-03-06 05:29
>Could not load file or assembly 'Xpand.ExpressApp.Win, Version=19.2.6.0

this is an invalid version our packages versions are 19.2.60x.x. Did you custom compile the source code?

**Comment by laceratione** [comment] 2020-03-06 05:35
we use installation script from GitHub "Set-ExecutionPolicy Bypass -Scope Process -Force;iex "$(([System.Net.WebClient]::new()).DownloadString('http://install.expandframework.com'));Install-Xpand -Assets @('Assemblies','Nuget','VSIX','Source')  #-Version '19.2.602.0' -SkipGac -InstallationPath 'C:\Solution'"

**Comment by apobekiaris** [comment] 2020-03-06 05:45
check the version Xpand.ExpressApp.Win manually please and let me know what they say

**Comment by laceratione** [comment] 2020-03-06 05:53
19.2.602.0

![xpand version](https://user-images.githubusercontent.com/43997427/76056508-a2401d80-5f98-11ea-8a36-a27d3c95cae9.png)

**Comment by apobekiaris** [comment] 2020-03-06 05:56
i will get back to u once I research it a bit

**Comment by expand** [comment] 2020-03-06 06:11
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by apobekiaris** [comment] 2020-03-06 06:12
the lab contains related work can u also try if it already fixed?

http://lab.releases.expandframework.com/

**Comment by laceratione** [comment] 2020-03-06 06:55
Installed 19.2.602.3 but didnt help, we get the same problem

**Comment by apobekiaris** [comment] 2020-03-06 06:57
Can you repro it on a sample?

**Comment by apobekiaris** [comment] 2020-03-06 07:00
do you have installed the VSIX? it is a requirement if u try to use the ME from within VS. In any case it won't allow u to open the model if VSIX not found with a prompt to install VSIX

**Comment by laceratione** [comment] 2020-03-06 07:07
> Can you repro it on a sample?

I created a new clean Xpand project and ModelEditor works ok there. But still doesnt work in a big project

> do you have installed the VSIX? it is a requirement if u try to use the ME from within VS. In any case it won't allow u to open the model if VSIX not found with a prompt to install VSIX

This one? 
![vsix expand](https://user-images.githubusercontent.com/43997427/76060275-b25cfa80-5fa2-11ea-82ab-350ea9151587.png)

**Comment by apobekiaris** [comment] 2020-03-06 07:08
does the Xpand.ModelEditor works?

**Comment by laceratione** [comment] 2020-03-06 07:19
Are you asking about this one? Works in a new project but error in a big one 
![newproject model](https://user-images.githubusercontent.com/43997427/76061090-98bcb280-5fa4-11ea-82af-5da672e2e92e.png)

**Comment by apobekiaris** [comment] 2020-03-06 07:31
nope about the

https://github.com/eXpandFramework/DevExpress.XAF/tree/master/tools/Xpand.XAF.ModelEditor#vsix-integration

**Comment by laceratione** [comment] 2020-03-06 08:23
So i tried to install Xpand.XAF.ModelEditor on a clean project. After building it says: 
![Paket](https://user-images.githubusercontent.com/43997427/76065205-f8b75700-5fac-11ea-97b1-9cf10070e907.png)

Isnt that a mistake somewhere because it says "Paket" instead of "Packet" in commands? 

Also i tried to open XAF Soultion Model List and its not loading also 
![xaf soultion model list](https://user-images.githubusercontent.com/43997427/76065459-8d21b980-5fad-11ea-9618-65e43151be16.png)

**Comment by apobekiaris** [comment] 2020-03-06 08:36
add this function to your Get-DevExpressVersion.ps1 and try again it should compile now

```ps1
function Get-PaketReferences {
    [CmdletBinding()]
    param (
        [System.IO.FileInfo]$projectFile = "."
    )
    
    begin {
        
    }
    
    process {
        $paketDirectoryInfo = $projectFile.Directory
        $paketReferencesFile = "$($paketDirectoryInfo.FullName)\paket.references"
        if (Test-Path $paketReferencesFile) {
            Push-Location $projectFile.DirectoryName
            $dependencies = dotnet paket show-installed-packages --project $projectFile.FullName --all --silent | ForEach-Object {
                $parts = $_.split(" ")
                [PSCustomObject]@{
                    Include = $parts[1]
                    Version = $parts[3]
                }
            }
            Pop-Location
            $c = Get-Content $paketReferencesFile | ForEach-Object {
                $ref = $_
                $d = $dependencies | Where-Object {
                    $ref -eq $_.Include
                }
                $d
            }
            Write-Output $c
        }
    }
    
    end {
        
    }
}
```

**Comment by laceratione** [comment] 2020-03-06 09:38
Ok this editor works in Solution.Win but still cant open in Solution.Module with the same problem 
![editor error](https://user-images.githubusercontent.com/43997427/76071209-b34c5700-5fb7-11ea-8d71-bcc6ef8d4100.png)

**Comment by apobekiaris** [comment] 2020-03-06 10:07
the problem is about conflicting versions evenmore u just mentioned that in Solution.Module u use the TreeListEditor.Win which is not valid to use a win module inside an agnostic.

**Comment by expand** [comment] 2020-03-17 12:56
The pre-release [2.201.0.3](https://github.com/eXpandFramework/DevExpress.XAF/releases/tag/2.201.0.3) in the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [ModelEditor: fails if XpandPwsh not installed #684](https://github.com/eXpandFramework/DevExpress.XAF/commit/e5c97b4e6fbd7c55dabb0a4d0ffd3d795221e7bd)

Released packages:
1. [Xpand.Extensions v.2.201.9.2](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions)
 1. [Xpand.Extensions.Mono.Cecil v.2.201.9.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil)
 1. [Xpand.Extensions.Reactive v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive)
 1. [Xpand.Extensions.XAF v.2.201.9.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF)
 1. [Xpand.Extensions.XAF.Xpo v.2.201.9.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo)
 1. [Xpand.XAF.Core.All v.2.201.25.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.ModelEditor v.1.201.2.1](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/tools/Xpand.XAF.ModelEditor)
 1. [Xpand.XAF.Modules.AutoCommit v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/AutoCommit)
 1. [Xpand.XAF.Modules.CloneMemberValue v.2.201.9.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneMemberValue)
 1. [Xpand.XAF.Modules.CloneModelView v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/CloneModelView)
 1. [Xpand.XAF.Modules.GridListEditor v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/GridListEditor)
 1. [Xpand.XAF.Modules.HideToolBar v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/HideToolBar)
 1. [Xpand.XAF.Modules.MasterDetail v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/MasterDetail)
 1. [Xpand.XAF.Modules.ModelMapper v.2.201.9.6](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelMapper)
 1. [Xpand.XAF.Modules.ModelViewInheritance v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ModelViewInheritance)
 1. [Xpand.XAF.Modules.OneView v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/OneView)
 1. [Xpand.XAF.Modules.ProgressBarViewItem v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ProgressBarViewItem)
 1. [Xpand.XAF.Modules.Reactive v.2.201.9.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive)
 1. [Xpand.XAF.Modules.Reactive.Logger v.2.201.9.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger)
 1. [Xpand.XAF.Modules.Reactive.Logger.Client.Win v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win)
 1. [Xpand.XAF.Modules.Reactive.Logger.Hub v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Logger.Hub)
 1. [Xpand.XAF.Modules.Reactive.Win v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/Reactive.Win)
 1. [Xpand.XAF.Modules.RefreshView v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/RefreshView)
 1. [Xpand.XAF.Modules.SuppressConfirmation v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/SuppressConfirmation)
 1. [Xpand.XAF.Modules.ViewEditMode v.2.201.9.3](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/ViewEditMode)
 1. [Xpand.XAF.Web.All v.2.201.25.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)
 1. [Xpand.XAF.Win.All v.2.201.25.4](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules)


Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment] 2020-04-20 05:25
Issue is `deprioritized` as `no Assignee found` and scheduled for `auto-close` if no activity in the next `60 days`. Thanks a lot for your contribution.

**Comment by expand** [comment] 2020-06-19 21:01
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2020-06-19 21:01 UTC
Labels: Bug, ModelMapper, Question, ShowStopper, Standalone_XAF_Modules, XpandModelEditor
