### ISSUE TITLE
eXpand ExcelImport Module: View disappearance when uploading an excel file

### ISSUE THREAD

**Issue by okanmazman** [eXpandFramework/eXpand#384] opened 2019-04-26 07:24 UTC
Hi,
I am using ExcelImport module of eXpand framework (18.1.5.5).When I select a excel file to upload ,the related view refreshes and disappeares appearently on postback.(There are 2 ss enclosed)
I could not get any error or any warnings.
What could be the problem here? Actually I could not managed to debug this problem also.
Could It be because of a customization or a spesific configuration?
Regards
Okan
![disappeared-step-1](https://user-images.githubusercontent.com/46827534/56790253-c1b0da80-680c-11e9-9845-225af65ce0ad.png)
![disappeared-step-2](https://user-images.githubusercontent.com/46827534/56790254-c2497100-680c-11e9-89c6-a1adb2ed6ef8.png)

**Additional context**

**Comment by apobekiaris** [comment] 2019-04-26 11:36
please try this suggestion and let me know if it worked

https://github.com/eXpandFramework/eXpand/issues/377#issuecomment-485678932

**Comment by expand** [comment] 2019-06-26 03:01
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Comment by okanmazman** [comment] 2019-07-02 10:42
I am sorry that I have just forgot to update this thread.I just tried https://github.com/eXpandFramework/eXpand/issues/377#issuecomment-485678932
but there is no effect on it.I have used exe installer to set up eXpand framework.Should I try from  nuget installer?I am using DevExpress  v18.1.Which  is the last version of eXpand should I install for this version of DevExpress?

**Comment by apobekiaris** [comment] 2019-07-02 10:48
to resolve the issue let's try to find out if it works with the latest 18.2 version. I do not imply u should switch your production to 18.2 just install use projectconverter in your project and update xpand to latest. Do u get the same results?

Or if you can post repro instruction I could for sure answer better. The problem there is probably an error on the import thread, I am not sure if its in the log, it should be can u check. Can u also check a simple BO import?

**Comment by apobekiaris** [comment] 2019-07-02 10:52
maybe @isatahiri has something to add here?

**Comment by isatahiri** [comment] 2019-07-02 11:30
How about Winform client ? Do you have the same behaviour ?

**Comment by okanmazman** [comment] 2019-07-02 11:45
No.Winforms works fine. I am now trying to uninstall Xpand framework and reinstall the 18.2 version.(BTW The powershell installer just download and installed the latest version even if I specify the version I desire.)

**Comment by isatahiri** [comment] 2019-07-02 12:18
Make sure you take away the # before the version parameter : 
![image](https://user-images.githubusercontent.com/41955268/60512166-2b010e00-9cd4-11e9-8076-56b614103e45.png)

**Comment by okanmazman** [comment] 2019-07-02 13:31
Thanks for reminding it . :) Now I  installed Xpand 18.2.704 but cannot reach toolbox item from Xpand. Also I could not find any ToolboxCreator.exe within Xpand.DLL file. I think I need to learn a descent way to add Xpand Framework and its Excel Importer to my Xaf solution. I guess  I am doing something wrong :/

**Comment by apobekiaris** [comment] 2019-07-02 13:35
there is no ToolBoaxCreator anymore, toolbox componenet registration is handled from Xpand.VSIX. 

>I think I need to learn a descent way to add 

fastest way to avoid VS design time issue is in the ctor of your agnostic, win modules

```cs
this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ExcelImporter.ExcelImporterModule));
````

```cs
this.RequiredModuleTypes.Add(typeof(Xpand.ExpressApp.ExcelImporter.Win.ExcelImporterWinModule));
```

then compile and let the compiler tell u what reference is miisng if any.

**Comment by apobekiaris** [comment] 2019-07-02 13:36
ssame for the web i miised

**Comment by okanmazman** [comment] 2019-07-03 07:51
> to resolve the issue let's try to find out if it works with the latest 18.2 version. I do not imply u should switch your production to 18.2 just install use projectconverter in your project and update xpand to latest. Do u get the same results?
> 
> Or if you can post repro instruction I could for sure answer better. The problem there is probably an error on the import thread, I am not sure if its in the log, it should be can u check. Can u also check a simple BO import?

Where can I check the log? Is it a standalone file within the project?
Do you want me to try BO import via IO module of Xpand?

I have just installed the 18.2.704.0 version but gave conflict with devexpress v18.1.5 so I gave a chance to v18.1.5.4 of Xpand insted of v18.1.5.5 . After that the issue is still insisting.

ps: I used .exe file for installing xpand and added .dll references to the projects by my hand so that There is no xpand menu in VS menu bar right now

**Comment by apobekiaris** [comment] 2019-07-03 10:35
can u share the project u use for this? along with the xls data and detailed repro instructions? I can try to import with the latest version for u so we can tell whats the problem or if it has been resolved.

>Where can I check the log?
this is the expressappframework.log file in the root of your site

>I have just installed the 18.2.704.0 version but gave conflict with devexpress v18.1.5 
xpand 18.2.7x works only with XAF 18.2.7

>Do you want me to try BO import via IO module of Xpand?Is Xpand.Express.App.ExcelImporter dependent to IO module?
this a different module no relation

>ps: I used .exe file for installing xpand and added .dll references to the projects by my hand so that There is no xpand menu in VS menu bar right now

you do not need VSIX feature for the module to work

**Comment by okanmazman** [comment] 2019-07-05 10:05
I am thankful for your attention and help. I am about to try one more thing.We just updated our prod repository to the lastest version of DevExpress. I will try with the latest version of Xpand and agnostic approach . I will let you know if it resolves . Second step will be trying to share the project.
Thank you again

**Comment by apobekiaris** [comment] 2019-07-05 11:09
i can sure help u better on a sample over the latest, the module is functional at least other users have in prod

**Comment by okanmazman** [comment] 2019-07-09 10:59
Latest update from me:

1. I have just installed the latest version of eXpandExcelImporter and eXpandExcelImporterWeb  from nuget manager.
[eXpressAppFramework.log](https://github.com/eXpandFramework/eXpand/files/3372591/eXpressAppFramework.log)

2. I have added the modules from toolbox to Module.cs of ProjectName.Module (Not ProjectName.Module.Web or ProjectName.Module.Win ). I can see the excelimporter module in ProjectName.Module.Web's WebApplication.cs designer.
3. I have achieved to see Excel Import menu in my default listview section.
4. But again I am getting the error attached when trying to upload a .xls file
[eXpressAppFramework.log](https://github.com/eXpandFramework/eXpand/files/3372596/eXpressAppFramework.log)

Is there any problem in my install and add procedure of the eXpand?

**Comment by apobekiaris** [comment] 2019-07-09 12:22
nope the problem is not with your installation, however the log does not provide much help. Can you post a solution where the problem occurs? If you cannot post in public you can find my email in my profile

**Comment by okanmazman** [comment] 2019-07-10 14:53
Actually It is kinda impossible me to send the project or a part of the project independently.It is totally ~1.5GB after deleting the builded dlls. However I decided to create a fresh project and repeated all the same install procedures on it .At this point there is an interesting error .You can see attached ss.There is no upload button when heading to detailview.You can also find the project below.
![image](https://user-images.githubusercontent.com/46827534/60977742-aac45380-a338-11e9-9b34-02268584455e.png)

project link: https://we.tl/t-5ATPeDF5H5

**Comment by okanmazman** [comment] 2019-07-10 14:56
> nope the problem is not with your installation, however the log does not provide much help. Can you post a solution where the problem occurs? If you cannot post in public you can find my email in my profile

**Comment by apobekiaris** [comment] 2019-07-12 08:57
have't test your project yet but looks like u missed a few modules, make ExcelImporterWeb and FileAttachments modules agnostic and web also registered and let me know our status

**Comment by apobekiaris** [comment] 2019-07-12 09:12
in fact by looking at the code the ExcelImporterWebModule registers the DevExpress.ExpressApp.FileAttachments.Web.FileAttachmentsAspNetModule so my guess now is that you missed to register ExcelImporterWebModule

**Comment by okanmazman** [comment] 2019-07-12 11:03
_Uncaught TypeError: ASPx.GetGlobalEvents is not a function
    at eval (eval at _aspxRunStartupScriptsCore (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_179,1_180,1_19,1_209,1_220,1_221,1_207,1_223,1_232,1_234,1_235,1_226,1_230,1_233,1_236,1_21,1_22,1_186,1_188,1_190,1_182,1_189,1_178,1_34,1_43,1_32,1_48,1_9-ldZ3j:6630), <anonymous>:2:16)
    at _aspxRunStartupScriptsCore (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_179,1_180,1_19,1_209,1_220,1_221,1_207,1_223,1_232,1_234,1_235,1_226,1_230,1_233,1_236,1_21,1_22,1_186,1_188,1_190,1_182,1_189,1_178,1_34,1_43,1_32,1_48,1_9-ldZ3j:6630)
    at _aspxRunStartupScripts (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_179,1_180,1_19,1_209,1_220,1_221,1_207,1_223,1_232,1_234,1_235,1_226,1_230,1_233,1_236,1_21,1_22,1_186,1_188,1_190,1_182,1_189,1_178,1_34,1_43,1_32,1_48,1_9-ldZ3j:6606)
    at Object.ASPx.FinalizeScriptProcessing (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_179,1_180,1_19,1_209,1_220,1_221,1_207,1_223,1_232,1_234,1_235,1_226,1_230,1_233,1_236,1_21,1_22,1_186,1_188,1_190,1_182,1_189,1_178,1_34,1_43,1_32,1_48,1_9-ldZ3j:6600)
    at Object.ASPx.OnScriptLoadCallback (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_179,1_180,1_19,1_209,1_220,1_221,1_207,1_223,1_232,1_234,1_235,1_226,1_230,1_233,1_236,1_21,1_22,1_186,1_188,1_190,1_182,1_189,1_178,1_34,1_43,1_32,1_48,1_9-ldZ3j:6674)
    at HTMLScriptElement.eval (eval at _aspxProcessScripts (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_179,1_180,1_19,1_209,1_220,1_221,1_207,1_223,1_232,1_234,1_235,1_226,1_230,1_233,1_236,1_21,1_22,1_186,1_188,1_190,1_182,1_189,1_178,1_34,1_43,1_32,1_48,1_9-ldZ3j:6563), <anonymous>:3:6)_
This is the error I am not taking after registerin ExcelImporterWebModule via WebApplication.cs

**Comment by okanmazman** [comment] 2019-07-12 12:09
> _Uncaught TypeError: ASPx.GetGlobalEvents is not a function
> at eval (eval at _aspxRunStartupScriptsCore (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_179,1_180,1_19,1_209,1_220,1_221,1_207,1_223,1_232,1_234,1_235,1_226,1_230,1_233,1_236,1_21,1_22,1_186,1_188,1_190,1_182,1_189,1_178,1_34,1_43,1_32,1_48,1_9-ldZ3j:6630), :2:16)
> at _aspxRunStartupScriptsCore (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_179,1_180,1_19,1_209,1_220,1_221,1_207,1_223,1_232,1_234,1_235,1_226,1_230,1_233,1_236,1_21,1_22,1_186,1_188,1_190,1_182,1_189,1_178,1_34,1_43,1_32,1_48,1_9-ldZ3j:6630)
> at _aspxRunStartupScripts (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_179,1_180,1_19,1_209,1_220,1_221,1_207,1_223,1_232,1_234,1_235,1_226,1_230,1_233,1_236,1_21,1_22,1_186,1_188,1_190,1_182,1_189,1_178,1_34,1_43,1_32,1_48,1_9-ldZ3j:6606)
> at Object.ASPx.FinalizeScriptProcessing (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_179,1_180,1_19,1_209,1_220,1_221,1_207,1_223,1_232,1_234,1_235,1_226,1_230,1_233,1_236,1_21,1_22,1_186,1_188,1_190,1_182,1_189,1_178,1_34,1_43,1_32,1_48,1_9-ldZ3j:6600)
> at Object.ASPx.OnScriptLoadCallback (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_179,1_180,1_19,1_209,1_220,1_221,1_207,1_223,1_232,1_234,1_235,1_226,1_230,1_233,1_236,1_21,1_22,1_186,1_188,1_190,1_182,1_189,1_178,1_34,1_43,1_32,1_48,1_9-ldZ3j:6674)
> at HTMLScriptElement.eval (eval at _aspxProcessScripts (DXR.axd?r=1_11,1_63,1_12,1_13,1_14,1_15,1_17,1_41,24_364,24_365,24_366,24_367,24_359,24_362,24_363,24_360,24_361,24_368,1_23,1_8,1_49,1_24,1_33,1_35,1_179,1_180,1_19,1_209,1_220,1_221,1_207,1_223,1_232,1_234,1_235,1_226,1_230,1_233,1_236,1_21,1_22,1_186,1_188,1_190,1_182,1_189,1_178,1_34,1_43,1_32,1_48,1_9-ldZ3j:6563), :3:6)_
> This is the error I am not taking after registerin ExcelImporterWebModule via WebApplication.cs

I have solved this problem. Now I have the exact same problem which I shared with you by a logfile above. The same message (_**An asynchronous operation cannot be started at this time. Asynchronous operations may only be started within an asynchronous handler or module or during certain events in the Page lifecycle. If this exception occurred while executing a Page, ensure that the Page is marked <%@ Page Async="true" %>. This exception may also indicate an attempt to call an "async void" method, which is generally unsupported within ASP.NET request processing. Instead, the asynchronous method should return a Task, and the caller should await it.)**_ is stated in this log.

**Comment by apobekiaris** [comment] 2019-07-12 12:10
is it reproduced in the attached solution?

**Comment by okanmazman** [comment] 2019-07-12 12:41
This is the last version of solution which the error reproduced within:
https://we.tl/t-oS2CUuOY9K

**Comment by apobekiaris** [comment] 2019-07-16 18:56
I have reproduce the problem but due to works I cannot prioritize a fix. I will update you once is fixed.

**Comment by okanmazman** [comment] 2019-07-18 06:34
Thank you very much for your attention

**Comment by okanmazman** [comment] 2019-08-01 13:22
Are there any updates? :)

**Comment by apobekiaris** [comment] 2019-08-01 17:38
not yet i still assigned to the case

**Comment by expand** [comment] 2019-08-04 08:25
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF) repository includes commits that relate to this task:

* [Web Subscription disposing throws System.InvalidOperationException: An asynchronous operation cannot be started at this time #394 #384](https://github.com/eXpandFramework/DevExpress.XAF/commit/13c2c341d43f3850b1687dfb9edef36b17da7524)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the Xpand.XAF.Modules directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment] 2019-08-04 11:30
eXpand.lab release [19.1.402.15](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.402.15) includes commit that relate to this task:

* [Web Subscription disposing throws System.InvalidOperationException: An asynchronous operation cannot be started at this time #394 #384](https://github.com/eXpandFramework/eXpand.lab/commit/df3d5bd97f72786023a22cec78761c8a28bfb1aa)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by okanmazman** [comment] 2019-08-22 08:23
Hi,
Thanks for your effort and attention .I appreciate your will to solve this issue.
I am now closing this thread but It seems I will have to open another one separately  in the future about installing nuget packages of yours.
Best Regards

**Closed** 2019-08-22 08:23 UTC
Labels: ExcelImporter, Question

**Comment by apobekiaris** [comment] 2019-08-22 11:44
feel free to post

**Comment by okanmazman** [comment] 2019-09-26 08:32
Thanks it worked after all update process.

**Comment by apobekiaris** [comment] 2020-01-19 12:11
see #661
