### ISSUE TITLE
Null reference opening first time an complex detailview

### ISSUE THREAD

**Issue by vimarx** [eXpandFramework/eXpand#640] opened 2019-12-09 03:49 UTC
While testing 19.2.402. I found this exception thrown (before the exception occurred but was hidden)

   en Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.BindToModel(IModelNodeDisabled modelNodeDisabled, Object instance)
   en Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.BindTo(IModelNodeDisabled modelNode, Object instance)
   en Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.BindTo(ValueTuple`3 data)
   en Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.<>c.<BindLayoutGroupControl>b__5_3(ValueTuple`3 tuple)
   en System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value) en d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Do.cs: línea 38
   en System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) en d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ExceptionServicesImpl.cs: línea 16

I don't know how to get the .pdb for .XAF modules.
![image](https://user-images.githubusercontent.com/226800/70405817-427bba00-1a1d-11ea-8bc0-50ba89946781.png)

**Comment by rSeeFip** [comment] 2019-12-10 05:06
Try to build XAF.Modules byself, their was an Bug and the fix is not in actually released XAF 19.402.0 XAF.Modules. For me it works

**Comment by apobekiaris** [comment] 2019-12-10 07:24
>I don't know how to get the .pdb for .XAF modules.

https://github.com/eXpandFramework/eXpand/wiki/HowToDebug#from-the-nuget-packages

debugging is enabled as per docs.

consider enable the reactive logger to get more info to what happened before the exception and also posting details of your problem if you do not spent the time to describe your problem how you expect others time?

>Try to build XAF.Modules byself, their was an Bug and the fix is not in actually released XAF 19.402.0 XAF.Modules. For me it works

to my knowledge there is nothing in the lab at the moment

**Comment by apobekiaris** [comment] 2019-12-10 07:33
for such case one at least want to know what type of maps are enabled? which modules? and if u invest a few minutes to create a sample most probably will help u to resolve it your self but at for sure it will help me to resolve fast.

**Comment by rSeeFip** [comment] 2019-12-19 09:43
i can reproduce this issue to on "complexe views" , following some stacks i get

[new 9.txt](https://github.com/eXpandFramework/eXpand/files/3982790/new.9.txt)
[new 10.txt](https://github.com/eXpandFramework/eXpand/files/3982791/new.10.txt)
[new 11.txt](https://github.com/eXpandFramework/eXpand/files/3982792/new.11.txt)


by businessobjects with itself association and using of Variants View.

When i build an sample it works, but sample not reflect complexity in app

**Comment by apobekiaris** [comment] 2019-12-19 10:11
looking at your stacks it looks like a side effect, the Model can never be null. However it throws to a point that u can override. So what happens when 
```cs
            ModelBindingService.ControlBind.Subscribe(parameter => {
                parameter.Handled=parameter.Model==null
            })
```

what's the parameter values at this point?

**Comment by rSeeFip** [comment] 2019-12-19 16:38
in detail view by child view of self association i get null in model Map
![image](https://user-images.githubusercontent.com/43534405/71191002-e23f1080-2285-11ea-990a-6cee1ae9747d.png)

and thru this objectreference empty 
[new 13.txt](https://github.com/eXpandFramework/eXpand/files/3984589/new.13.txt)
error in ViewSiteManager.cs on
![image](https://user-images.githubusercontent.com/43534405/71191197-3cd86c80-2286-11ea-87ca-16748daf3d5e.png)

**Comment by apobekiaris** [comment] 2019-12-20 03:45
what is the `infoname` value?

**Comment by rSeeFip** [comment] 2019-12-20 05:27
infoname is LayoutConrolGroup
![image](https://user-images.githubusercontent.com/43534405/71232333-d5f09d00-22f1-11ea-977d-21d853644cec.png)

**Comment by apobekiaris** [comment] 2019-12-20 06:41
previously I posted https://github.com/eXpandFramework/eXpand/issues/640#issuecomment-567425195

that code should workaround the problem did you fail to use it?

**Comment by rSeeFip** [comment] 2019-12-20 07:43
yes, i fail. but i thinks this depend to my implementation

**Comment by apobekiaris** [comment] 2019-12-20 11:30
why does it fail? its a copy paste thing and should work

**Comment by rSeeFip** [comment] 2019-12-20 11:49
when i copy it to Bind data the issue still comes

**Comment by rSeeFip** [comment] 2019-12-20 12:13
![image](https://user-images.githubusercontent.com/43534405/71254186-7b276780-232a-11ea-8fe2-0be0c99a9905.png)

**Comment by apobekiaris** [comment] 2019-12-20 12:25
no this is wrong, the code i posted should go to your project before the model is created somewhere perphaps in the constructor of your module.

**Comment by rSeeFip** [comment] 2019-12-20 12:33
Sorry, I'm feeling like a rookie.
yes, of course it works if i call it during initialization.

the detail view now opens without errors

**Comment by apobekiaris** [comment] 2019-12-20 12:35
good to hear u just got confused with the deep dive there is luck of oxygen :), I would like to see the different for this view and what the ME displays as the layout, Please try to open as much nodes as possible and post a scrrenshot

**Comment by apobekiaris** [comment] 2019-12-20 12:37
post the model diffs for the layout node for this view and the screenshot

**Comment by rSeeFip** [comment] 2019-12-20 13:09
![image](https://user-images.githubusercontent.com/43534405/71256818-428b8c00-2332-11ea-914b-a5f4a80b3e5d.png)
[new 9.txt](https://github.com/eXpandFramework/eXpand/files/3988388/new.9.txt)

**Comment by rSeeFip** [comment] 2019-12-20 13:09
its too big for screenshot i paste it to file new9

**Comment by apobekiaris** [comment] 2019-12-20 13:15
for now I will let the source code throw as it looks like this state is invalid, users can use the workaround safely @vimarx .

**Comment by apobekiaris** [comment] 2019-12-20 13:21
can u confirm that without the workaround throws for any detailview that have nodes removed?

**Comment by apobekiaris** [comment] 2019-12-20 13:23
i meant group nodes it has to remove the `DevExpressXtraLayout_LayoutControlGroup`

**Comment by rSeeFip** [comment] 2019-12-20 13:34
yes by other view which occurs error they have node 
![image](https://user-images.githubusercontent.com/43534405/71257761-d8c0b180-2334-11ea-84f0-6300bff7cff4.png)
but when i remove your fix and delete this line in xamfl the error  still occurs

**Comment by apobekiaris** [comment] 2019-12-20 13:35
ok thnks for the input I will research further it looks like we are close to a better solution.

**Comment by rSeeFip** [comment] 2019-12-20 13:39
as far i could test your fix not create different errors, it could be used until better solution

Thanks,

**Comment by vimarx** [comment] 2019-12-20 14:15
> for now I will let the source code throw as it looks like this state is invalid, users can use the workaround safely @vimarx .

it works for me. thanks!

for vb people, I had to implement the solution as 
`ModelBindingService.ControlBind.Subscribe(New IobsDummy)

    End Sub

    Class IobsDummy
        Implements IObserver(Of Parameter)

        Public Sub OnNext(value As Parameter) Implements IObserver(Of Parameter).OnNext
            value.Handled = value.Model Is Nothing
        End Sub

        Public Sub OnError([error] As Exception) Implements IObserver(Of Parameter).OnError
        End Sub

        Public Sub OnCompleted() Implements IObserver(Of Parameter).OnCompleted
        End Sub
    End Class`

**Comment by Lukas-lab** [comment] 2020-01-27 16:52
hi i have the same issue as rSeeFlip.

i tried to use the fix. which references i have to add? 

Visual Studio can't find parameter.Handled and parameter.Model

CS1660	"Lambdaausdruck" kann nicht in den Typ "IObserver<Parameter>" konvertiert werden, da es kein Delegattyp ist.
![image](https://user-images.githubusercontent.com/52030639/73195182-b5f09c80-412d-11ea-9124-f5e594f3ba0d.png)

**Comment by apobekiaris** [comment] 2020-01-28 01:00
the solution should be already in the latest lab see #659 

to apply the work around if you do not want to try the lab build you need 

```ps1
Install-Package System.Reactive
```

**Comment by expand** [comment] 2020-01-29 09:05
Issue is deprioritized as 
o Assignee found and scheduled for uto-close if not activity in the next 60 days.

**Comment by expand** [comment] 2020-03-29 21:02
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2020-03-29 21:02 UTC
