### ISSUE TITLE
PositionsInListView Empty Database

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#721] opened 2020-06-18 10:35 UTC
If you start with a new Database (let XAF create it), you got the Error:

iXISXRM.Win.exe Error: 0 : 18.06.20 12:29:45.991	================================================================================
The error occurred:

	Type:       NullReferenceException
	Message:    Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
	Data:       0 entries
	Stack trace:

   bei Xpand.XAF.Modules.PositionInListview.PositionInListViewService.<>c.<PositionNewObjects>b__6_1(ValueTuple`2 _)
   bei System.Reactive.Linq.ObservableImpl.Do`1.OnNext._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Do.cs:Zeile 38.
	InnerException is null

And the in every ListView the Up and Down Button is visible.

Xpand.XAF.Modules.Reactive.ReactiveModuleBase.Unload(typeof(Xpand.XAF.Modules.PositionInListview.PositionInListViewModule));

does not work.

**Comment by expand** [comment] 2020-06-18 21:04
We will try to answer all questions that do not require research within 24hr.
To prioritize cases that require research we use the following labels **in order**. For all other issues the posting time is respected.
1. [❇️ Exclusive-Services](https://github.com/eXpandFramework/eXpand/labels/❇️%20Exclusive-Services)
 1. [❤ Bronze Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Bronze%20Sponsor)
 1. [❤ Sponsor](https://github.com/eXpandFramework/eXpand/labels/❤%20Sponsor)
 1. [❤ Backer](https://github.com/eXpandFramework/eXpand/labels/❤%20Backer)
 1. [Installation](https://github.com/eXpandFramework/eXpand/labels/Installation)
 1. [ShowStopper](https://github.com/eXpandFramework/eXpand/labels/ShowStopper)
 1. [Nuget](https://github.com/eXpandFramework/eXpand/labels/Nuget)
 1. [Contribution](https://github.com/eXpandFramework/eXpand/labels/Contribution)
 1. [BreakingChange](https://github.com/eXpandFramework/eXpand/labels/BreakingChange)
 1. [ReproSample](https://github.com/eXpandFramework/eXpand/labels/ReproSample)
 1. [Deployment](https://github.com/eXpandFramework/eXpand/labels/Deployment)
 1. [must-have](https://github.com/eXpandFramework/eXpand/labels/must-have)


**This case is prioritized.**

**Comment by apobekiaris** [comment] 2020-06-21 04:47
i cannot reproduce the issue with the info you posted. Attaching my sample where I installed the eXpandSystemWin and configure the Customer_ListView for PositionInListView. I also added the [unload call](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules/PositionInListView#issues-debugging-troubleshooting) in Program.cs and as u can see in the sample the Customer_ListView does not have the PositionInListView actions.

[Solution14.zip](https://github.com/eXpandFramework/eXpand/files/4808923/Solution14.zip)

What about your log?

**Comment by expand** [comment] 2020-07-11 21:06
Issue is `deprioritized` as `no Assignee found` and scheduled for `auto-close` if no activity in the next `60 days`. Thanks a lot for your contribution.

**Comment by expand** [comment] 2020-09-10 21:01
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2020-09-10 21:01 UTC
Labels: Bug, PositionInListView, Standalone_XAF_Modules, ❤ Sponsor
