### ISSUE TITLE
Error opening XpandCategorizedListEditor

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#652] opened 2020-01-05 15:32 UTC
When I open a XpandCategorizedListEditor for the 1st time I got an error. Opening once again everything is allright. If I start the application new, the behavior repeats (for the same Views).

Here is the Errorlog:

05.01.20 16:25:16.682	================================================================================
05.01.20 16:25:16.688	Trace Log for iXISXRM.Win.exe is started
05.01.20 16:25:16.692	================================================================================
iXISXRM.Win.exe Error: 0 : 05.01.20 16:26:35.744	================================================================================
The error occurred:

	Type:       InvalidOperationException
	Message:    Exception occurs while assigning the 'XpandListView, ID:Profil_ListView' view to XpandWinWindow:
No match for property with name MainView and flags Instance | NonPublic | Public | Static on type DevExpress.XtraEditors.SidePanelContainer.
	Data:       0 entries
	Stack trace:

   bei DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
   bei DevExpress.ExpressApp.ViewVariantsModule.FrameVariantsEngine.RecreateFrameView(IViewsFactory viewsFactory, Frame frame, String rootViewId, String variantViewId)
   bei DevExpress.ExpressApp.ViewVariantsModule.FrameVariantsEngine.RecreateFrameViewCore(IViewsFactory viewsFactory, Frame frame, String rootViewId, String currentVariantViewId)
   bei DevExpress.ExpressApp.ViewVariantsModule.FrameVariantsEngine.ChangeFrameViewToVariant(Frame frame, VariantsInfo variantsInfo, VariantInfo variantInfo)
   bei DevExpress.ExpressApp.ViewVariantsModule.CurrentFrameViewVariantsManager.ChangeToVariant(VariantInfo variantInfo)
   bei DevExpress.ExpressApp.ViewVariantsModule.ChangeVariantController.changeVariantAction_OnExecute(Object sender, SingleChoiceActionExecuteEventArgs args)
   bei DevExpress.ExpressApp.Actions.SingleChoiceAction.RaiseExecute(ActionBaseEventArgs eventArgs)
   bei DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)
	----------------
	InnerException:

			Type:       MissingMemberException
			Message:    No match for property with name MainView and flags Instance | NonPublic | Public | Static on type DevExpress.XtraEditors.SidePanelContainer.
			Data:       0 entries
			Stack trace:

   bei Fasterflect.Emitter.LookupUtils.GetMember(CallInfo callInfo) in D:\a\1\s\Fasterflect\Emitter\LookupUtils.cs:Zeile 70.
   bei Fasterflect.Emitter.MemberGetEmitter.CreateDelegate() in D:\a\1\s\Fasterflect\Emitter\MemberGetEmitter.cs:Zeile 57.
   bei Fasterflect.Emitter.BaseEmitter.GetDelegate() in D:\a\1\s\Fasterflect\Emitter\BaseEmitter.cs:Zeile 52.
   bei Fasterflect.PropertyExtensions.DelegateForGetPropertyValue(Type type, String name, Flags bindingFlags) in D:\a\1\s\Fasterflect\Extensions\Core\PropertyExtensions.cs:Zeile 136.
   bei Fasterflect.PropertyExtensions.DelegateForGetPropertyValue(Type type, String name) in D:\a\1\s\Fasterflect\Extensions\Core\PropertyExtensions.cs:Zeile 116.
   bei Fasterflect.PropertyExtensions.GetPropertyValue(Object obj, String name) in D:\a\1\s\Fasterflect\Extensions\Core\PropertyExtensions.cs:Zeile 50.
   bei Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.GetViewControl(PredefinedMap predefinedMap, CompositeView view, String model) in D:\a\1\s\src\Modules\ModelMapper\Services\PredefinedMapService.cs:Zeile 311.
   bei Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.BindData(ValueTuple`3 data, Object control) in D:\a\1\s\src\Modules\ModelMapper\Services\ModelBindingService.cs:Zeile 115.
   bei Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.<>c.<ViewModelProperties>b__9_1(ValueTuple`3 _) in D:\a\1\s\src\Modules\ModelMapper\Services\ModelBindingService.cs:Zeile 142.
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:Zeile 39.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ExceptionServicesImpl.cs:Zeile 16.
   bei System.Reactive.ExceptionHelpers.Throw(Exception exception) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ExceptionServices.cs:Zeile 14.
   bei System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Stubs.cs:Zeile 16.
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:Zeile 62.
   bei System.Reactive.Sink`1.ForwardOnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 60.
   bei System.Reactive.HalfSerializer.ForwardOnError[T](ISink`1 sink, Exception ex, Int32& wip, Exception& error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\HalfSerializer.cs:Zeile 76.
   bei System.Reactive.Linq.ObservableImpl.TakeUntil`2._.OnError(Exception ex) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\TakeUntil.cs:Zeile 62.
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Merge.cs:Zeile 244.
   bei System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\AutoDetachObserver.cs:Zeile 77.
   bei System.Reactive.ObserverBase`1.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:Zeile 59.
   bei Xpand.Extensions.Reactive.Utility.Utility.<>c__DisplayClass8_1`1.<Trace>b__3(Exception e) in D:\a\1\s\src\Extensions\Xpand.Extensions.Reactive\Xpand.Extensions.Reactive\Utility\Trace.cs:Zeile 59.
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:Zeile 62.
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Merge.cs:Zeile 244.
   bei System.Reactive.Sink`2.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 96.
   bei System.Reactive.Sink`1.ForwardOnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 60.
   bei System.Reactive.Sink`2.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 96.
   bei System.Reactive.Sink`1.ForwardOnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 60.
   bei System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Merge.cs:Zeile 244.
   bei System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\AutoDetachObserver.cs:Zeile 77.
   bei System.Reactive.ObserverBase`1.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:Zeile 59.
   bei Xpand.Extensions.Reactive.Utility.Utility.<>c__DisplayClass8_1`1.<Trace>b__3(Exception e) in D:\a\1\s\src\Extensions\Xpand.Extensions.Reactive\Xpand.Extensions.Reactive\Utility\Trace.cs:Zeile 59.
   bei System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:Zeile 62.
   bei System.Reactive.Sink`1.ForwardOnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 60.
   bei System.Reactive.Sink`2.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 96.
   bei System.Reactive.Sink`1.ForwardOnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 60.
   bei System.Reactive.Sink`2.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 96.
   bei System.Reactive.Sink`1.ForwardOnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 60.
   bei System.Reactive.Sink`2.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 96.
   bei System.Reactive.Sink`1.ForwardOnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 60.
   bei System.Reactive.Sink`2.OnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 96.
   bei System.Reactive.Sink`1.ForwardOnError(Exception error) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 60.
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:Zeile 43.
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 49.
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\SelectMany.cs:Zeile 1371.
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 49.
   bei System.Reactive.IdentitySink`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\IdentitySink.cs:Zeile 15.
   bei System.Reactive.Subjects.Subject`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:Zeile 139.
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 49.
   bei System.Reactive.IdentitySink`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\IdentitySink.cs:Zeile 15.
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 49.
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:Zeile 47.
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 49.
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:Zeile 47.
   bei System.Reactive.Sink`1.ForwardOnNext(TTarget value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Sink.cs:Zeile 49.
   bei System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnNext(TResult value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\SelectMany.cs:Zeile 946.
   bei System.Reactive.Subjects.Subject`1.OnNext(T value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:Zeile 139.
   bei System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.<>c__DisplayClass3_0.<GetHandler>b__1(Object sender, TEventArgs eventArgs) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\FromEventPattern.cs:Zeile 39.
   bei System.EventHandler.Invoke(Object sender, EventArgs e)
   bei DevExpress.ExpressApp.View.OnControlsCreated()
   bei Xpand.ExpressApp.XpandListView.OnControlsCreated() in D:\a\1\s\Xpand\Xpand.ExpressApp\Xpand.ExpressApp\XpandListView.cs:Zeile 35.
   bei DevExpress.ExpressApp.View.CreateControls()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.EnsureViewControl()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.FillViewSite()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.OnViewChanged()
   bei DevExpress.ExpressApp.Win.Templates.ViewSiteManager.SetView(View view)
   bei DevExpress.ExpressApp.Win.Templates.Ribbon.DetailRibbonFormV2.DevExpress.ExpressApp.Templates.IFrameTemplate.SetView(View view)
   bei DevExpress.ExpressApp.Frame.SetTemplateView(View view)
   bei DevExpress.ExpressApp.Frame.SetView(View view, Boolean updateControllers, Frame sourceFrame, Boolean disposeOldView)
			InnerException is null

**Comment by apobekiaris** [comment] 2020-01-06 02:48
is it reproducible on a sample solution?

**Comment by apobekiaris** [comment] 2020-01-17 12:48
r u sure you are on the latest here? this exception does not make sense it is already treated in lab 

see https://github.com/eXpandFramework/DevExpress.XAF/blob/2875b329fed6556d26441dfb29ae747e9e998ce6/src/Modules/ModelMapper/Services/PredefinedMapService.cs#L311

https://github.com/eXpandFramework/DevExpress.XAF/blob/2875b329fed6556d26441dfb29ae747e9e998ce6/src/Modules/ModelMapper/Services/PredefinedMapService.cs#L373-L381

**Comment by apobekiaris** [comment] 2020-01-18 05:56
Issue is prioritized as it contains one of the following labels ***sponsor***, **installation**, **contribution**, **nuget**, **breakingchange**, **ReproSample**, **Deployment**

**Comment by CWolffIF** [comment] 2020-01-19 09:07
I´m on 19.2.502.2. But the same problem.

o match for property with name MainView and flags Instance | NonPublic | Public on type DevExpress.XtraEditors.SidePanelContainer.

   bei Fasterflect.Emitter.LookupUtils.GetMember(CallInfo callInfo) in D:\a\1\s\Fasterflect\Emitter\LookupUtils.cs:Zeile 70.
   bei Fasterflect.Emitter.MemberGetEmitter.CreateDelegate() in D:\a\1\s\Fasterflect\Emitter\MemberGetEmitter.cs:Zeile 57.
   bei Fasterflect.Emitter.BaseEmitter.GetDelegate() in D:\a\1\s\Fasterflect\Emitter\BaseEmitter.cs:Zeile 52.
   bei Fasterflect.PropertyExtensions.DelegateForGetPropertyValue(Type type, String name, Flags bindingFlags) in D:\a\1\s\Fasterflect\Extensions\Core\PropertyExtensions.cs:Zeile 136.
   bei Fasterflect.PropertyExtensions.GetPropertyValue(Object obj, String name, Flags bindingFlags) in D:\a\1\s\Fasterflect\Extensions\Core\PropertyExtensions.cs:Zeile 70.
   bei Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.GetPropertyValueSafe(Object o, String name, Nullable`1 flags) in D:\a\1\s\src\Modules\ModelMapper\Services\PredefinedMapService.cs:Zeile 376.
   bei Xpand.XAF.Modules.ModelMapper.Services.PredefinedMapService.GetViewControl(PredefinedMap predefinedMap, CompositeView view, String model) in D:\a\1\s\src\Modules\ModelMapper\Services\PredefinedMapService.cs:Zeile 311.
   bei Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.BindData(ValueTuple`3 data, Object control) in D:\a\1\s\src\Modules\ModelMapper\Services\ModelBindingService.cs:Zeile 116.
   bei Xpand.XAF.Modules.ModelMapper.Services.ModelBindingService.<>c.<ViewModelProperties>b__9_1(ValueTuple`3 _) in D:\a\1\s\src\Modules\ModelMapper\Services\ModelBindingService.cs:Zeile 143.
   bei System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:Zeile 39.

**Comment by apobekiaris** [comment] 2020-01-19 13:01
the exception really say that a GridListEditor is detected and not an XpandCategorizedListEditor. However I do not see why this can happen and failed to repro it in my sample where i installed the XpandTreeListEditorWin and open a categorized listview.

Please modify the same to match your configuration or supply a repro 
[Solution10.zip](https://github.com/eXpandFramework/eXpand/files/4082683/Solution10.zip)
sample

**Comment by apobekiaris** [comment] 2020-01-19 13:04
maybe it has also to do with your model config as i did not change my model at all

**Comment by expand** [comment] 2020-01-20 09:58
The [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/lab) repository includes commits that relate to this task:

* [ModelMapper: Handle binding exceptions if ListEditor does not return the predifined control #652](https://github.com/eXpandFramework/DevExpress.XAF/commit/ac284586225fbf8f444679bcd5b96d072579ba96)

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use the [Xpand.XAF.Modules](https://github.com/eXpandFramework/DevExpress.XAF) directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by apobekiaris** [comment] 2020-01-20 10:10
this should address the problem, note that due to custom archtecture of CategorizedListEditor ModelMapper auto binding is not supported.

**Comment by expand** [comment] 2020-01-29 09:05
Issue is deprioritized as 
o Assignee found and scheduled for uto-close if not activity in the next 60 days.

**Comment by expand** [comment] 2020-03-29 21:02
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2020-03-29 21:02 UTC
