### ISSUE TITLE
ModelViewInheritance not working when creating IModelMergedDifferences in Setup(ApplicationModulesManager moduleManager)

### ISSUE THREAD

**Issue by krombipils** [eXpandFramework/eXpand#946] opened 2022-08-23 12:51 UTC
I'm trying to use your ModelViewInheritance module similar to the sample linked on the documentation (https://www.youtube.com/watch?v=uh4SMPwJ5pU). Unfortunately this does not seem to work.

I think the problem is, that ModelViewInheritanceService.CreateUnchangeableLayer() is executed before IModelMergedDifferences nodes are created in the moduleManager.WhenGeneratingModelNodes<IModelMergedDifferences>(){...}.

**Comment by apobekiaris** [comment] 2022-08-23 13:22
does not work in runtime as well?

**Comment by krombipils** [comment] 2022-08-24 06:27
For me it also does not work in runtime. I attached a small sample project.
In this project I create ModelMergedDifference nodes with View = BaseObject_ListView.
```
moduleManager.WhenGeneratingModelNodes<IModelMergedDifferences>()
    .Do(differences =>
    {
        var diff = differences.AddNode<IModelMergedDifference>("MergedDiffFromSetup");
        diff.View = (IModelListView)differences.Application.Views.GetNode("BaseObject_ListView");
    }).Subscribe(this);
```
ModelChanges of the BaseObject_ListView, e.g. ShowGroupPanel are not merged, e.g. to the PersistentClass1_ListView.
For the PersistentClass2_ListView I added another ModelMergedDifference node with the ModelEditor. Now the changes are merged to PersistentClass2_ListView.

I think the ModelViewInheritance module has another problem, when using the new simplified XAF solution structure: By default there is no win specific module anymore and changes are directly stored in the Model.xafml of the win executable project. The Model.xafml has a 'Content' build action, but the CreateUnchangeableLayer implementation searches for embedded resources diffs. Am I right?

[ModdelInheritanceTest.zip](https://github.com/eXpandFramework/eXpand/files/9413429/ModdelInheritanceTest.zip)

**Comment by apobekiaris** [comment] 2022-08-24 06:33
>I think the ModelViewInheritance module has another problem, when using the new simplified XAF solution structure: By default there is no win specific module anymore and changes are directly stored in the Model.xafml of the win executable project. The Model.xafml has a 'Content' build action, but the CreateUnchangeableLayer implementation searches for embedded resources diffs. Am I right?

most probably the package was not desinged with the front end model in mind. It will take some time to examine the case be aware. Do I understand correctly that the problem is also there when u using embedded models?

**Comment by apobekiaris** [comment] 2022-08-24 06:39
> By default there is no win specific module anymore and changes are directly stored in the Model.xafml of the win executable project. The Model.xafml 

i think we already have an auto merge all embeded models functionality, did u tried to add a new embeded model to your project?

https://github.com/eXpandFramework/Reactive.XAF/blob/58e357d4d619144da1bf5f2f982f35236c1b873c/src/Modules/Reactive/RXApp.cs#L140

**Comment by krombipils** [comment] 2022-08-24 06:49
Never used your MDO concept. So what do you suggest? Add a MDO embedded resource to the win project and check if ModelViewInheritance works?

**Comment by apobekiaris** [comment] 2022-08-24 06:57
if it works for a module with embedded models the MDO is no differnent

**Comment by apobekiaris** [comment] 2022-08-24 07:00
and the Win project if it has a ModuleBase descenant also behaves like a hybrid module-frontend

**Comment by apobekiaris** [comment] 2022-08-24 07:01
if it does not have just add one and register it with your app

**Comment by krombipils** [comment] 2022-08-24 07:04
You mean adding an embedded model in addition to the model.xafml in the win project? Nevertheless right now, the ModelViewInheritance does not work, when using embedded models (I have one in my agnostic module).
Imho the service does not 'see' the ModelMergedDifferences nodes, because they are created 'too late'.

**Comment by apobekiaris** [comment] 2022-08-24 07:14
>You mean adding an embedded model in addition to the model.xafml i

yes and the Win project should also have a ModuleBase descenant added to your Application.Modules collection

>Imho the service does not 'see' the ModelMergedDifferences nodes, because they are created 'too late'.

first u add the node, then u compile then u open again the ME and it should see

**Comment by apobekiaris** [comment] 2022-08-24 07:17
note there are a few test on the package that test the runtime and they green so at least some parts should work

**Comment by apobekiaris** [comment] 2022-08-24 07:21
apologies the previous link i posted with MDO should not work in this case as it uses `WhenCreateCustomUserModelDifferenceStore` this is too late merge, u need to add a new agnostic module project to host your models

**Comment by apobekiaris** [comment] 2022-08-24 07:28
```cs
 var streams = modelDifferenceStores.OfType<ResourcesModelStore>()
                .Select(store => {
                    var assembly = ((Assembly) store.GetFieldValue("assembly"));
                    var value = (string) store.GetFieldValue("modelDesignedDiffsName");
                    var name = assembly.GetManifestResourceNames().FirstOrDefault(s => s.EndsWith(value));
                    return name != null ? (stream:assembly.GetManifestResourceStream(name),assembly,modelName:value) : default;
                })
                .WhereNotDefault();
```

modifying this method on the `ModelViewInheritanceService` to included additional emdedded models might help resolve this case

**Comment by krombipils** [comment] 2022-08-24 07:37
In my agnostic model I have this embedded model diff:

![grafik](https://user-images.githubusercontent.com/8317504/186358335-821393f1-3332-475a-8a3e-53833632358b.png)

In the runtime model editor, the MergedDifference node is created, but for the PersistentClass1_Listview, the diff is not inherited/merged:

![grafik](https://user-images.githubusercontent.com/8317504/186358746-6b406574-f880-4b18-b4fe-918b1c6951a1.png)

But for the PersistentClass2_ListView (with a MergedDifference node created in the embedded resource model), the diff is merged:

![grafik](https://user-images.githubusercontent.com/8317504/186358894-ef032864-0c26-46d2-917c-fc050967ea3c.png)

**Comment by apobekiaris** [comment] 2022-08-24 07:42
assuimng u already 

>first u add the node, then u compile then u open again the ME and it should see

unfortunately i cannot help u unless i spent time debugging it

**Comment by krombipils** [comment] 2022-08-24 07:43
No problem, it's not that urgentl

**Comment by apobekiaris** [comment] 2022-08-24 07:44
it should be rather easy to debug it yourself is just one method `CreateUnchangeableLayer` and u know how to compile now. In any case if u attempt it let me know please so we do not double spent resources

**Comment by krombipils** [comment] 2022-08-24 07:59
I already tried to debug. In CreateUnchangeableLayer you load the embedded models and try to get 'rules'. But nodes added in the `WhenGeneratingModelNodes` are not 'physically' added to the models. Am I wrong?

**Comment by apobekiaris** [comment] 2022-08-24 08:03
as far as I remember was some model layers  reposition, that is collecting the diffs and position them in the generation layer, not sure if this funcationality works, but should given that u said:

>But for the PersistentClass2_ListView (with a MergedDifference node created in the embedded resource model), the diff is merged:

and as I understand u having problems merging views of different types e.g. BaseListView

**Comment by krombipils** [comment] 2022-08-24 08:17
> u having problems merging views of different types e.g. BaseListView
I'm having problems, when trying to setup the merging 'dynamically' in the the Setup(...) override. Adding the merging directly/physically in the model is working fine.
Actually I'm trying to combine cloning and merging (based on some conditions) and therefore I need this dynamic/runtime approach

**Comment by apobekiaris** [comment] 2022-08-24 08:31
hopefully your sample demos your problem clear enough, if not please repost it

**Comment by apobekiaris** [comment] 2022-09-12 07:18
I upgrade Harmony and restore design time for all related packages e.g. `ModelViewInheritance`, `ModelMapper` etc. In my tests I see no issues for both Xpand or native ModelEditors. However the approach of the doc is not implemented you can use the model for now

**Comment by apobekiaris** [comment] 2022-09-12 07:18
that for the next minor

**Comment by apobekiaris** [comment] 2022-09-12 07:53
The pre-release [4.221.5.0](https://github.com/eXpandFramework/Reactive.XAF/releases/tag/4.221.5.0) in the [Reactive.XAF](https://github.com/eXpandFramework/Reactive.XAF/tree/lab) `lab` branch  includes commits that relate to this task:

* [Update Harmony and enable desingTime patch #946](https://github.com/eXpandFramework/Reactive.XAF/commit/5ab609899dda755c5b7a01207ea6ca043332e660)

To minimize version conflicts we recommend that you use the [Xpand.XAF.Core.All](https://www.nuget.org/packages/Xpand.XAF.Core.All), [Xpand.XAF.Win.All](https://www.nuget.org/packages/Xpand.XAF.Win.All), [Xpand.XAF.Web.All](https://www.nuget.org/packages/Xpand.XAF.Web.All) packages. Doing so, all packages will be at your disposal and .NET will add a dependecy only to those packages that you actually use and not to all (see the [Modules installation-registrations](https://youtu.be/LvxQ-U_0Sbg) youtube video).
<details>
    <summary>Released packages:</summary>
<a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions'>Xpand.Extensions v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Blazor'>Xpand.Extensions.Blazor v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Mono.Cecil'>Xpand.Extensions.Mono.Cecil v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud'>Xpand.Extensions.Office.Cloud v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Office.Cloud.Google.Blazor'>Xpand.Extensions.Office.Cloud.Google.Blazor v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.Reactive'>Xpand.Extensions.Reactive v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF'>Xpand.Extensions.XAF v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Extensions/Xpand.Extensions.XAF.Xpo'>Xpand.Extensions.XAF.Xpo v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Blazor v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.Common v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/tests'>Xpand.TestsLib.EasyTest v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/tools/Xpand.VersionConverter'>Xpand.VersionConverter v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Core.All v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/AutoCommit'>Xpand.XAF.Modules.AutoCommit v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Blazor'>Xpand.XAF.Modules.Blazor v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/BulkObjectUpdate'>Xpand.XAF.Modules.BulkObjectUpdate v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneMemberValue'>Xpand.XAF.Modules.CloneMemberValue v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/CloneModelView'>Xpand.XAF.Modules.CloneModelView v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Email'>Xpand.XAF.Modules.Email v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/GridListEditor'>Xpand.XAF.Modules.GridListEditor v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/HideToolBar'>Xpand.XAF.Modules.HideToolBar v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Hangfire'>Xpand.XAF.Modules.JobScheduler.Hangfire v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/JobScheduler.Notification'>Xpand.XAF.Modules.JobScheduler.Notification v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/MasterDetail'>Xpand.XAF.Modules.MasterDetail v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelMapper'>Xpand.XAF.Modules.ModelMapper v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ModelViewInheritance'>Xpand.XAF.Modules.ModelViewInheritance v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google'>Xpand.XAF.Modules.Office.Cloud.Google v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Calendar'>Xpand.XAF.Modules.Office.Cloud.Google.Calendar v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Google.Tasks'>Xpand.XAF.Modules.Office.Cloud.Google.Tasks v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Microsoft'>Xpand.XAF.Modules.Office.Cloud.Microsoft v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Calendar'>Xpand.XAF.Modules.Office.Cloud.Microsoft.Calendar v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.Cloud.Microsoft.Todo'>Xpand.XAF.Modules.Office.Cloud.Microsoft.Todo v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Office.DocumentStyleManager'>Xpand.XAF.Modules.Office.DocumentStyleManager v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/OneView'>Xpand.XAF.Modules.OneView v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/PositionInListView'>Xpand.XAF.Modules.PositionInListView v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ProgressBarViewItem'>Xpand.XAF.Modules.ProgressBarViewItem v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RazorView'>Xpand.XAF.Modules.RazorView v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive'>Xpand.XAF.Modules.Reactive v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger'>Xpand.XAF.Modules.Reactive.Logger v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Client.Win'>Xpand.XAF.Modules.Reactive.Logger.Client.Win v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Logger.Hub'>Xpand.XAF.Modules.Reactive.Logger.Hub v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Reactive.Rest'>Xpand.XAF.Modules.Reactive.Rest v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/RefreshView'>Xpand.XAF.Modules.RefreshView v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SequenceGenerator'>Xpand.XAF.Modules.SequenceGenerator v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Speech'>Xpand.XAF.Modules.Speech v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/StoreToDisk'>Xpand.XAF.Modules.StoreToDisk v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/SuppressConfirmation'>Xpand.XAF.Modules.SuppressConfirmation v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/TenantManager'>Xpand.XAF.Modules.TenantManager v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewEditMode'>Xpand.XAF.Modules.ViewEditMode v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewItemValue'>Xpand.XAF.Modules.ViewItemValue v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/ViewWizard'>Xpand.XAF.Modules.ViewWizard v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules/Windows'>Xpand.XAF.Modules.Windows v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Web.All v.4.221.5</a></br> <a href='https://github.com/eXpandFramework/Reactive.XAF/tree/master/src/Modules'>Xpand.XAF.Win.All v.4.221.5</a></br>
</details>

Please update the related Nuget packages and test if issues is addressed. These are nightly nuget packages available only from our [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget/).

If you do not use these packages directly but through a module of the main eXpandFramework project, please wait for the bot to notify you again when integration is finished or update the related packages manually.

Thanks a lot for your contribution.

**Comment by expand** [comment] 2024-01-19 21:02
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2024-01-19 21:02 UTC
Labels: Bug, ModelViewInheritance, Reactive.XAF
