### ISSUE TITLE
Error opening the Win Model

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#385] opened 2019-04-26 10:35 UTC
I got an Error opening the Win Model in VS.
How can I debug this?

The error occurred:

	Type:       InvalidOperationException
	Message:    Exception occurs while initializing the 'Xpand.XAF.Modules.ViewEditMode.ViewEditModeModule' module: Der Typeninitialisierer für "Xpand.XAF.Modules.ViewEditMode.ViewEditModeService" hat eine Ausnahme verursacht.
	Data:       0 entries
	Stack trace:

   bei DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
   bei DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   bei DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(ModuleBase module, String assembliesPath, List`1 additionalModules, ISecurityStrategyBase securityInstance)
   bei DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
	----------------
	InnerException:

			Type:       TypeInitializationException
			Message:    Der Typeninitialisierer für "Xpand.XAF.Modules.ViewEditMode.ViewEditModeService" hat eine Ausnahme verursacht.
			Data:       0 entries
			Stack trace:

   bei Xpand.XAF.Modules.ViewEditMode.ViewEditModeModule.Setup(ApplicationModulesManager moduleManager)
   bei DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
			----------------
			InnerException:

					Type:       TypeInitializationException
					Message:    Der Typeninitialisierer für "Xpand.XAF.Modules.Reactive.RxApp" hat eine Ausnahme verursacht.
					Data:       0 entries
					Stack trace:

   bei Xpand.XAF.Modules.Reactive.RxApp.get_Application()
   bei Xpand.XAF.Modules.ViewEditMode.ViewEditModeService..cctor()
					----------------
					InnerException:

							Type:       InvalidOperationException
							Message:    Unable to redirect methods whose bodies are too close to one another.
							Data:       0 entries
							Stack trace:

   bei Ryder.MethodRedirection..ctor(MethodBase original, MethodBase replacement, Boolean start)
   bei Ryder.Redirection.CreateDynamicRedirection(MethodBase method, Int32& id)
   bei Ryder.Redirection.Observe(MethodBase method)
   bei Xpand.XAF.Modules.Reactive.RxApp..cctor()
							InnerException is null

**Comment by apobekiaris** [comment] 2019-04-26 12:12
u can debug as any design time error, you need to attach a 2nd VS instance with break on error and open the designer. Alternatively if you use the Xpand.ModelEditor you can  enable debug.

![image](https://user-images.githubusercontent.com/159464/56806114-aa391800-6833-11e9-9d8f-af1c6bfb9ab0.png)

running the Xpand.ModelEditor after this it will show a messagebox like

![image](https://user-images.githubusercontent.com/159464/56806649-36980a80-6835-11e9-93c8-0f77e0b355bb.png)

the box stops the execution until u attach to the editor 

![image](https://user-images.githubusercontent.com/159464/56806718-68a96c80-6835-11e9-8d03-07533eba0215.png)

if u use the VS embedded editor, you need to build the project before opening the editor on the first installation of any standalone module and most probably the exception will not raised,

**Comment by apobekiaris** [comment] 2019-04-26 15:06
>if u use the VS embedded editor, you need to build the project before opening the editor on the first installation of any standalone module and most probably the exception will not raised,

this is because VS copies the assemblies in a random path and if you run the editor before the build the unpatched assembly will be copied. Restarting VS will force regeneration of the random path and it will work if u build afterwards.

**Comment by CWolffIF** [comment] 2019-04-27 08:44
Hi Tolis,

when I try to open the modeleditor from
![screen1](https://user-images.githubusercontent.com/43132306/56847263-3bae9580-68d9-11e9-9d3b-bcfb970ce983.PNG)

I get the error
------------------OpenModelEditor------------------

Version missmatch for:
C:\Users\CWolff\Documents\Xpand\VSIX\Xpand.ExpressApp.ModelEditor.exe

The modeleditor is from the installation 18.2.704.0. Where can I get the right Version?

**Comment by apobekiaris** [comment] 2019-04-27 08:51
Hi,

VSIX should install the correct version if you update it. It is possible to use many versions for each dx version using the VSIX.Options.ModelEditor (VS/Option/Xpand). Xpandmodeleditor will discover the right version by parsing the project references.

see also my answer here

https://github.com/eXpandFramework/eXpand/issues/321#issuecomment-461500675

let me know if you have more questions please

**Comment by CWolffIF** [comment] 2019-04-27 13:53
Hi Tolis,

if I start it with Xpand.ExpressApp.ModelEditor.exe there is no Error.

If I start it with the VS embedded Editor I got the Error

The error occurred:

	Type:       InvalidOperationException
	Message:    Exception occurs while initializing the 'Xpand.XAF.Modules.ViewEditMode.ViewEditModeModule' module: Der Typeninitialisierer für "Xpand.XAF.Modules.ViewEditMode.ViewEditModeService" hat eine Ausnahme verursacht.
	Data:       0 entries
	Stack trace:

   bei DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
   bei DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   bei DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(ModuleBase module, String assembliesPath, List`1 additionalModules, ISecurityStrategyBase securityInstance)
   bei DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
	----------------
	InnerException:

			Type:       TypeInitializationException
			Message:    Der Typeninitialisierer für "Xpand.XAF.Modules.ViewEditMode.ViewEditModeService" hat eine Ausnahme verursacht.
			Data:       0 entries
			Stack trace:

   bei Xpand.XAF.Modules.ViewEditMode.ViewEditModeModule.Setup(ApplicationModulesManager moduleManager)
   bei DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
			----------------
			InnerException:

					Type:       TypeInitializationException
					Message:    Der Typeninitialisierer für "Xpand.XAF.Modules.Reactive.RxApp" hat eine Ausnahme verursacht.
					Data:       0 entries
					Stack trace:

   bei Xpand.XAF.Modules.Reactive.RxApp.get_Application()
   bei Xpand.XAF.Modules.ViewEditMode.ViewEditModeService..cctor()
					----------------
					InnerException:

							Type:       InvalidOperationException
							Message:    Unable to redirect methods whose bodies are too close to one another.
							Data:       0 entries
							Stack trace:

   bei Ryder.MethodRedirection..ctor(MethodBase original, MethodBase replacement, Boolean start)
   bei Ryder.Redirection.CreateDynamicRedirection(MethodBase method, Int32& id)
   bei Ryder.Redirection.Observe(MethodBase method)
   bei Xpand.XAF.Modules.Reactive.RxApp..cctor()
							InnerException is null

**Comment by CWolffIF** [comment] 2019-04-27 13:54
Sorry, closed by mistake.

**Comment by apobekiaris** [comment] 2019-04-27 16:20
search your disk for Xpand.XAF.Modules and delete those found in C:\program files while all VS instances are closed. Then reopen VS and try again.

**Comment by apobekiaris** [comment] 2019-04-27 16:23
as I understand the problem is that you install a xaf.modules package and you open VS Model editor without building the project. When u install a package there is a document opened with the message `Build the project before opening ME`.

am i wrong in my assumptions?

**Comment by CWolffIF** [comment] 2019-04-27 17:34
Hi Tolis,

maybe this is the problem. The Xpand.XAF.Modules are loaded in 2 Versions. One by the standard Xpand Installation and the other by the new Nugets.

	Xpand.XAF.Modules.AutoCommit, Version=0.0.10.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.AutoCommit\v4.0_0.0.10.0__c52ffed5d5ff0958\Xpand.XAF.Modules.AutoCommit.dll
	Xpand.XAF.Modules.AutoCommit, Version=0.0.16.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\ap1dog2-01\Xpand.XAF.Modules.AutoCommit.dll
	Xpand.XAF.Modules.CloneMemberValue, Version=1.2.15.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\mfzotebc01\Xpand.XAF.Modules.CloneMemberValue.dll
	Xpand.XAF.Modules.CloneModelView, Version=0.0.4.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\-cb_figu01\Xpand.XAF.Modules.CloneModelView.dll
	Xpand.XAF.Modules.MasterDetail, Version=0.0.10.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.MasterDetail\v4.0_0.0.10.0__c52ffed5d5ff0958\Xpand.XAF.Modules.MasterDetail.dll
	Xpand.XAF.Modules.MasterDetail, Version=0.0.16.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\4x2r8ieu01\Xpand.XAF.Modules.MasterDetail.dll
	Xpand.XAF.Modules.ModelViewInheritance, Version=1.1.12.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\syf8jfrp01\Xpand.XAF.Modules.ModelViewInheritance.dll
	Xpand.XAF.Modules.ModelViewInheritance, Version=1.1.6.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.ModelViewInheritance\v4.0_1.1.6.0__c52ffed5d5ff0958\Xpand.XAF.Modules.ModelViewInheritance.dll
	Xpand.XAF.Modules.Reactive, Version=1.2.15.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\tmrsnxzm01\Xpand.XAF.Modules.Reactive.dll
	Xpand.XAF.Modules.Reactive, Version=1.2.9.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.Reactive\v4.0_1.2.9.0__c52ffed5d5ff0958\Xpand.XAF.Modules.Reactive.dll
	Xpand.XAF.Modules.SuppressConfirmation, Version=0.0.10.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.SuppressConfirmation\v4.0_0.0.10.0__c52ffed5d5ff0958\Xpand.XAF.Modules.SuppressConfirmation.dll
	Xpand.XAF.Modules.SuppressConfirmation, Version=0.0.16.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\gczmliv701\Xpand.XAF.Modules.SuppressConfirmation.dll
	Xpand.XAF.Modules.ViewEditMode, Version=1.2.15.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\koudl15501\Xpand.XAF.Modules.ViewEditMode.dll
	Xpand.XAF.Modules.ViewEditMode, Version=1.2.9.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.ViewEditMode\v4.0_1.2.9.0__c52ffed5d5ff0958\Xpand.XAF.Modules.ViewEditMode.dll

**Comment by apobekiaris** [comment] 2019-04-27 17:36
aha it makes sense, let me refactor accordingly there should be an issue there for sure.

**Comment by apobekiaris** [comment] 2019-04-27 17:38
interested to know more details on how did you investigate this result.

**Comment by CWolffIF** [comment] 2019-04-27 18:51
Hi Tolis,

the easiest way would be that I should read the lines "Modules loaded".  :-(
But before that, I
- Uninstalled Xpand
- Repaired Devexpress Installation
- Installed Xpand
- Followed your suggestions (delete all stuff and rebuild everything new)

I have here now another error (opening the VS model editor), maybe the same stuff but there is now a codelinenumer. Maybe it helps.


27.04.19 20:41:01.271	================================================================================
The error occurred:

	Type:       InvalidOperationException
	Message:    Exception occurs while initializing the 'Xpand.XAF.Modules.Reactive.ReactiveModule' module: Der Typeninitialisierer für "Xpand.XAF.Modules.Reactive.RxApp" hat eine Ausnahme verursacht.
	Data:       0 entries
	Stack trace:

   bei DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
   bei DevExpress.ExpressApp.ApplicationModulesManager.Load(ITypesInfo typesInfo, Boolean loadTypesInfo)
   bei DevExpress.ExpressApp.Utils.DesignerModelFactory.CreateModulesManager(XafApplication application, String configFileName, String assembliesPath)
   bei DevExpress.ExpressApp.Design.ModelEditor.ModelLoader.LoadModel(ITypeDiscoveryService typeDiscoveryService, ITypeResolutionService typeResolutionService, String targetDiffFileName, IDisposable& obj)
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.CreateModelEditorController()
   bei DevExpress.ExpressApp.Design.ModelEditor.EditorPane.PrivateInit(String fileName, ProjectItem currentProjectItem, IVsHierarchy pvHier)
	----------------
	InnerException:

			Type:       TypeInitializationException
			Message:    Der Typeninitialisierer für "Xpand.XAF.Modules.Reactive.RxApp" hat eine Ausnahme verursacht.
			Data:       0 entries
			Stack trace:

   bei Xpand.XAF.Modules.Reactive.RxApp.Connect(XafApplication application)
   bei Xpand.XAF.Modules.Reactive.ReactiveModule.Setup(ApplicationModulesManager moduleManager) in D:\a\1\s\src\Modules\Agnostic\Reactive\Module.cs:Zeile 46.
   bei DevExpress.ExpressApp.ApplicationModulesManager.SetupModules()
			----------------
			InnerException:

					Type:       InvalidOperationException
					Message:    Unable to redirect methods whose bodies are too close to one another.
					Data:       0 entries
					Stack trace:

   bei Ryder.MethodRedirection..ctor(MethodBase original, MethodBase replacement, Boolean start)
   bei Ryder.Redirection.CreateDynamicRedirection(MethodBase method, Int32& id)
   bei Ryder.Redirection.Observe(MethodBase method)
   bei Xpand.XAF.Modules.Reactive.RxApp..cctor() in D:\a\1\s\src\Modules\Agnostic\Reactive\RXApp.cs:Zeile 52.
					InnerException is null


and all modules are loaded twice.

	Xpand.XAF.Modules.AutoCommit, Version=0.0.10.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.AutoCommit\v4.0_0.0.10.0__c52ffed5d5ff0958\Xpand.XAF.Modules.AutoCommit.dll
	Xpand.XAF.Modules.AutoCommit, Version=0.0.16.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\ltaujyva01\Xpand.XAF.Modules.AutoCommit.dll
	Xpand.XAF.Modules.CloneMemberValue, Version=1.2.15.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\lgqaw8n-01\Xpand.XAF.Modules.CloneMemberValue.dll
	Xpand.XAF.Modules.CloneModelView, Version=0.0.4.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\6vrd25sj01\Xpand.XAF.Modules.CloneModelView.dll
	Xpand.XAF.Modules.MasterDetail, Version=0.0.10.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.MasterDetail\v4.0_0.0.10.0__c52ffed5d5ff0958\Xpand.XAF.Modules.MasterDetail.dll
	Xpand.XAF.Modules.MasterDetail, Version=0.0.16.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\wbhj5p9p01\Xpand.XAF.Modules.MasterDetail.dll
	Xpand.XAF.Modules.ModelViewInheritance, Version=1.1.12.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\wp7vgq_601\Xpand.XAF.Modules.ModelViewInheritance.dll
	Xpand.XAF.Modules.ModelViewInheritance, Version=1.1.6.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.ModelViewInheritance\v4.0_1.1.6.0__c52ffed5d5ff0958\Xpand.XAF.Modules.ModelViewInheritance.dll
	Xpand.XAF.Modules.Reactive, Version=1.2.15.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\tbyf5eik01\Xpand.XAF.Modules.Reactive.dll
	Xpand.XAF.Modules.Reactive, Version=1.2.9.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.Reactive\v4.0_1.2.9.0__c52ffed5d5ff0958\Xpand.XAF.Modules.Reactive.dll
	Xpand.XAF.Modules.SuppressConfirmation, Version=0.0.16.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\2zs0t0k701\Xpand.XAF.Modules.SuppressConfirmation.dll
	Xpand.XAF.Modules.ViewEditMode, Version=1.2.15.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\5dfwwuwc01\Xpand.XAF.Modules.ViewEditMode.dll
	Xpand.XAF.Modules.ViewEditMode, Version=1.2.9.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Xpand.XAF.Modules.ViewEditMode\v4.0_1.2.9.0__c52ffed5d5ff0958\Xpand.XAF.Modules.ViewEditMode.dll

**Comment by apobekiaris** [comment] 2019-04-27 18:56
I did not check this yet as I am refactoring the VersionConverter with a mutex to synchronize patching. I will update you again once I research.

So to be clear there are problems when you do not have Xpand in GAC?

**Comment by CWolffIF** [comment] 2019-04-27 19:07
Do you have a scritp to only uninstall the Xpand.XAF. modules from GAC?

**Comment by apobekiaris** [comment] 2019-04-27 19:17
not really but i can write one 

```ps1
[System.Reflection.Assembly]::Load("System.EnterpriseServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
$publish = New-Object System.EnterpriseServices.Internal.Publish
Get-ChildItem pathtoxpandassemblies Xpand.XAF*.dll|ForEach-Object{
    $publish.GacRemove( $_.FullName)
}
```

**Comment by apobekiaris** [comment] 2019-04-27 19:19
actually u do not need a script for this

use Explorer to go to C:\Windows\Microsoft.NET\assembly\GAC_MSIL\
fileter and delete the assemblies u want

**Comment by CWolffIF** [comment] 2019-04-27 19:28
Hi,

I uninstalled all Xpand.XAF modules from the GAC. The problem is still the same and all modules are loaded twice (but with the same Version).

	Xpand.XAF.Modules.AutoCommit, Version=0.0.16.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\DevProjects\iXISJH\iXISXRM\iXISXRM.Module.Win\bin\Debug\Xpand.XAF.Modules.AutoCommit.dll
	Xpand.XAF.Modules.AutoCommit, Version=0.0.16.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\ott7jltl01\Xpand.XAF.Modules.AutoCommit.dll
	Xpand.XAF.Modules.CloneMemberValue, Version=1.2.15.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\vjebiyks01\Xpand.XAF.Modules.CloneMemberValue.dll
	Xpand.XAF.Modules.CloneModelView, Version=0.0.4.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\kvkp0tjg01\Xpand.XAF.Modules.CloneModelView.dll
	Xpand.XAF.Modules.MasterDetail, Version=0.0.16.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\DevProjects\iXISJH\iXISXRM\iXISXRM.Module.Win\bin\Debug\Xpand.XAF.Modules.MasterDetail.dll
	Xpand.XAF.Modules.MasterDetail, Version=0.0.16.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\afhexukk01\Xpand.XAF.Modules.MasterDetail.dll
	Xpand.XAF.Modules.ModelViewInheritance, Version=1.1.12.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\DevProjects\iXISJH\iXISXRM\iXISXRM.Module.Win\bin\Debug\Xpand.XAF.Modules.ModelViewInheritance.dll
	Xpand.XAF.Modules.ModelViewInheritance, Version=1.1.12.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\ahnk7qug01\Xpand.XAF.Modules.ModelViewInheritance.dll
	Xpand.XAF.Modules.Reactive, Version=1.2.15.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\DevProjects\iXISJH\iXISXRM\iXISXRM.Module.Win\bin\Debug\Xpand.XAF.Modules.Reactive.dll
	Xpand.XAF.Modules.Reactive, Version=1.2.15.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\tpedpkxa01\Xpand.XAF.Modules.Reactive.dll
	Xpand.XAF.Modules.SuppressConfirmation, Version=0.0.16.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\vfkdvq0s01\Xpand.XAF.Modules.SuppressConfirmation.dll
	Xpand.XAF.Modules.ViewEditMode, Version=1.2.15.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\DevProjects\iXISJH\iXISXRM\iXISXRM.Module.Win\bin\Debug\Xpand.XAF.Modules.ViewEditMode.dll
	Xpand.XAF.Modules.ViewEditMode, Version=1.2.15.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958, Location=C:\Users\CWolff\AppData\Local\Microsoft\VisualStudio\15.0_65935e22\ProjectAssemblies\fxl0zd4m01\Xpand.XAF.Modules.ViewEditMode.dll

**Comment by apobekiaris** [comment] 2019-04-27 19:29
thnks I will update asap

**Comment by apobekiaris** [comment] 2019-04-27 19:29
u restarted VS I presume after uninstallation

**Comment by CWolffIF** [comment] 2019-04-27 19:35
Si, cause my internet went down i started the whole computer

**Comment by expand** [comment] 2019-06-27 03:01
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2019-06-27 03:01 UTC
Labels: Bug, Standalone_XAF_Modules, ViewEditMode, XpandModelEditor
