### ISSUE TITLE
Dashboard datasource name problem

### ISSUE THREAD

**Issue by ramos41** [eXpandFramework/eXpand#363] opened 2019-04-09 11:26 UTC
Hello,

When we create a dashboard with Expand, version 18.1.6.3, the name of the business object class is written to the Name property of the ObjectDataSource in the dashboard definition.
For example ;
My business object name is "MT_Activity",
XafDisplayNameAttribute is "Activity"

Datasource (with Expand, version 18.1.6.3):

`<DataSources>
    <ObjectDataSource Name="MT_Activity" ComponentName="MT_Activity">
      <DataSource Type="Solution1.Module.BusinessObjects.MT_Activity, Solution1.Module, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
    </ObjectDataSource>
  </DataSources>
`

But when I create a dashboard project without Expand libraries, I see that the display name attribute of the class is written to the Name property as follows ;

Datasource (without Expand libraries):

`
<DataSources>
        <ObjectDataSource Name="Activity" ComponentName="objectDataSource1">
            <DataSource Type="Dashboard.Module.BusinessObjects.MT_Activity, Dashboard.Module, Version=1.0.7038.24829, Culture=neutral, PublicKeyToken=null" />
        </ObjectDataSource>
    </DataSources>
`

So Object data source name is different with expand (MT_Activity) and without expand (Activity) . Why XafDisplayNameAttribute of the business object is ignored in Expand?

For this reason, dashboards with Expand are not displayed in the web application. How can we solve this? I have uploaded screenshot, xml files and business object to help you.
Thanks,

[Data.zip](https://github.com/eXpandFramework/eXpand/files/3058664/Data.zip)

**Comment by apobekiaris** [comment] 2019-04-10 17:25
Hi,

I patched the current sources with 

https://github.com/eXpandFramework/eXpand.lab/commit/8a13613a949b63657bf3345894bdfa76b6dae339

However If you do not want to upgrade you have to rebuild the sources of your version using the build.ps1 on the root and applying the patch.

**Comment by expand** [comment] 2019-04-10 18:47
eXpand.lab release [18.2.703.6](https://github.com/eXpandFramework/lab/releases/18.2.703.6) includes commit [XtraDashboard: DashoardName is not localized #363](https://github.com/eXpandFramework/153812905/commit/8a13613a949b63657bf3345894bdfa76b6dae339) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by ramos41** [comment] 2019-04-11 11:14
Thanks for your information. But I'm using version 18.1.6.3 and unfortunately I cannot upgrade to version 18.2.703.6. Can you give me these changes in version 18.1.6.3?

**Comment by apobekiaris** [comment] 2019-04-11 13:46
hmm it looks like the `eXpand bot` is posting broken links.

the releated commit is here

https://github.com/eXpandFramework/eXpand.lab/commit/8a13613a949b63657bf3345894bdfa76b6dae339

the raw file that you may replace as is and recompile the `DashboardModule` is here
https://raw.githubusercontent.com/eXpandFramework/eXpand.lab/8a13613a949b63657bf3345894bdfa76b6dae339/Xpand/Xpand.ExpressApp.Modules/Dashboard/Services/Extensions.cs

**Comment by ramos41** [comment] 2019-05-02 13:39
Hello,

Any command on line 89 of the code in the Extensions.cs file that you sent is guessing it works incorrectly. I have ObjectDataSource in DataSources, but your function is adding another ObjectDataSource and deleting the wrong ObjectDataSource. Also, the DataSource items are not updated. I'm adding my old xml file and my new xml file.
[xml.zip](https://github.com/eXpandFramework/eXpand/files/3138242/xml.zip)

**Comment by apobekiaris** [comment] 2019-05-03 09:46
hhm apologies for this, I need some research/testing time as I cannot tell the problem from a first look. I will update you again.

**Comment by apobekiaris** [comment] 2019-05-06 15:54
did you replaced the whole file or just the changed method? I previously suggested by mistake to replace the whole file.

**Comment by ramos41** [comment] 2019-05-07 06:10
I just changed the part about me.

**Comment by apobekiaris** [comment] 2019-05-07 06:31
you only replaced this part and not the whole file is that what you meant?

```cs
var name = CaptionHelper.GetClassCaption(typeWrapper.Type.FullName);
                    var dataSource = new DashboardObjectDataSource{
                        DataSourceType = typeWrapper.Type,
                        Name = name,
                        ComponentName = name
                    };
```

**Comment by apobekiaris** [comment] 2019-05-07 06:32
and still the function misbehaves while previously worked fine?

**Comment by ramos41** [comment] 2019-05-07 06:42
Of course. The function is working incorrectly.

**Comment by apobekiaris** [comment] 2019-05-09 16:34
Hi again and apologies for the delay, the xpand dashboard module had some major issues in 19.1 which was in priority. Now all major 19.1 issues are workedaround and I move priority to main project tickets.

I tested your classes again and I see the XafDisplayAttribute is respected.
![image](https://user-images.githubusercontent.com/159464/57470228-0159d680-7291-11e9-8cb5-f010bff767b6.png)

>The function is working incorrectly. Because the function is adding more than a DataSource. In fact, he had to wipe out the old one.

I am a bit confused here, what do you mean u had to wipe out the old one? This is a non supported scenario and I will provide a fix for those property editors in the next minor.

You can try these controller for make the editor single select
in agnostic module add 
```cs
using System;
using System.Linq;
using DevExpress.ExpressApp;
using Xpand.ExpressApp.Dashboard.BusinessObjects;
using Xpand.Persistent.Base.General;

namespace XtraDashboardTester.Module {
    public abstract class DisableMultiDashboardTypeController : ObjectViewController<DetailView, DashboardDefinition> {
        protected override void OnActivated() {
            base.OnActivated();
            View.GetItems<IChooseFromListCollectionEditor>().First().ControlCreated += OnControlCreated;
        }

        protected virtual void OnControlCreated(object sender, EventArgs e) {
            
        }
    }
}

```

in your web add
```cs
using System;
using DevExpress.Web;
using Xpand.ExpressApp.XtraDashboard.Web.PropertyEditors;


namespace XtraDashboardTester.Module.Web.Controllers {
    public class DisableMultiDashboardTypeController : Module.DisableMultiDashboardTypeController {
        protected override void OnControlCreated(object sender, EventArgs e) {
            ( ((DashboardTypesEditor) sender).ListBoxTemplate).SelectionMode=ListEditSelectionMode.Single;
        }
    }
}
```

and for win 
```cs
using System;
using System.Collections.Generic;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using Xpand.ExpressApp.XtraDashboard.Win.PropertyEditors;
using ItemCheckEventArgs = DevExpress.XtraEditors.Controls.ItemCheckEventArgs;

namespace XtraDashboardTester.Module.Win.Controllers {
    public class DisableMultiDashboardTypeController : Module.DisableMultiDashboardTypeController {
        protected override void OnControlCreated(object sender, EventArgs e) {
            ((CheckedComboBoxEdit) ((DashboardTypesEditor) sender).Control).Popup += OnPopup;
        }

        private void OnPopup(object sender, EventArgs e) {
            ((CheckedComboBoxEdit) sender).InternalListBox.ItemCheck += OnItemCheck;
        }

        private void OnItemCheck(object sender, ItemCheckEventArgs e) {
            if (e.State == CheckState.Checked) {
                var list = (CheckedListBoxControl) sender;
                var items = new List<CheckedListBoxItem>();
                foreach (var index in list.CheckedIndices) {
                    if (index == e.Index) continue;
                    items.Add(list.Items[index]);
                }

                foreach (var item in items)
                    item.CheckState = CheckState.Unchecked;
            }
        }
    }
}
```

**Comment by ramos41** [comment] 2019-05-10 05:54
I'm talking about ObjectDataSource in new xml. 2. which is being added and the 1st one is not already running Designer. Therefore, ComponentName of first ObjectDataSource should be given to second. And the first ObjectDataSource that is old should be deleted. In the meantime, I work in the 18.1.6 version. Your knowledge.
Thanks.

**Comment by apobekiaris** [comment] 2019-05-10 05:58
How you end up having 2 datasources, do you actually use them both and how? 

I do not think the code should take initiatives and delete datasources silently. Don't you think that you should manually remove the one by yourself?

**Comment by apobekiaris** [comment] 2019-05-10 06:00
>How you end up having 2 datasources

or better question is how to repro this dupliate as it looks datasource myself? I have your files running

**Comment by ramos41** [comment] 2019-05-10 06:03
He's already here. 2 We cannot use ObjectDataSource together. 1. already wrong. Designer also opens it by default. It doesn't help me change DataSource from Designer at the moment. We also have thousands of dashboards, so it's impossible to do it manually. Can't we do something while at least the runtime is loading the dashboard?

**Comment by apobekiaris** [comment] 2019-05-10 06:05
I think I have an idea whats going on, I ll update u again once I have a patch.

**Comment by ramos41** [comment] 2019-05-10 06:07
Thank you.

**Comment by apobekiaris** [comment] 2019-05-10 06:08
do u have thousabd of database as well? how is your app distributed?

**Comment by apobekiaris** [comment] 2019-05-10 06:09
what i really manet to u administer your self the databases or there is an app deployed to your customers?

**Comment by ramos41** [comment] 2019-05-10 06:15
I can manage to my databases with DatabaseUpdater.cs.

**Comment by apobekiaris** [comment] 2019-05-10 15:27
>or this reason, dashboards with Expand are not displayed in the web application. How can we solve this?

let's start from this comment. This is not the reason you have problems, in web. Please provide details of the problem if it continues after my comments.

After researching and consulting the 19.1 XAF sources, it became obvious that locazing the dashboard name makes no sense. At lest latest XAF version use a fixed name so I refactored the method as:

```cs
        private static void AddNewDataSources(IDashboardDefinition dashboardDefinition, DevExpress.DashboardCommon.Dashboard dashboard){
            var dashboardTypesCount = dashboardDefinition.DashboardTypes.Count;
            if (dashboardTypesCount > 1) {
                throw new UserFriendlyException($"{dashboardDefinition.Name} contains {dashboardTypesCount} dashboard types. Only one dashboard type is supported.");
            }
            var wrapper = dashboardDefinition.DashboardTypes.First();
            var dataSource = new DashboardObjectDataSource{
                DataSourceType = wrapper.Type,
                Name = nameof(DashboardObjectDataSource),
                ComponentName = nameof(DashboardObjectDataSource)
            };
            dashboard.DataSources.Add(dataSource);
        }

```

as you see the method assumes that only one dashboard type is used, and we need to add some validation to assure that contract.

so reference the XAF ConditionalAppeareance add this line in the constructor of the `Xpand.ExpressApp.Dashboard.DashboardModule`
```cs
RequiredModuleTypes.Add(typeof(DevExpress.ExpressApp.ConditionalAppearance.ConditionalAppearanceModule));
```
and add the next rules to `Xpand.ExpressApp.Dashboard.BusinessObjects.DashboardDefintion`
```cs
[Appearance("Disable viewitems for existing dashboards",AppearanceItemType.ViewItem, nameof(IsNewObject)+"=False And "+nameof(Xml)+"!=null",Enabled = false,TargetItems = nameof(DashboardTypes)+","+nameof(Xml))]
    public class DashboardDefinition 
...
[RuleRequiredField]
        public IList<ITypeWrapper> DashboardTypes 
```
Replace the next method in `Xpand.ExpressApp.Win.PropertyEditors.RichEdit.RichEditWinPropertyEditor`
```cs
        private void ObjectSpaceOnCommitting(object sender, CancelEventArgs cancelEventArgs) {
            if ((((IModelMemberViewItemRichEdit) Model).RichEdit.PrintXML &&
                 !string.IsNullOrEmpty((string) PropertyValue))) {
                MemberInfo.SetValue(CurrentObject, PropertyValue.ToString().XMLPrint());
            }
        }
```

changes in `Xpand.ExpressApp.Win.PropertyEditors.ChooseFromListCollectionEditor`

add this line in the constructor and override the method.
```cs
        public ChooseFromListCollectionEditor(Type objectType, IModelMemberViewItem info)
            : base(objectType, info) {
            CanUpdateControlEnabled = true;
        }

        protected override bool IsMemberSetterRequired() {
            return false;
        }

```

and finally this Updater can help you fix your existing data
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using DevExpress.DashboardCommon;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.Updating;
using Xpand.ExpressApp.Dashboard.BusinessObjects;
using Xpand.ExpressApp.Dashboard.Services;

namespace Xpand.ExpressApp.Dashboard.DatabaseUpdate {
    public class DashboardObjectDataSourceUpdater : ModuleUpdater {
        public DashboardObjectDataSourceUpdater(IObjectSpace objectSpace, Version currentDBVersion)
            : base(objectSpace, currentDBVersion) {
        }

        public override void UpdateDatabaseAfterUpdateSchema() {
            base.UpdateDatabaseAfterUpdateSchema();
            var dashboardDefinitions = ObjectSpace.GetObjects<DashboardDefinition>().ToArray().Where(definition => definition.DashboardTypes.Count>1).ToArray();
            RemoveInvalidDataSources(dashboardDefinitions);
            RemoveDuplicates(dashboardDefinitions);
        }

        private  void RemoveDuplicates(DashboardDefinition[] dashboardDefinitions){
            foreach (var dashboardDefinition in dashboardDefinitions){
                var dublicates = dashboardDefinition.DashboardTypes
                    .GroupBy(wrapper => wrapper.Type).Where(wrappers => wrappers.Count() > 1).ToArray();
                for (var index = dublicates.Length - 1; index >= 0; index--){
                    var dublicate = dublicates[index];
                    dashboardDefinition.DashboardTypes.Remove(dublicate.First());
                }
            }
        }

        private void RemoveInvalidDataSources(IEnumerable<DashboardDefinition> dashboardDefinitions){
            foreach (var definition in dashboardDefinitions){
                var dashboard = definition.ToDashboard();
                var objectDataSources = dashboard.DataSources.OfType<DashboardObjectDataSource>().ToArray();
                for (var index = objectDataSources.Length - 1; index >= 0; index--){
                    var objectDataSource = objectDataSources[index];
                    if (objectDataSource.DataSourceType == null||XafTypesInfo.Instance.FindTypeInfo(objectDataSource.DataSourceType)==null){
                        dashboard.DataSources.Remove(objectDataSource);
                    }
                }
            }
        }
    }
}
```

I tested both platforms and work fine in 19.1.

the bot will notify you again once all changes integrated with 19.1, so if you comfortable with git you can simply cherry pick them

**Comment by expand** [comment] 2019-05-10 19:53
eXpand.lab release [19.1.200.8](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.200.8) includes commit [Force only one DashboardObjectDataSource #363](https://github.com/eXpandFramework/eXpand.lab/commit/f653e4d5620d3e6db30d25a5a2816eb9d4bfb597),[Support IAppearenceEnabled for ChooseFromListCollectionEditor #363](https://github.com/eXpandFramework/eXpand.lab/commit/cb7fda23860aa54764ec71970c1dfa1157cd7ade),[Dashboard: DisableMultiDashboardTypeController #363](https://github.com/eXpandFramework/eXpand.lab/commit/0f1841fb1bbc4de50b06553f362e6bd58f0af31e) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by ramos41** [comment] 2019-05-13 08:13
Thank you for the information. I'll try this soon.

**Comment by ramos41** [comment] 2019-05-13 13:54
I can try these in version 18.1.6, right?

**Comment by apobekiaris** [comment] 2019-05-13 14:02
i only tested against 19.1 but yes you most probably can apply them there as well

**Comment by apobekiaris** [comment] 2019-05-20 08:08
looks like this case #406 is not covered the method should be refactor as 

```cs
        private static void AddNewDataSources(IDashboardDefinition dashboardDefinition, DevExpress.DashboardCommon.Dashboard dashboard){
            var dashboardTypesCount = dashboardDefinition.DashboardTypes.Count;
            if (dashboardTypesCount > 1) {
                throw new UserFriendlyException($"{dashboardDefinition.Name} contains {dashboardTypesCount} dashboard types. Only one dashboard type is supported.");
            }

            if (dashboardTypesCount == 1) {
                return;
            }
            var wrapper = dashboardDefinition.DashboardTypes.First();
            var dataSource = new DashboardObjectDataSource{
                DataSourceType = wrapper.Type,
                Name = nameof(DashboardObjectDataSource),
                ComponentName = nameof(DashboardObjectDataSource)
            };
            dashboard.DataSources.Add(dataSource);
        }

```

**Comment by apobekiaris** [comment] 2019-05-27 15:10
It looks like this case is coming back unfortunately, everything we talked here is reverterd in the next minor as multiple ObjectDataSources are supported see https://github.com/eXpandFramework/eXpand/issues/406#issuecomment-495128137

apparently the language barrier makes communication hard. So going back to the start to understand your problem.

>When we create a dashboard with Expand, version 18.1.6.3, the name of the business object class is written to the Name property of the ObjectDataSource in the dashboard definition.
For example ;
My business object name is "MT_Activity",
XafDisplayNameAttribute is "Activity"

The leads to this small change in ln 94 of extensions.cs
https://github.com/eXpandFramework/eXpand.lab/blob/d762255bc6ae8ca29fea6fde1fb7a9e30766961c/Xpand/Xpand.ExpressApp.Modules/Dashboard/Services/Extensions.cs#L94
```cs
Name = CaptionHelper.GetClassCaption(typeWrapper.Type.FullName),
```

I tested on an existing dashboard where this line is never hit as there is a linq quaery above testing if new dashboard needed.

I also tested against a new dashboard and now my DataSource lookup in the designer displays the XafDisplayName content.

looking up this post I suggested a similar changed before where you replied

>Any command on line 89 of the code in the Extensions.cs file that you sent is guessing it works incorrectly. I have ObjectDataSource in DataSources, but your function is adding another ObjectDataSource and deleting the wrong ObjectDataSource. Also, the DataSource items are not updated. I'm adding my old xml file and my new xml file.

this I wasn't possible to reproduce, and as I stated before there is a check just above my change in line 89
https://github.com/eXpandFramework/eXpand.lab/blob/d762255bc6ae8ca29fea6fde1fb7a9e30766961c/Xpand/Xpand.ExpressApp.Modules/Dashboard/Services/Extensions.cs#L89

so can provide details on how to repro it?

**Comment by expand** [comment] 2019-05-27 15:39
eXpand.lab release [19.1.302.4](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.302.4) includes commit [Revert "Dashboard: DisableMultiDashboardTypeController #406 #363" 0f1841fb1bbc4de50b06553f362e6bd58f0af31e.](https://github.com/eXpandFramework/eXpand.lab/commit/795ba421ad712bdac60eaefb09d7be549d81d5f9),[Revert "XtraDashboard: DashoardName is not localized #406 #363" commit 8a13613a949b63657bf3345894bdfa76b6dae339.](https://github.com/eXpandFramework/eXpand.lab/commit/0934624316ce52481b70ffa2741b902101cf90bc),[Revert "Force only one DashboardObjectDataSource #363" #406

This reverts commit f653e4d5620d3e6db30d25a5a2816eb9d4bfb597.](https://github.com/eXpandFramework/eXpand.lab/commit/79253eb2f5fba65829b67b663dbf43cd7c495ed1) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment] 2019-07-27 03:01
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2019-07-27 03:01 UTC
Labels: Bug, XtraDashboard
