### ISSUE TITLE
modelassembly.dll always recreated.

### ISSUE THREAD

**Issue by Johnka2** [eXpandFramework/eXpand#900] opened 2022-01-14 13:32 UTC
Steps.
1. create new xaf solution
2. Add eXpandMasterDetailWin to module project and register it
3. Run application multiple times even in release mode
4.modelassembly.dll is always recreated.

Expected behavior
Modelassembly.dll should be generated ounce.

Startup noticeably slow for large models.

**Comment by Kagandaj** [comment] 2023-06-13 11:54
Issue could be caused by Xpand.ExpressApp.MasterDetail.MasterDetailModule 
and 
Xpand.XAF.Modules.MasterDetail.MasterDetailModule  
having the same type name.
Renaming one stopped the problem for me in production

**Comment by apobekiaris** [comment] 2023-06-13 17:37
Sample applicati9on please

**Comment by Kagandaj** [comment] 2023-06-13 18:07
going thru @Johnka2 steps reproduces the problem for .net6 
i renamed Xpand.ExpressApp.MasterDetail.MasterDetailModule to Xpand.ExpressApp.MasterDetail.GridMasterDetailModule
to remove the naming conflict in the moduleinfo file at runtime
and compiled the module. moduleassembly.dll isn't recreated every time in release mode anymore.

another workaround would be to remove the Xpand.ExpressApp.MasterDetail.MasterDetailModule from the application

**Comment by apobekiaris** [comment] 2023-06-13 18:13
>i renamed Xpand.ExpressApp.MasterDetail.MasterDetailModule to Xpand.ExpressApp.MasterDetail.GridMasterDetailModule

I cannot follow where is the conflict?

**Comment by Kagandaj** [comment] 2023-06-13 18:39
look at these two modules
Xpand.ExpressApp.MasterDetail.MasterDetailModule
Xpand.XAF.Modules.MasterDetail.MasterDetailModule

they have the same type name "MasterDetailModule"
at runtime when a xaf application starts it examines ModulesVersionInfo file.
since the two modules are versioned differently xaf thinks that the version has changed for one of these modules.
remember the ModulesVersionInfo  does not use full type names.
as a result modelassembly.dll will always be regenarated.
A solution would be to rename one of these modules

**Comment by apobekiaris** [comment] 2023-06-13 18:41
aha I agree we may have issues there I will rename, thnks!

**Comment by expand** [comment] 2024-02-22 21:02
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2024-02-22 21:02 UTC
Labels: Question, MasterDetail, Reactive.XAF
