### ISSUE TITLE
Issue with percentage range set of pivot grid rules in Dashboard module

### ISSUE THREAD

**Issue by disteSp** [eXpandFramework/eXpand#333] opened 2019-02-28 12:22 UTC
As shown in attached screenshots, setting percentage ranges in rules of pivot grid seems not working correctly in version 1.8.4 of Xpand dashboard module

**To Reproduce**
1.add a pivot grid to the dashboard
2add some fileds
3 add percentage calculated filed to values
4 add rule on pivot grid
5 add a range rule (use % ranges enabled)

Error:
pivot cells are not highlighted as expected by percentage of the range rule 

[PivotRuleRangeError.docx](https://github.com/eXpandFramework/eXpand/files/2914896/PivotRuleRangeError.docx)

**Comment by apobekiaris** [comment] 2019-02-28 13:25
thnks for the post however if possible post a sample+db and a screencast of the exact steps. There are many free apps for screen-capture and they can really help to collaborate better. Your doc is hard to read and understand.

**Comment by disteSp** [comment] 2019-02-28 13:53
[PivotRuleRangeError.docx](https://github.com/eXpandFramework/eXpand/files/2915259/PivotRuleRangeError.docx)

Thanks for reply. 
Here attached a new document with more detailed instructions and screenshots

**Comment by apobekiaris** [comment] 2019-02-28 15:41
A possible cause of the issue is that the Range Set uses % ranges and the target column also displays percent values. That is, the rule calculates a percentage of percent values, which is probably is not what you want to achieve. Uncheck the "Use % ranges" checkbox to see if the result will be more appropriate.

**Comment by disteSp** [comment] 2019-02-28 17:18
Ok thanks now It works, For example to for 2.5% I had to set  0.025.

**Comment by expand** [comment] 2019-04-30 03:04
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed** 2019-04-30 03:04 UTC
Labels: Bug, Standalone_XAF_Modules, XtraDashboard
