### ISSUE TITLE
Pessimistic View Controller not working

### ISSUE THREAD

**Issue by DSCmattb** [eXpandFramework/eXpand#655] opened 2020-01-08 13:21 UTC
Hi, I've added the following attributes to my class.

`[PessimisticLocking]
 [Custom("ViewEditMode", "View")]
 [PessimisticLockingMessageAttribute("AnId")]`

However the Pessimistic Unlock action never shows.

I attempted to debug this myself by copying out the code from your controller and running it manually, which throws errors about not finding the LockedUser attribute. I can see that it added this directly to the table and I can see that it "should" add this when the SystemModule is included and run. I can see it has been added to our Win designer. 

Any thoughts on where to go from here?

Running Win 10, VS 2019, .net 4.6.2

**Comment by DSCmattb** [comment] 2020-01-08 13:22
Also does the unlock action always appear because I can't see under what context it appears, it looks like its bound to every view, is that correct?

**Comment by apobekiaris** [comment] 2020-01-08 13:38
nope as the source code dictates the action is disable by default and enable only

https://github.com/eXpandFramework/eXpand/blob/01a65994c310251669d463246e4d4388b76d781d/Xpand/Xpand.Persistent/Xpand.Persistent.Base/General/Controllers/PessimisticLockingViewController.cs#L62

**Comment by DSCmattb** [comment] 2020-01-26 07:16
Once setting the properties as described on your blog post I get the following error when refreshing the view:

`Can't find property 'LockedUser'

   at DevExpress.Data.Filtering.Helpers.EvaluatorContextDescriptorDefault.GetPropertyValue(Object source, String property, Boolean isPath)
   at DevExpress.Data.Filtering.Helpers.EvaluatorContextDescriptorDefault.GetPropertyValue(Object source, EvaluatorProperty propertyPath)
   at DevExpress.Data.Filtering.Helpers.ExpressionEvaluatorCore.Visit(OperandProperty theOperand)
   at DevExpress.Data.Filtering.Helpers.ExpressionEvaluatorCoreBase.Process(CriteriaOperator operand)
   at DevExpress.Data.Filtering.Helpers.ExpressionEvaluatorCoreBase.Visit(BinaryOperator theOperator)
   at DevExpress.Data.Filtering.Helpers.ExpressionEvaluatorCoreBase.Process(CriteriaOperator operand)
   at DevExpress.Data.Filtering.Helpers.ExpressionEvaluatorCoreBase.Visit(GroupOperator theOperator)
   at DevExpress.Data.Filtering.Helpers.ExpressionEvaluatorCoreBase.Process(CriteriaOperator operand)
   at DevExpress.Data.Filtering.Helpers.ExpressionEvaluatorCoreBase.Evaluate(EvaluatorContext evaluationContext, CriteriaOperator evaluatorCriteria, IComparer customComparer)
   at DevExpress.Data.Filtering.Helpers.ExpressionEvaluatorCoreBase.Fit(EvaluatorContext evaluationContext, CriteriaOperator filterCriteria)
   at Xpand.ExpressApp.Logic.LogicRuleEvaluator.Fit(Object targetObject, ILogicRuleObject logicRule)
   at Xpand.ExpressApp.Logic.LogicRuleExecutor.<>c__DisplayClass12_0`1.<Execute>b__0(ILogicRuleObject o)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Xpand.ExpressApp.Logic.LogicRuleExecutor.Execute[T](View view, Boolean invertCustomization, ExecutionContext executionContext, Object currentObject, EventArgs eventArgs)
   at Xpand.ExpressApp.Logic.LogicRuleViewController.ViewOnCurrentObjectChanged(Object sender, EventArgs args)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at DevExpress.ExpressApp.View.OnCurrentObjectChanged()
   at DevExpress.ExpressApp.DetailView.set_CurrentObject(Object value)
   at DevExpress.ExpressApp.ObjectView.objectSpace_Reloaded(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at DevExpress.ExpressApp.BaseObjectSpace.OnReloaded()
   at DevExpress.ExpressApp.Xpo.XPObjectSpace.Reload()
   at DevExpress.ExpressApp.BaseObjectSpace.Refresh()
   at DevExpress.ExpressApp.SystemModule.RefreshController.Refresh()
   at DevExpress.ExpressApp.Actions.ActionBase.ExecuteCore(Delegate handler, ActionBaseEventArgs eventArgs)`

**Comment by apobekiaris** [comment] 2020-01-26 08:55
the LockedUser property is dynamically created at 

https://github.com/eXpandFramework/eXpand/blob/f916916dcf045b5317c48a8d7740fdc169f86fe4/Xpand/Xpand.ExpressApp/Xpand.ExpressApp/SystemModule/XpandSystemModule.cs#L88-L108

**Comment by DSCmattb** [comment] 2020-01-26 10:24
Yep, the property gets added but it only seems to happen on a View Refresh

**Comment by apobekiaris** [comment] 2020-01-26 12:12
CustomizedTypesInfo is called from XAF when the app starts and I do not see how this can fail using the posted code.

**Comment by DSCmattb** [comment] 2020-01-26 12:34
Me either, the actual property is present on the object. If I inspect it with visual studio I can see it is in fact present I can see it adds into the database the oid as its meant to but when you refresh the view itself you get that error.

On 26 Jan. 2020 10:12 pm, Apostolis Bekiaris <notifications@github.com> wrote:

CustomizedTypesInfo is called from XAF when the app starts and I do not see how this can fail using the posted code.

-

**Comment by apobekiaris** [comment] 2020-01-26 12:35
do u have a sample?

**Comment by DSCmattb** [comment] 2020-01-27 05:25
[TestXAF.zip](https://github.com/eXpandFramework/eXpand/files/4115670/TestXAF.zip)

If you create a test object, save it. Reopen it modify the title, click on the oid and restart visual studio it will then show its locked, as expected.

Then open the new;y created object and refresh the view. Error throws.

**Comment by expand** [comment] 2020-01-27 14:44
Issue is prioritized as it contains one of the following labels **bronze-sponsor**, **sponsor**, **backer**, **installation**, **ShowStopper**, **nuget**, **contribution**, **breakingchange**, **ReproSample**, **Deployment**, **must-have**

**Comment by DSCmattb** [comment] 2020-02-04 23:57
hey @apobekiaris, any update on this one?

**Comment by apobekiaris** [comment] 2020-02-05 01:38
sorry not yet, the case needs research and priority is not reached. When there is an update will post results. If you in the meantime work it out let me know so not to lost resources in vain.

**Comment by apobekiaris** [comment] 2020-02-24 16:36
I haven't research deeply the reason for this however I see that the xpo session is not aware of the object after refresh, maybe is a bug on XPO or maybe it was when this feature was designed. In any case I provided a workaround in next minor.

**Comment by expand** [comment] 2020-02-24 18:18
eXpand.lab release [19.2.601.13](https://github.com/eXpandFramework/eXpand.lab/releases/19.2.601.13) includes commit that relate to this task:

* [Improve EvaluatorContextDescriptor detection #655](https://github.com/eXpandFramework/eXpand.lab/commit/48bb933e98b3143e01ac8503b4fd9efb506676f7)

Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by expand** [comment] 2020-02-28 10:49
Issue is `deprioritized` as `no Assignee found` and scheduled for `auto-close` if no activity in the next `60 days`. Thanks a lot for your contribution.

**Comment by expand** [comment] 2020-04-29 21:01
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2020-04-29 21:01 UTC
Labels: Bug, ReproSample

**Comment by DSCmattb** [comment] 2020-07-29 05:14
Can confirm the new version addresses this issue.

However a separate issue has started. When adding the attributes to class A that inherits XPCustomObject it works fine and works as expected. However when modifying object B that inherits XPLiteObject we now get the application tracking changes to the object and asking for merging. on save as per the following image from DX.

https://docs.devexpress.com/eXpressAppFramework/images/concurrencymerge117396.png

This wasn't a problem previously and I have confirmed that removing the attribute on Object A stops this from happening.

Object A and B are linked 1-1 but the objects being attempted do not have data in the relations.
