### ISSUE TITLE
What package is Xpand.ExpressApp.Attributes included in

### ISSUE THREAD

**Issue by DSCmattb** [eXpandFramework/eXpand#801] opened 2020-11-09 03:32 UTC
𝗤𝘂𝗲𝘀𝘁𝗶𝗼𝗻
We use AllowEditAttribute and are converting to use the nuget packages.

Which package is it included in?

**Comment by apobekiaris** [comment] 2020-11-09 08:44
this class lives in the Xpand.ExpressApp assembly which declares the XpandSystemModule and the hosting page is the `eXpandSystem`

**Comment by DSCmattb** [comment] 2020-11-09 13:15
Yeah so I have the references in place from when we were using the DLL.

The module it is going into is netstandard2.0 which used to work with the dll itself.

![image](https://user-images.githubusercontent.com/26134058/98545503-51c84f00-22e1-11eb-8e81-21fbbf1dfd30.png)

This is what I see for the references with that included:

![image](https://user-images.githubusercontent.com/26134058/98545577-6e648700-22e1-11eb-88b9-2612640980c8.png)

**Comment by apobekiaris** [comment] 2020-11-09 13:20
first I want to mention that since you interested for the `eXpandSystemWin` you do not need to install the eXpandLib and the eXpandSystem as it is implied that they are transitive dependencies and they will be install as well.

can u reproduce the problem in an empty XAF solution where the eXpandSystemWin is installed? provide the sample if yes please

**Comment by apobekiaris** [comment] 2020-11-09 13:25
>The module it is going into is netstandard2.0 which used to work with the dll itself.

not exactly sure what u mean by this but at lease the main framework packages targetframework is the net461 at least for now

**Comment by DSCmattb** [comment] 2020-11-09 13:35
Hmm, so previously we were running the assemblies in our .netstandard agnostic module base without any issues. However since it comes through nuget it no longer seems to pull the reference through correctly. Ill change back to net462 for now.

**Comment by apobekiaris** [comment] 2020-11-09 13:38
without a sample cannot say much, however note that we have all WIndows,WebForms,WindowsDesktop(.netcore) consuming the packages from the Easytests and everything is green

**Comment by DSCmattb** [comment] 2020-11-09 13:39
I just made a sample app and switching it from net462 to netstandard2.0 causes issues

I can send it if you'd like.

**Comment by apobekiaris** [comment] 2020-11-09 13:40
yes i can have a look please post it

**Comment by DSCmattb** [comment] 2020-11-09 13:45
[BlankXAF.zip](https://github.com/eXpandFramework/eXpand/files/5510862/BlankXAF.zip)

**Comment by apobekiaris** [comment] 2020-11-09 14:43
unfortunately i fail to start your project cause of the broken dependecies, however from a quick look saw that you tried to install `eXpandSystem` which is a net461 package in a netstandard2.0 module? Judging from what we know that netstandard is a platform  specification  what you try to do does not make sense

**Comment by DSCmattb** [comment] 2020-11-09 23:30
However when we using Xpand 20.1.401.0 with the dll's referenced manually it worked correctly. Even though the module was netstandard2.0

**Comment by apobekiaris** [comment] 2020-11-10 09:42
as I said the **main framework** assemblies targetframework was net461 and did not change. Your sample tries to consume .NETFramework assemblies from netstandard this is totally wrong. What is ported to netstartard are the Xpand.XAF.Modules.* ,Xpand.Extensions.* and they can be consumed from .NET461.

**Comment by expand** [comment] 2022-05-19 21:03
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2022-05-19 21:03 UTC
Labels: Question
