### ISSUE TITLE
Xpand.XAF.Modules.MasterDetail.MasterDetailModule Bug

### ISSUE THREAD

**Issue by cevious** [eXpandFramework/eXpand#592] opened 2019-10-15 09:43 UTC
Hi

Exception of Xpand Latest Version 

Xpand.XAF.Modules.MasterDetail.MasterDetailModule required System.ValueTuple version :4.0.2

Check Log

[eXpressAppFramework.log](https://github.com/eXpandFramework/eXpand/files/3728484/eXpressAppFramework.log)

**Comment by apobekiaris** [comment] 2019-10-15 10:29
Does explicitly installing the missing System.Value tuple in your front end project helps?

**Comment by apobekiaris** [comment] 2019-10-16 07:15
I am not sure how you installed the packages but the System.ValueTuple is not missing when Nugets are used. I just confirm that all your xpand modules run with no warning in an empty XAF app. Using explicit references means u have to call the dependecies instead of Nuget

**Comment by cevious** [comment] 2019-10-16 07:18
From VS 2019 / debug mode its running fine. But from installer/production environment it showing error

I am using nuget packagerefrence in my entire solution with latest eXpand module.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by apobekiaris** [comment] 2019-10-16 07:19
> installer/production environment

meaning?

**Comment by apobekiaris** [comment] 2019-10-18 04:23
>FileLoadException

this is a FileLoadException which means that the assembly is not published and most probably depends on your configuration. eXpand builds with the WarnAsError flag meaning that even if there is one warning such as a version conflict or file not found the builds fail.

However if you can provide a sample to reproduce the case happy to research the reason.

**Comment by expand** [comment] 2019-12-18 03:01
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2019-12-18 03:01 UTC
Labels: Bug, MasterDetail, Standalone_XAF_Modules
