### ISSUE TITLE
Does this thing work?

### ISSUE THREAD

**Issue by shahidmughal** [eXpandFramework/eXpand#826] opened 2020-12-30 17:08 UTC
I have been trying to use expandframework for last two years. Can't move forward from Nuget installation. Does this works?

**Comment by apobekiaris** [comment] 2020-12-30 17:13
There are proofs, we have EasyTests that Easy 4 different XafApplication types Win, Web, Blazor, WinDesktop consuming the same packages you have issues to use.

I do not say that they perfect of course however your post also says totally nothing.

**Comment by shahidmughal** [comment] 2020-12-30 17:20
@apobekiaris I don't mean to be disrespectful of the work you guys are doing. I know it is amazing work that you guys have put together. But what is the point if a person like me with average technical skill can't even start. If the goal is to get help to get started then please make it clear so we can consider this option.

**Comment by apobekiaris** [comment] 2020-12-30 17:29
> But what is the point if a person like me with average technical skill can't even start. If the goal is to get help to get started then please make it clear so we can consider this option.

This is the reason we switch to nuget so to handle the dependencies transparently.  This video demos how we expect our user to consume the packages. 

https://www.youtube.com/watch?v=LvxQ-U_0Sbg&t=1s

Try to describe your problem and how it can be reproduced rather than rhetorical posts

**Comment by shahidmughal** [comment] 2020-12-30 17:30
Ok. Let me provide the problem I am facing. 

I am using XAF for more than 2 years successfully with a team of developers. I love it. I had found out there is a great open source expandframework. I found your website and github page years ago. The only piece missing is how one can start? There is a page called "How do you start?" But it doesn't say anything. I understand it is a open source project and you may not have all the resources, but putting a simple step by step instructions shouldn't be that difficult. I can volunteer to do that if it helps. I may use your professional expertise for projects I am leading. But I need to pass the first barrior.

**Comment by shahidmughal** [comment] 2020-12-30 17:32
> > But what is the point if a person like me with average technical skill can't even start. If the goal is to get help to get started then please make it clear so we can consider this option.
> 
> This is the reason we switch to nuget so to handle the dependencies transparently. This video demos how we expect our user to consume the packages.
> 
> https://www.youtube.com/watch?v=LvxQ-U_0Sbg&t=1s
> 
> Try to describe your problem and how it can be reproduced rather than rhetorical posts

Great video. I tried to follow up and got stuck in the first step. Here is the error:
Install-Package : Unable to resolve dependency 'akarnokd.reactive_extensions'. Source(s) used: 'nuget.org', 'expandframework', 'Microsoft Visual Studio Offline Packages', 'DevExpress 20.2 Local'.
At line:1 char:41
+ Get-XpandPackages Release XAFExtensions|Install-Package
+                                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
I tried to install the reactive extension from the original author without any sucesss.

**Comment by apobekiaris** [comment] 2020-12-30 17:37
"How do you start?"

I would start from the `documented` packages from the [DevExpress.XAF](https://github.com/eXpandFramework/DevExpress.XAF/tree/master/src/Modules) repository.

**Comment by apobekiaris** [comment] 2020-12-30 17:48
please record a screencast of your actions it is not clear what you doing

**Comment by shahidmughal** [comment] 2020-12-30 17:49
Here is the video for my steps.

https://user-images.githubusercontent.com/638570/103371408-37f6ed00-4a84-11eb-9700-08ca67714134.mp4

**Comment by apobekiaris** [comment] 2020-12-30 18:03
I cannot tell why this behavior nothing looks wrong. Can you try installing the akarnokd.reactive_extensions package before installing Xpand. Check the prerelease for find the akarnokd.reactive_extensions

**Comment by shahidmughal** [comment] 2020-12-30 18:15
I did that and it didn't help. Please see below. 

![image](https://user-images.githubusercontent.com/638570/103372776-d2a4fb00-4a87-11eb-96b1-3156fc01526e.png)

**Comment by apobekiaris** [comment] 2020-12-30 18:16
> Check the prerelease for find the akarnokd.reactive_extensions

I meant check the Include Prerelease button next to the search

**Comment by shahidmughal** [comment] 2020-12-30 18:49
Thanks for the pointer. Was able to make progress. Now stuck at this step.

![image](https://user-images.githubusercontent.com/638570/103374517-a344bd00-4a8c-11eb-8102-7042e5a7e918.png)

**Comment by apobekiaris** [comment] 2020-12-30 18:52
your system complain that mscorlib 2.0.0.0 cannot be loaded, it beats me

edit VersionConverter.ps1 and remove its contents and build again

**Comment by apobekiaris** [comment] 2020-12-30 18:53
mscorllib version 2.0.0.0 really not sounds right but impossible to guess

**Comment by apobekiaris** [comment] 2020-12-30 18:54
I would suggest you try another machine

**Comment by ndamgaard** [comment] 2020-12-30 19:11
Shahid,

I have gotten a bit further than you. Maybe we can help each other. It
seems like this guy is condescending and wants money. I have spent more
than 100 hours trying to get these things to work.

Niels

**Comment by apobekiaris** [comment] 2020-12-30 19:28
@ndamgaard 

as I posted before it is the **same packages** consumed from our tests in a public Azure pipeline. 

https://github.com/eXpandFramework/DevExpress.XAF/blob/master/src/Tests/EasyTests/TestApplication/TestApplication.Win/TestApplication.Win.csproj#L133

so in an Azure Virtual Machine they work fine and here you can find the Azure VM [specs](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md). 

you can find the test reports also here https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=15423&view=ms.vss-test-web.build-test-results-tab

**Comment by shahidmughal** [comment] 2020-12-30 22:06
> mscorllib version 2.0.0.0 really not sounds right but impossible to guess

Hi @apobekiaris - Finally I was able to complete initial steps. Here is the finding.

- Make sure Nuget PackageReference format is default in VS Nuget Setting.

Once I did the above, I was able to go smoothly. At least I am at a point I can move forward and I am sure I will have further issues. But this first hurdle was putting me off every time I wanted to give a try to XAF.Modules

Thanks for quick response and putting up with my frustration. I respect your work. Please continue. 

Shahid

**Comment by shahidmughal** [comment] 2020-12-30 22:08
@ndamgaard Would love to get your help if stuck. At the moment I think I am good. Thanks for your support.

**Comment by ndamgaard** [comment] 2020-12-30 22:21
@shahidmughal I am trying to learn all of this too. There is a lot of amazing functionality here. But there is a great deal to know to make it all work. I apologize to you and @apobekiaris for showing my frustration.

**Comment by shahidmughal** [comment] 2020-12-31 00:05
> @shahidmughal I am trying to learn all of this too. There is a lot of amazing functionality here. But there is a great deal to know to make it all work. I apologize to you and @apobekiaris for showing my frustration.

@ndamgaard All of us have been there. This is the occupational hazard of technology profession. Things don't work. They worked yesterday, stopped working today. It works on my machine but not on your machine so on and so forth. We have come very far and in this age of instant gratifications, expectations are very high. 

Nice to interact with you. Happy new year to both of you.

**Comment by apobekiaris** [comment] 2020-12-31 07:54
That's why I try to emphasize on the Azure builds, which the tell us 

Hey, I work on a clean Azure Devops VM, try to guess what you are doing different in your system if you can not ask for help if still cannot a few sponsoring bucks can take you out of any trouble today.

**Comment by apobekiaris** [comment] 2020-12-31 07:55
Happy new year to all

**Comment by expand** [comment] 2022-05-28 21:02
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.

**Closed by expand** 2022-05-28 21:02 UTC
